### ISSUE TITLE
PHP Fatal Errors in API v2/v3 endpoints in 2.7 RC

### ISSUE THREAD

**Issue by ragulka** [woocommerce/woocommerce#13517]
A fatal PHP error occurs when trying to update an order fee via V2 or V3 of the REST API in 2.7 RC1 (and in master as well), because the `WC_API_Orders` class is trying to call a protected method (`WC_Order_Item_Fee::set_total_tax()`).

V3:
```
PHP Fatal error:  Uncaught Error: Call to protected method WC_Order_Item_Fee::set_total_tax() from context 'WC_API_Orders' in /web/app/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-orders.php:1157
Stack trace:
#0 /web/app/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-orders.php(890): WC_API_Orders->set_fee(Object(WC_Order), Array, 'update')
#1 /web/app/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-orders.php(610): WC_API_Orders->set_item(Object(WC_Order), 'fee', Array, 'update')
#2 /web/app/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(372): WC_API_Orders->edit_order(400, Array)
#3 /web/app/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-server.php(223): WC_API_Server->dispatch()
#4 /web/app/plugins/woocommerce/includes/class-wc-legacy-api.php(111): W in /web/app/plugins/woocommerce/includes/api/legacy/v3/class-wc-api-orders.php on line 1157
```

V2:
```
[09-Mar-2017 07:25:05 UTC] PHP Fatal error:  Uncaught Error: Call to protected method WC_Order_Item_Fee::set_total_tax() from context 'WC_API_Orders' in /web/app/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-orders.php:1111
Stack trace:
#0 /web/app/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-orders.php(842): WC_API_Orders->set_fee(Object(WC_Order), Array, 'update')
#1 /web/app/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-orders.php(569): WC_API_Orders->set_item(Object(WC_Order), 'fee', Array, 'update')
#2 /web/app/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-server.php(372): WC_API_Orders->edit_order(400, Array)
#3 /web/app/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-server.php(223): WC_API_Server->dispatch()
#4 /web/app/plugins/woocommerce/includes/class-wc-legacy-api.php(269): W in /web/app/plugins/woocommerce/includes/api/legacy/v2/class-wc-api-orders.php on line 1111
````

## STEPS TO REPRODUCE THE ISSUE

`PUT /wc-api/v3/orders/<id>` with the following:

```json
{
  "order": {
    "fee_lines": [
      {
        "id": 61,
        "title": "Gift wrapping",
        "tax_class": "",
        "total": "20.00",
        "total_tax": "4.00"
      },
    ]
  }
}
```

**Comment by ragulka** [comment]
Sorry, I realised this had been fixed in #13454 and my `master` was out-of-date.
