### ISSUE TITLE
(WC 3.0.0 RC2) Cannot create variations

### ISSUE THREAD

**Issue by jkohlbach** [woocommerce/woocommerce#13848]
## EXPLANATION OF THE ISSUE

When creating a new variable product and manually setting the Regular Price, it throws a PHP error:

```
[31-Mar-2017 00:46:20 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getOffsetTimestamp() on null in [redacted]/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:177
Stack trace:
#0 [redacted]/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(163): WC_Product_Data_Store_CPT->update(Object(WC_Product_Variable))
#1 [redacted]/wp-content/plugins/woocommerce/includes/class-wc-product-variable.php(379): WC_Data_Store->update(Object(WC_Product_Variable))
#2 [redacted]/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(313): WC_Product_Variable->save()
#3 [redacted]/wp-includes/class-wp-hook.php(298): WC_Meta_Box_Product_Data::save(14, Object(WP_Post))
#4 [redacted]/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#5 [redacted]/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 [redacted] in [redacted]/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 177
```

## STEPS TO REPRODUCE THE ISSUE

To reproduce:
1. Create new product and set it to variable product
2. Set the attributes
3. Add variations and then fill the regular price one by one (manually)
4. Don't click "Save Change", instead, click publish

Ensure that you haven't saved draft at any stage. This should be a completely new product without any previous post saves.

PHP error should be thrown to the logs as above.

Tested on PHP 7 and PHP 5.5.

## SYSTEM STATUS REPORT

```
`
### WordPress Environment ###

WC Version: 3.0.0
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_wsgi/3.5 Python/2.7.10 PHP/7.0.0 mod_ssl/2.2.29 OpenSSL/0.9.8zh DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.22.0
PHP Version: 7.0.0
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/0.9.8zd

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.42 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider. cURL error 35: Unsupported SSL protocol version
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider. 200

### Database ###

WC Database Version: 3.0.0
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.0.0-rc.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)


### WC Pages ###

Shop base: #4 - /index.php/shop/
Cart: #5 - /index.php/cart/
Checkout: #6 - /index.php/checkout/
My account: #7 - /index.php/my-account/

### Theme ###

Name: Twenty Seventeen
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```

**Comment by DavidAnderson684** [comment]
I got hit in testing with a few issues with calling things of the sort `get_date_X()->getTimestamp()` too, not having spotted that get_date_X() methods can potentially return null. (I read the blog post about returning a DateTime and then read the docblocs too quickly for my own good).
