### ISSUE TITLE
new WC_Product_Variable( $postId ) results in error

### ISSUE THREAD

**Issue by Kinzi** [woocommerce/woocommerce#14373]
### EXPLANATION OF THE ISSUE

Since the update calling `new WC_Product_Variable( $postId )` results in:

`PHP Fatal error: Uncaught Exception: Invalid Product. in /wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:133`

Stack trace:

```
#0 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): WC_Product_Data_Store_CPT->read(Object(WC_Product_Variable))
#1 /wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(126): WC_Data_Store->read(Object(WC_Product_Variable))
#2 /wp-content/plugins/updateVariations/updateVariationPrices.php(112): WC_Product->__construct(4913)
```

The ID is correct. Can you please fix this or give me a hint on how to amend this?

Basically I used to do this:

```
$wc_product_variable = new WC_Product_Variable( $postID ); 
$wc_product_variable->set_stock( $stockAmount );
$wc_product_variable->set_stock_status( $stock );
$wc_product_variable->sync_stock_status( $postParent );
$wc_product_variable->sync( $postParent );
$wc_product_variable->variable_product_sync( $postParent );
```

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: https://www.packliste-reise.de
Site URL: https://www.packliste-reise.de
WC Version: 3.0.3
Log Directory Writable: ✔
WP Version: 4.7.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE

### Server Environment ###

Server Info: nginx/1.11.9
PHP Version: 7.0.16
PHP Post Max Size: 500 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.33
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.0.3
WC Database Prefix: wp_dtftwffwdx_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Affiliate Variations: von Sebastian Kinzlinger – 1.1.0
Akismet Anti-Spam: von Automattic – 3.3
Async JavaScript: von Clough I.T. Solutions – 1.17.02.06
Better Wordpress Minify: von Khang Minh – 1.3.3
EU Cookie Law: von Alex Moss
Marco Milesi
Peadig
Shane Jones – 2.10

Frontend Variations: von Sebastian Kinzlinger – 1.0
Fusion Builder: von ThemeFusion – 1.1.5
Fusion Core: von ThemeFusion – 3.1.5
Get Affilinet XMLS: von Sebastian Kinzlinger – 1.0
Instagram Slider Widget: von jetonr – 1.4.0
Log Error: von  –
Ultimate Nofollow: von bitacre – 1.4.5
Posts in Sidebar: von Aldo Latino – 3.8.5
Pretty Link: von Blair Williams – 2.0.8
Quick Adsense: von Quicksense – 1.9.2
ScrapeAZon: von James R. Hanback
Jr. – 2.2.7

Simple 301 Redirects: von Scott Nellé – 1.07
SSL Insecure Content Fixer: von WebAware – 2.2.3
Revive Old Post (Former Tweet Old Post): von revive.social – 7.4.8
WooCommerce: von Automattic – 3.0.3
Yoast SEO: von Team Yoast – 4.6
WP Crontrol: von John Blackbourn & contributors – 1.5
WP Smush: von WPMU DEV – 2.6.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop-Basis: #1591 - /ausruestung/
Warenkorb: ❌ Seite nicht festgelegt
Kasse: ❌ Seite nicht festgelegt
Mein Konto: ❌ Seite nicht festgelegt

### Theme ###

Name: Packliste
Version: – 0 ist verfügbar
Author URL: 
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.1.5
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.0.3
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
Avada/woocommerce/single-product/product-image.php Version 2.6.3 ist veraltet. Die Hauptversion ist 3.0.2
Avada/woocommerce/single-product/product-thumbnails.php Version 2.6.3 ist veraltet. Die Hauptversion ist 3.0.2
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌Erfahren Sie
wie Sie aktualisieren können

`
```
</details>

**Comment by mikejolley** [comment]
If you're seeing this exception its because the $post_id is not a product post type.

Use `wc_get_product` function. Note; if you provide an invalid ID, this will return false, not an object.
