### ISSUE TITLE
Add or edit page, post, coupon and product page is blank.

### ISSUE THREAD

**Issue by cdmcigars** [woocommerce/woocommerce#14884]
When you click on anything to edit or try and add a product, post, page or coupon the page is blank.  It throws up an html error 500 in Google Chrome.

### STEPS TO REPRODUCE THE ISSUE

I just updated to the New Woocommerce.  Immediately I was not able to get an add/edit page for any post, page, or product.  

I've tried deactivating all plugins and tried switching themes.  Cannot get to an edit or add page that is not blank.

The only time I can get to an add or edit page is by deactivating Woocommerce.

Now when I go back to an older version of woocommerce I can get the add/edit page to show but I can't get the Publish/Update button to work while on the add/edit page.

Also with the old version of Woocommerce when someone orders it never goes to the order complete screen.  It just scrolls back to the top of the page and sometimes says there is a syntax error. Multiple customers have ordered up to 3 times because there is no confirmation page after order.

### SYSTEM STATUS

<details>
```
`
### WordPress Environment ###

Home URL: http://www.cdmcigars.com
Site URL: http://www.cdmcigars.com
WC Version: 3.0.5
Log Directory Writable: ✔
WP Version: 4.7.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.35
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 2.6.14
WC Database Prefix: wp_ptvj_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (28) ###

a3 License Manager: by A3 Revolution – 1.0.2
Age Verifier for WordPress: by Nikolay Dyankov – 1.3.1
iThemes Security: by iThemes – 6.2.1
Code Snippets: by Shea Bunge – 2.8.4
WooCommerce - Gift Cards: by WP Ronin – 2.5.8
MailChimp for WordPress: by ibericode – 4.1.1
Ultimate WooCommerce Brands PRO: by MagniumThemes – 1.2
Nextend Facebook Connect: by Nextendweb – 2.0.2
Ninja Forms: by The WP Ninjas – 3.1.1
WooCommerce Product Filter: by Mihajlovic Nenad – 5.7.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 2.2.6
Smart Manager: by StoreApps – 3.9.21
Taxonomy Metadata: by mitcho (Michael Yoshitaka Erlewine)
sirzooro – 0.5

UPS WooCommerce Shipping: by WooForce – 2.7.5
Stamps.com WooCommerce Extension (USPS): by WooForce – 1.5.4
Woocommerce Variations Table - Grid: by Spyros Vlachopoulos – 1.3.3
WooCommerce Cost of Goods: by WooThemes / SkyVerge – 1.9.3 – 2.3.2 is available
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 1.6.5
WooCommerce Product Slider: by subhansanjaya – 1.2.2
WooCommerce Predictive Search PRO: by a3rev Software – 4.2.2
WooCommerce: by Automattic – 3.0.5
Authorize.net Gateway: by DenonStudio – 1.4.0
WooSidebars: by WooThemes – 1.4.3
Yoast SEO: by Team Yoast – 4.7
WP All Import Pro: by Soflyy – 4.4.6
Media Library Categories: by Jeffrey-WP – 1.5.5
YITH WooCommerce Ajax Search: by YITHEMES – 1.5.2
YITH WooCommerce Wishlist: by YITHEMES – 2.1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #11 - /shop/
Cart: #12 - /cart/
Checkout: #13 - /checkout/
My account: #14 - /my-account/

### Theme ###

Name: Flatsome
Version: 3.3.5
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you're modifying WooCommerce on a parent theme you didn't build personally
then we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/cart/proceed-to-checkout-button.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/orderby.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/product-searchform.php
flatsome/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.0.3
flatsome/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
flatsome/woocommerce/single-product/tabs/description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌Learn how to update
`
```
</details>

**Comment by claudiosanches** [comment]
> Add or edit page, post, coupon and product page is blank.

Blank page is because there is a PHP fatal error.
And WooCommerce 3.0 does not cause any Fatal error like that.
Have you enabled the WordPress debug mode?
What appears in the logs?

**Comment by claudiulodro** [comment]
500 error is super generic. We need the actual fatal error from the debug logs in order to troubleshoot the problem. My hunch is that one of your other plugins isn't compatible with WooCommerce 3.0 and is causing the errors, though.

**Comment by cdmcigars** [comment]
I just replied with the error log. Did you get it? 
Kyle


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by claudiosanches** [comment]
@cdmcigars no, try come back to GitHub and post it.

**Comment by cdmcigars** [comment]
Fatal error: Uncaught exception ‘Exception’ with message ‘Invalid order.’ in /home/cdmcigar/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:86 Stack trace: #0 /home/cdmcigar/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(143): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order)) #1 /home/cdmcigar/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(109): WC_Data_Store->read(Object(WC_Order)) #2 /home/cdmcigar/public_html/wp-content/plugins/ups-woocommerce-shipping/includes/class-wf-shipping-ups-tracking.php(38): WC_Abstract_Order->__construct(’76’) #3 /home/cdmcigar/public_html/wp-content/plugins/ups-woocommerce-shipping/includes/class-wf-shipping-ups-tracking.php(179): WF_Shipping_UPS_Tracking->wf_load_order(’76’) #4 [internal function]: WF_Shipping_UPS_Tracking->wf_add_admin_metabox(‘page’) #5 /home/cdmcigar/public_html/wp-includes/class-wp-hook.php(300): call_user_func_array(Array, Array) #6 /home/cdmcig in /home/cdmcigar/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 86


Thank you for your timely response. Any help would be greatly appreciated

**Comment by claudiosanches** [comment]
This is caused by the UPS plugin from WooForce.
Need to deactivate the plugin or maybe update, not sure if there is already some new release for it.

**Comment by cdmcigars** [comment]
When the UPS Plugin is deactivated it still happens. I'll run another debug.
