### ISSUE TITLE
faild csv import breaks built in csv importer.

### ISSUE THREAD

**Issue by maltonge** [woocommerce/woocommerce#16405]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of WooCommerce on Github
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.import of products using built in woocommerce import via csv file
2. drop connection during import
3. reconnect connection after which CSV import no longer works for any CSV file.
4. delete import placeholders from wp_post table and wp_postmeta
5.  Still can not import or update products.
6. requires fresh database install to get imports working again.
7.I also notice that custom product ids are ignored on import and woocommerce creates its own product id. not sure that's how its supposed to be.

## Expected/actual behavior

When I follow those steps, I see no products importing,  however if i use the csv on a fresh database it works ok until a failed product upload then it all goes bad again making it impossible to import or update.  meaning another fresh install.

I have been trying to update prices on my main site for well over a month now.  we do this first on a test database but this just is not working.  I am not new to CSV files and have been using CSV for product imports since oscommerce 2005.

before the database update from woocommerce i never once had any issues.  50k products would import in around 4 hours.

now its been over 1 month and I still can not update prices via csv.

Will it be best to go back to woocommerce old version before the database change?

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://hobbydabber.com
Site URL: http://hobbydabber.com
WC Version: 3.1.1
Log Directory Writable: ✔
WP Version: 4.8.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: nginx/1.13.2
PHP Version: 7.1.6-1~ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 8 GB
PHP Time Limit: 3000000
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.1.1
WC Database Prefix: wp_
woocommerce_sessions: ✔
woocommerce_api_keys: ✔
woocommerce_attribute_taxonomies: ✔
woocommerce_downloadable_product_permissions: ✔
woocommerce_order_items: ✔
woocommerce_order_itemmeta: ✔
woocommerce_tax_rates: ✔
woocommerce_tax_rate_locations: ✔
woocommerce_shipping_zones: ✔
woocommerce_shipping_zone_locations: ✔
woocommerce_shipping_zone_methods: ✔
woocommerce_payment_tokens: ✔
woocommerce_payment_tokenmeta: ✔
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /?page_id=4
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>
here is a link to one of our csv files for your convenience  htts://dev.hobbygiant.co.uk/html/wp-content/uploads/2017/08/woocommerce-product-exportfull.csv

**Comment by mikejolley** [comment]
CSV link is broken.

**Comment by maltonge** [comment]
https://dev.hobbygiant.co.uk/wp-content/uploads/2017/08/woocommerce-product-exportfull.csv sorry

**Comment by mikejolley** [comment]
Can you explain what happens when you import? Where does it get stuck? Are you importing fresh or using the 'update existing products' checkbox?

**Comment by maltonge** [comment]
import all seems to go ok but im on wifi and every once in a while we get a drop in connection.  if this happens then it deems the database scrap as can not import or update anymore with csv.  the problem is not so much with the csv file.  it is what happens after the product import has failed half way thorough.  the last version of woocommerce was not like this.  if it failed before it was just a case of doing the import again.  now it just spins if i try it again with no imports also tried to update products with a csv file that was previously used before the fail and that does not work neither.  the only way to get it working again is to fresh install database then csv works again.

**Comment by mikejolley** [comment]
The last version of WC didn't have a built in importer.

Have you looked at the server error logs for clues on why it hangs?

**Comment by maltonge** [comment]
sorry mike, yes i have checked the logs from sql nginx and php there is no errors at all shown for this  O I should have mentioned in previous version I used a plugin to import but that no longer works with the database update.  this has been driving me round the bend.  im thinking to just go back to the older version as I know that works without fault.  it was just a little slower.

**Comment by mikejolley** [comment]
@maltonge I imported your CSV for a few mins then closed the tab.

Then did a second import, it quickly got to the same point and continued to import.

I did not check the 'update existing products' box on either run.

**Comment by maltonge** [comment]
@mikejolley thanks for trying mike.  im not sure if you noticed when importing the second time it just creates duplicates.  if you check the database wp_post table you will see incomplete products from the first import which you closed with status as import and placeholders.  did that happen in your test?

**Comment by mikejolley** [comment]
yeah but when you do an import, IDs are ignored. It's correct to duplicate.

Are you sure the error logs had nothing? If it stopped import I'd expect something to be in the php error log.

**Comment by maltonge** [comment]
yes really there is zero errors for this in the logs.  When ever i get errors the first port of call for me is error logs but this instant shows nothing at all.

ok I have been watching the serve for the past 6 hours and i think the fails are to do with server side software, namely cpulimit this is set to 90% cpu limit and although this never ever gets to 90% i suspect this to be the cause of the fails.  I have disabled cpulimit on our server and i'm going to try the import again with fresh database.  fingers crossed.  even if this is the issue with the fails i am still stumped as to why I can not import more products after the fail, its like the database has been locked down if it fails.  I will know more after the test. I will keep you posted as to my findings.

**Comment by maltonge** [comment]
Hi mike some good news some bad.  the bad news is after cpulimit was disabled import stopped,  however now I have an error in the nginx logs.  ill put below for your convenience.  I hope this will give some clues as to the problems faced.

`2017/08/12 10:04:56 [error] 7471#7471: *3294 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot use object of type WP_Error as array in /var/www/hobbydabber.com/html/wp-content/plugins/woocommerce/includes/import/class-wc-product-csv-importer.php:308
Stack trace:
#0 /var/www/hobbydabber.com/html/wp-content/plugins/woocommerce/includes/import/class-wc-product-csv-importer.php(695): WC_Product_CSV_Importer->parse_categories_field('Electronics>Ind...')
#1 /var/www/hobbydabber.com/html/wp-content/plugins/woocommerce/includes/import/class-wc-product-csv-importer.php(89): WC_Product_CSV_Importer->set_parsed_data()
#2 /var/www/hobbydabber.com/html/wp-content/plugins/woocommerce/includes/import/class-wc-product-csv-importer.php(51): WC_Product_CSV_Importer->read_file()
#3 /var/www/hobbydabber.com/html/wp-content/plugins/woocommerce/includes/admin/importers/class-wc-product-csv-importer-controller.php(71): WC_Product_CSV_Importer->__construct('/var/www/hobbyd...', Array)
#4 /var/www/hobbydabber.com/html/wp-content/plugins/woocommerce/includes/admin/class-" while reading response header from upstream, client: 86.172.77.230, server: hobbydabber.com, request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "hobbydabber.com", referrer: "http://hobbydabber.com/wp-admin/edit.php?post_type=product&page=product_importer&step=import&file=%2Fvar%2Fwww%2Fhobbydabber.com%2Fhtml%2Fwp-content%2Fuploads%2F2017%2F08%2Fwoocommerce-product-export4-2.csv&delimiter=%2C&_wpnonce=abb4f0df53" `

**Comment by mikejolley** [comment]
Perfect, Ill patch next week.

**Comment by BigBlack** [comment]
I’m having a problem importing a csv file into woocommerce. The file contains about 400 variable products with 4000 variations inside.
The first part of products is imported regularly. The second part, approximately in the middle of the sheet, is imported without the tick on “use for variations”. The file is generated by a VBA script, so all lines are generated identically, from top to bottom.
Checking the wp_wc_order_product_lookup table, in the is_variation column, for correctly imported products there is a 1, for those imported badly there is 0.
Is there any solution to this problem? I have seen that several people have a similar problem, but it involves all lines. Instead in my case the bad import affects only half of them. Cells from lines 1482 to 2760 are skipped. Each time the import is done, they are always the same. But there is nothing different from the others. I also tried to change the Is_variation column from 0 to 1 from SQL for badly imported products, but after a while the values ​​return to 0. What to do?
