### ISSUE TITLE
API does not allow product_variations

### ISSUE THREAD

**Issue by limestreet** [woocommerce/woocommerce#16953]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I hook into 'woocommerce_api_save_product_variation' to save product variations.

It looks like this check do not allow product variations: https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L135
If post type is "product_variation" it throws error.

## Expected/actual behavior
I want to update product variations via API.

When I follow those steps, I see...
PHP Fatal error:  Uncaught Exception: Invalid product. in /public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:134
Stack trace:
#0 /public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(147): WC_Product_Data_Store_CPT->read(Object(WC_Product))
#1 /public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(126): WC_Data_Store->read(Object(WC_Product))
#2 /public_html/wp-content/plugins/custom-plugin/custom-plugin.php(59): WC_Product->__construct(1492)
#3 /public_html/wp-content/plugins/custom-plugin/custom-plugin.php(38): setPricesFromDear(1492, 'CC6BL-0.3')
#4 /public_html/wp-includes/class-wp-hook.php(298): action_woocommerce_api_save_product_variation(1492, 0, Object(WC_Product_Variation))
#5 /public_html/wp-includes/class-wp-hook.php(323) in /public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 134

I was expecting to see...
Updated product

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
WC version: 		3.1.2
WP version: 		4.8.2
```
</details>

**Comment by limestreet** [comment]
I found workaround to not use read when updating.
