### ISSUE TITLE
Order date_created prop not set

### ISSUE THREAD

**Issue by shivapoudel** [woocommerce/woocommerce#17489]
When a order is created from backend then there is no `date_created` prop but when a order is created from checkout form then there it is. When I get  `date_created` prop for backend order error is thrown while using this snippet:

`$order->get_date_created()->format( 'c' )`

Throws error:

```
Fatal error: Uncaught Error: Call to a member function format() on null in D:\htdocs\themegrill\wp-content\plugins\woocommerce\templates\emails\email-order-details.php:30 Stack trace: #0 D:\htdocs\themegrill\wp-content\plugins\woocommerce\includes\wc-core-functions.php(209): include() #1 D:\htdocs\themegrill\wp-content\plugins\woocommerce\includes\class-wc-emails.php(340): wc_get_template('emails/email-or...', Array) #2 D:\htdocs\themegrill\wp-includes\class-wp-hook.php(298): WC_Emails->order_details(Object(WC_Order), true, false, Object(WC_Email_New_Order)) #3 D:\htdocs\themegrill\wp-includes\class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 D:\htdocs\themegrill\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #5 D:\htdocs\themegrill\wp-content\plugins\woocommerce\templates\emails\admin-new-order.php(38): do_action('woocommerce_ema...', Object(WC_Order), true, false, Object(WC_Email_New_Order)) #6 D:\htdocs\themegrill\wp-content\plugins\woocommerce\includes\wc-core-functions.php(209): include('D:\\htdo in D:\htdocs\themegrill\wp-content\plugins\woocommerce\templates\emails\email-order-details.php on line 30
```

**Comment by mikejolley** [comment]
Just came across; happens if you skip processing and go right to completed.

**Comment by shivapoudel** [comment]
Can't we set `date_created` prop on creation rather than after checking order statuses.

**Comment by shivapoudel** [comment]
@mikejolley any update on this :)

**Comment by kloon** [comment]
Tested this on master and not getting the same results, if you look at the create method in the order datastore it runs the set_date_created method https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/abstract-wc-order-data-store-cpt.php#L53

**Comment by shivapoudel** [comment]
@kloon Thanks!

**Comment by dlatza** [comment]
meta directly
