### ISSUE TITLE
Ajax error when proceeding to pay from a payment link (#order_review form)

### ISSUE THREAD

**Issue by lvl99** [woocommerce/woocommerce#17833]
I'm using v3.2.4 on WordPress 4.9

I have a blocking AJAX error on the `#order_review` form when customer is given payment link (e.g. `https://example.com/checkout/order-pay/14889/?pay_for_order=true&key=wc_order_5a0f2aaf28e2e`) to then pay with PayPal. Once pressing "Proceed to payment" there is an "Internal Server Error" on non-debug environments, and with my developer environment it outputs:

```
[21-Nov-2017 08:37:45 UTC] PHP Notice:  Undefined index: key in /Users/mattscheurich/Sites/example.com/site/web/app/plugins/woocommerce/includes/class-wc-form-handler.php on line 305
[21-Nov-2017 08:37:45 UTC] PHP Stack trace:
[21-Nov-2017 08:37:45 UTC] PHP   1. {main}() /Users/mattscheurich/Sites/example.com/site/web/index.php:0
[21-Nov-2017 08:37:45 UTC] PHP   2. require() /Users/mattscheurich/Sites/example.com/site/web/index.php:17
[21-Nov-2017 08:37:45 UTC] PHP   3. wp() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-blog-header.php:16
[21-Nov-2017 08:37:45 UTC] PHP   4. WP->main() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/functions.php:960
[21-Nov-2017 08:37:45 UTC] PHP   5. do_action_ref_array() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp.php:726
[21-Nov-2017 08:37:45 UTC] PHP   6. WP_Hook->do_action() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/plugin.php:515
[21-Nov-2017 08:37:45 UTC] PHP   7. WP_Hook->apply_filters() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp-hook.php:310
[21-Nov-2017 08:37:45 UTC] PHP   8. WC_Form_Handler::pay_action() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp-hook.php:286
[21-Nov-2017 08:37:45 UTC] PHP Notice:  Undefined index: order-pay in /Users/mattscheurich/Sites/example.com/site/web/app/plugins/woocommerce/includes/class-wc-form-handler.php on line 306
[21-Nov-2017 08:37:45 UTC] PHP Stack trace:
[21-Nov-2017 08:37:45 UTC] PHP   1. {main}() /Users/mattscheurich/Sites/example.com/site/web/index.php:0
[21-Nov-2017 08:37:45 UTC] PHP   2. require() /Users/mattscheurich/Sites/example.com/site/web/index.php:17
[21-Nov-2017 08:37:45 UTC] PHP   3. wp() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-blog-header.php:16
[21-Nov-2017 08:37:45 UTC] PHP   4. WP->main() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/functions.php:960
[21-Nov-2017 08:37:45 UTC] PHP   5. do_action_ref_array() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp.php:726
[21-Nov-2017 08:37:45 UTC] PHP   6. WP_Hook->do_action() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/plugin.php:515
[21-Nov-2017 08:37:45 UTC] PHP   7. WP_Hook->apply_filters() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp-hook.php:310
[21-Nov-2017 08:37:45 UTC] PHP   8. WC_Form_Handler::pay_action() /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp-hook.php:286
[21-Nov-2017 08:37:45 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_id() on boolean in /Users/mattscheurich/Sites/example.com/site/web/app/plugins/woocommerce/includes/class-wc-form-handler.php:309
Stack trace:
#0 /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp-hook.php(286): WC_Form_Handler::pay_action(Object(WP))
#1 /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array)
#2 /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/plugin.php(515): WP_Hook->do_action(Array)
#3 /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/class-wp.php(726): do_action_ref_array('wp', Array)
#4 /Users/mattscheurich/Sites/example.com/site/web/cms/wp-includes/functions.php(960): WP->main('')
#5 /Users/mattscheurich/Sites/example.com/site/web/cms/wp-blog-header.php(16): wp()
#6 /Users/mattscheurich/Sites/example.com/site/web/index.php(17): require('/Users/mattsche...')
#7 {main}
  thrown in /Users/mattscheurich/Sites/example.com/site/web/app/plugins/woocommerce/includes/class-wc-form-handler.php on line 309
```

Looking at the code, it seems to be breaking in `class-wc-form-handler.php` on these lines:
https://github.com/woocommerce/woocommerce/blob/8801279c103c0bc77749d6e9163ede5ba0e8cf43/includes/class-wc-form-handler.php#L304-L307

It seems that the AJAX request itself doesn't have the `key` passed as a `$_GET` query variable, so the operation fails to fetch the order ID:
![image](https://user-images.githubusercontent.com/238480/33063754-b2726c36-cea3-11e7-83e6-8782df5331e3.png)

I see that the key is available in the `_wp_http_referer` so I attempted this minor rewrite to ensure that I could get it based on the order key:
```php
      // Pay for existing order
      parse_str( preg_replace( '/^[^\?]*\?/', '', $_POST['_wp_http_referer'] ), $extracted );
      $order_key  = isset( $_GET['key'] ) ? $_GET['key'] : $extracted['key'];
      $order_id   = ! empty( $wp->query_vars['order-pay'] ) ? absint( $wp->query_vars['order-pay'] ) : wc_get_order_id_by_order_key( $order_key );
      $order      = wc_get_order( $order_id );
```

I'm not sure if that is a good rewrite, as there might be other use cases for this particular action. It seems that I now don't get the errors about the undefined `key` and `order-pay` variables (good!), but the action still doesn't go through (bad!) and I get an error message in the frontend:
```json
{"result":"failure","messages":"<div class=\"site-message-error\">\n  <ul class=\"site-message-inner\">\n\t\t\t<li>We were unable to process your order, please try again.<\/li>\n\t  <\/ul>\n<\/div>\n","refresh":true,"reload":false}
```

Any ideas?

**Comment by lvl99** [comment]
Ah, I needed to `absint` the order ID...

```php
      // Pay for existing order
      parse_str( preg_replace( '/^[^\?]*\?/', '', $_POST['_wp_http_referer'] ), $extracted );
      $order_key  = isset( $_GET['key'] ) ? $_GET['key'] : $extracted['key'];
      $order_id   = ! empty( $wp->query_vars['order-pay'] ) ? $wp->query_vars['order-pay'] : wc_get_order_id_by_order_key( $order_key );
      $order      = wc_get_order( absint( $order_id ) );
```

But now I get this error in the console:
```
Failed to load https://www.paypal.com/cgi-bin/webscr?...: Response for preflight is invalid (redirect)
```

**Comment by lvl99** [comment]
I'm not sure if I've gone too far down the rabbit hole (so unsure if I might have some bad side effects), but it seems that adding in an AJAX JSON response here has fixed my issue of the errored "response for preflight is invalid (redirect)" action:

https://github.com/woocommerce/woocommerce/blob/8801279c103c0bc77749d6e9163ede5ba0e8cf43/includes/class-wc-form-handler.php#L356-L360

Changed to:
```php
  // Redirect to success/confirmation/payment page
  if ( defined( 'DOING_AJAX' ) ) {
    wp_send_json( $result );
    exit;
  } else {
    if ( 'success' === $result['result'] ) {
      wp_redirect( $result['redirect'] );
      exit;
    }
  }
```

**Comment by mikejolley** [comment]
@lvl99 You have a non-core issue here :) I know this because the Pay For Order page is not powered by AJAX. It's a regular form; no fields, regular post. Thats why it's missing data and the ajax endpoint is failing.

If you think it's the PayPal gateway using ajax here, you may want to report to the developer. I don't know what extension you're using.

If in doubt, test the pay page with BACS or Cheque gateway, since those are the simplest gateways for testing.

Thanks!

**Comment by lvl99** [comment]
@mikejolley I'm using the PayPal Standard gateway that ships with WooCommerce. Is that an external plugin?

**Comment by mikejolley** [comment]
The pay page itself does not use AJAX. If yours is, something is changing it.

**Comment by lvl99** [comment]
I've found that I used the CSS classes "checkout woocommerce-checkout" to inherit the presentational styles, but didn't realise that extra AJAX functionality was included with those classes.

Would it make more sense to signify JS behaviours on elements with custom data attributes (e.g. "data-use-checkout"), rather than using presentational class names?

**Comment by mikejolley** [comment]
It would, however it would also break backwards compatibility so our hands are tied.

**Comment by lvl99** [comment]
Fair enough 🙌. That might also explain the variety of different types of CSS class names used throughout the templates too.
