### ISSUE TITLE
Fatal error when empty strings is passed as columns parameter in shortcode

### ISSUE THREAD

**Issue by ksere** [woocommerce/woocommerce#18615]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)

- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Clean install WP 4.9.2 + WC 3.3-rc1 (also tested on master/be7ad7f2346e3627ca5b1e759184002c9355b811 )
2. Import WC demo data
3. Add this to a page:

`[product_category category="accessories" per_page="4" columns=""]`

## Expected/actual behavior

Getting a Fatal error:
```
[26-Jan-2018 14:46:45 UTC] PHP Fatal error:  Uncaught DivisionByZeroError: Modulo by zero in /var/www/html/devbox/wp7test2/wp-content/plugins/woocommerce/includes/wc-template-functions.php:387
Stack trace:
#0 /var/www/html/devbox/wp7test2/wp-content/plugins/woocommerce/includes/wc-template-functions.php(435): wc_get_loop_class()
#1 /var/www/html/devbox/wp7test2/wp-includes/class-wp-hook.php(286): wc_product_post_class(Array, Array, 48)
#2 /var/www/html/devbox/wp7test2/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#3 /var/www/html/devbox/wp7test2/wp-includes/post-template.php(543): apply_filters('post_class', Array, Array, 48)
#4 /var/www/html/devbox/wp7test2/wp-includes/post-template.php(423): get_post_class(Array, NULL)
#5 /var/www/html/devbox/wp7test2/wp-content/plugins/woocommerce/templates/content-product.php(30): post_class()
#6 /var/www/html/devbox/wp7test2/wp-includes/template.php(690): require('/var/www/html/d...')
#7 /var/www/html/devbox/wp7test2/wp-content/plugins/woocommerce/includes/wc-core-functions.php(180): load_templa in /var/www/html/devbox/wp7test2/wp-content/plugins/woocommerce/includes/wc-template-functions.php on line 387
```
## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
### WordPress Environment ###

Home URL: http://devbox/wp7test2
Site URL: http://devbox/wp7test2
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.18-0ubuntu0.16.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 2.94MB
Database Data Size: 2.07MB
Database Index Size: 0.87MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.47MB + Index: 0.02MB
wp_postmeta: Data: 0.08MB + Index: 0.06MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 2
post: 2
product: 18
revision: 5

### Security ###

Secure connection (HTTPS): ❌Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

WooCommerce Beta Tester: by Mike Jolley – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.3.0-rc.1
WordPress Importer: by wordpressdotorg – 0.6.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/18617
