### ISSUE TITLE
Fatal error when removing item from popup cart.

### ISSUE THREAD

**Issue by GAPP99** [woocommerce/woocommerce#18768]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add item to cart.
2. Remove item from cart from the Popup Cart
3. Fatal error

## Expected/actual behavior

When I follow those steps, I see this fatal error message:
`Fatal error: Uncaught Error: Call to a member function is_in_stock() on boolean in /srv/users/XXX/public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php:517 Stack trace: #0 /srv/users/XXX/public/wp-includes/class-wp-hook.php(286): WC_Form_Handler::update_cart_action('') #1 /srv/users/XXX/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #2 /srv/users/XXX/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /srv/users/XXX/public/wp-settings.php(471): do_action('wp_loaded') #4 /srv/users/XXX/public/wp-config.php(37): require_once('/srv/users/caru...') #5 /srv/users/XXX/public/wp-load.php(37): require_once('/srv/users/XXX...') #6 /srv/users/XXX/public/wp-blog-header.php(13): require_once('/srv/users/XXX...') #7 /srv/users/XXX/public/in in /srv/users/XXX/public/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php on line 517`

I was expecting to see the item being removed from cart.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: XXX
Site URL: XXX
WC Version: 3.3.0
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US

### Server Environment ###

Server Info: Apache/2.4.28 (Unix) OpenSSL/1.0.2g
PHP Version: 7.2.1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.0
WC Database Prefix: wp_2eba27eec0_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from http://dev.maxmind.com/geoip/legacy/geolite/ to the path: . Scroll down to "Downloads" and download the "Binary / gzip" file next to "GeoLite Country". Please remember to uncompress GeoIP.dat.gz and upload the GeoIP.dat file only.
Total Database Size: 5.52MB
Database Data Size: 4.52MB
Database Index Size: 1.00MB
wp_2eba27eec0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_2eba27eec0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_2eba27eec0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_2eba27eec0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_2eba27eec0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_comments: Data: 0.02MB + Index: 0.08MB
wp_2eba27eec0_gb_ocu_customers: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_gb_ocu_funnels: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_links: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_options: Data: 2.02MB + Index: 0.05MB
wp_2eba27eec0_postmeta: Data: 0.48MB + Index: 0.11MB
wp_2eba27eec0_posts: Data: 1.48MB + Index: 0.06MB
wp_2eba27eec0_termmeta: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_terms: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_2eba27eec0_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_usermeta: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_users: Data: 0.02MB + Index: 0.05MB
wp_2eba27eec0_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_2eba27eec0_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

ae_global_templates: 1
attachment: 51
custom_css: 1
customize_changeset: 68
elementor_library: 2
nav_menu_item: 11
page: 16
post: 4
product: 1
product_variation: 2
revision: 181

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Elementor: by Elementor.com – 1.9.3
WooCommerce: by Automattic – 3.3.1-rc.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: OceanWP Child
Version: 1.0
Author URL: https://oceanwp.org/
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 1.4.15
Parent Theme Author URL: https://oceanwp.org/about-me/
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/checkout/form-coupon.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

`
```
</details>

**Comment by WPprodigy** [comment]
> Remove item from cart from the Popup Cart

There is very likely something wrong with the way to popup cart plugin is removing items.


WooCommerce probably should make sure the product exists here though: 
https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L512-L517

**Comment by kloon** [comment]
As Caleb mentioned, this is probably an error in the popup cart plugin, however, I have added a check in #18776 to ensure a fatal error does not happen when an invalid product ID is passed to the remove from cart function.
