### ISSUE TITLE
API not working as documented (attempts to update an order's meta_data fail.)

### ISSUE THREAD

**Issue by willfaulds** [woocommerce/woocommerce#18810]
Any attempts to update an order's **meta_data** fail.

This goes against the API documentation http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional

## Steps to reproduce the issue

**Outline of API call (PHP using wc-api-php 2.0.0):**
```
$woocommerce = new Client(
    'https://www....',
    '...',
    '...',
    [
        'wp_api' => true,
        'version' => 'wc/v2'
    ]
);

...create/load an wooOrder with $orderId

$data = [
  'id' => $orderId,
  'meta_data' => [ '_custom_field' => '24.54' ]
];

$woocommerce->put('orders/'.$orderId, $data);
```

## Expected/actual behavior

When I follow those steps, I see...
**ERROR log**

```
[31-Jan-2018 09:49:53 Europe/London] PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid parameter(s): meta_data [rest_invalid_param] in /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:348
Stack trace:

#0 /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(378): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass))

#1 /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(414): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()

#2 /home/vendor/automattic/woocommerce/src/WooCommerce/Client.php(69): Automattic\WooCommerce\HttpClient\HttpClient->request('orders/7712', 'PUT', Array)

#3 /home/woocommerce.php(95): Automattic\WooCommerce\Client->put('orders/7712', Array)

#4 /home/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 348

```

I was expecting to see...
The order to have new/updated meta data

## WordPress Environment

<details>
```
### WordPress Environment ###

WC Version: 3.2.6
Log Directory Writable: ✔
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_GB

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.12
PHP Post Max Size: 50 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 374.42MB
Database Data Size: 365.05MB
Database Index Size: 9.37MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.12MB
wp_woocommerce_order_itemmeta: Data: 1.57MB + Index: 1.11MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
ao_email_logs: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.26MB + Index: 0.13MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_litespeed_optimizer: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.51MB + Index: 0.07MB
wp_postmeta: Data: 13.16MB + Index: 6.10MB
wp_posts: Data: 342.56MB + Index: 0.73MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.42MB + Index: 0.85MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.27MB + Index: 0.17MB
wp_users: Data: 0.01MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.01MB + Index: 0.02MB
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB
wp_wpml_mails: Data: 5.08MB + Index: 0.01MB

### Post Type Counts ###

attachment: 1
page: 8
post: 5
product: 27
product_variation: 14
revision: 8
shop_coupon: 2
shop_order: 521
shop_webhook: 1
wp-rest-api-log: 157

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (19) ###

User Switching in Admin Bar: by Mark Wilkinson – 1.1.1
AppleOrphanageInvoices: by Will Faulds – 0.1
Autoptimize: by Frank Goossens (futtta) – 2.3.2
BackWPup: by Inpsyde GmbH – 3.4.4
Disable Emails: by WebAware – 1.3.0
Force Sell for WooCommerce: by BeRocket – 1.0.9 – Not tested with the active version of WooCommerce
LiteSpeed Cache: by LiteSpeed Technologies – 1.8.3
User Switching: by John Blackbourn – 1.3.0
Username Changer: by Daniel J Griffiths – 3.1.3
Advanced Order Export For WooCommerce: by AlgolPlus – 1.5.2
WooCommerce Product Bundles: by SomewhereWarm – 5.7.3
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.2 – Not tested with the active version of WooCommerce
WooCommerce Wholesale Order Form: by Rymera Web Co – 1.8.1
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.16.1
WooCommerce Wholesale Prices: by Rymera Web Co – 1.6.0
WooCommerce Xero Integration: by WooCommerce – 1.7.10
WooCommerce: by Automattic – 3.2.6
WP Mail Logging: by Christian Zöller – 1.8.3
REST API Log: by Pete Nelson – 1.6.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
wcpb (wcpb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #53 - /shop/
Basket: #54 - /basket/
Checkout: #55 - /checkout/
My account: #56 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.2.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mikejolley** [comment]
You're going against the documentation.

`'meta_data' => [ '_custom_field' => '24.54' ]`

Look at:

http://woocommerce.github.io/woocommerce-rest-api-docs/#order-properties
http://woocommerce.github.io/woocommerce-rest-api-docs/#order-meta-data-properties

```
id | integer | Meta ID.READ-ONLY
-- | -- | --
key | string | Meta key.
value | string | Meta value.
```

You are missing key and value.

**Comment by willfaulds** [comment]
Hi Mike,


I cannot test live live for a few weeks but did also try the following
meta_data' => [
‘key’ => ‘custom',
‘value’ => ‘data’
]

With the same results against orders only (not products).

All the best,

---

Will Faulds
(07624) 439445
Design-Branch
www.design-branch.com


Design-Branch is a division of Apple Orphanage Company Limited.
Registered in the Isle of Man No. 124074C.
Directors: William H Faulds & Charlotte A Traynor.
Registered office: The Lynague, German, Isle of Man, IM5 2AQ.

**Comment by mikejolley** [comment]
![insomnia create product 2018-02-05 15-36-53](https://user-images.githubusercontent.com/90977/35813010-6aad2382-0a8a-11e8-987e-3157bc232550.png)

**Comment by willfaulds** [comment]
Will confirm ASAP when I have development setup again. 😳

**Comment by willfaulds** [comment]
Hi Mike,

I'm back from my time away and looking into this now... I initially could not get the call using wc-api-php to work. However, after some persistence I have found the correct syntax for the data array:

```
$data = [
  'id' => $orderId,
  'meta_data' => array([
    'key' => 'custom',
    'value' => 'data'
  ])
];
```

**NB the double array wrap is required**
i.e. array() && []

Hope this helps others.

**Comment by tvplinux** [comment]
You help me a lot! @willfaulds 
Many thank to come back and auto reply you.
