### ISSUE TITLE
Can't Edit Pages with WooCommerce Plugin Enabled

### ISSUE THREAD

**Issue by vicatcu** [woocommerce/woocommerce#20536]
**Describe the bug**
I get a 500 error on my server when clicking the Edit link for any page in the table under the Pages side menu. The stack trace reads as follows:

```
[Thu Jun 14 13:18:01.025730 2018] [:error] [pid 5121] [client 24.59.249.190:60090] PHP Fatal error:  Uncaught Exception: Invalid order. in /var/www/html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:100
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): Abstract_WC_Order_Data_Store_CPT->read(Object(WC_Order))
#1 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(111): WC_Data_Store->read(Object(WC_Order))
#2 /var/www/html/wp-content/plugins/dhl-woocommerce-shipping/includes/class-wf-dhl-woocommerce-shipping-admin.php(146): WC_Abstract_Order->__construct('5')
#3 /var/www/html/wp-content/plugins/dhl-woocommerce-shipping/includes/class-wf-dhl-woocommerce-shipping-admin.php(269): wf_dhl_woocommerce_shipping_admin->wf_load_order('5')
#4 /var/www/html/wp-includes/class-wp-hook.php(288): wf_dhl_woocommerce_shipping_admin->wf_add_dhl_metabox('page')
#5 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wp-includes/plugin.php(453): WP_Hook-> in /var/www/html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 100, referer: https://my.website.com/wp-admin/edit.php?post_type=page
```
**To Reproduce**
1. Go to admin console
2. Click on Pages in the side menu
3. Click on any page listed in the table.
4. Get a 500 http error code
5. Fish the stack trace out of the Apache logs.

**Screenshots**
N/A

**Expected behavior**
You should reach the edit page

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. **No, but simply deactivating woocommerce makes this problem go away **
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). ** I'm using the WooStore theme**
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
```
`
### WordPress Environment ###

Home URL: https://my.website.com
Site URL: https://my.website.com
WC Version: 3.4.2
Log Directory Writable: ✔
WP Version: 4.9.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.30-0ubuntu0.16.04.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.22-0ubuntu0.16.04.1
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
Total Database Size: 235.18MB
Database Data Size: 161.69MB
Database Index Size: 73.49MB
wp_woocommerce_sessions: Data: 37.58MB + Index: 0.45MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.25MB + Index: 0.09MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.95MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.23MB + Index: 0.27MB
wp_comments: Data: 1.52MB + Index: 0.73MB
wp_draftsforfriends: Data: 0.02MB + Index: 0.05MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 0.09MB + Index: 0.20MB
wp_followup_customer_carts: Data: 0.13MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.09MB + Index: 0.05MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.14MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.13MB + Index: 0.17MB
wp_followup_order_items: Data: 0.13MB + Index: 0.20MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wp_itsec_log: Data: 39.08MB + Index: 11.72MB
wp_itsec_logs: Data: 11.02MB + Index: 0.84MB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.23MB + Index: 0.06MB
wp_postmeta: Data: 5.52MB + Index: 8.03MB
wp_posts: Data: 6.52MB + Index: 0.67MB
wp_ps_exclude: Data: 0.02MB + Index: 0.02MB
wp_ps_keyword: Data: 0.02MB + Index: 0.00MB
wp_ps_postmeta: Data: 0.02MB + Index: 0.03MB
wp_ps_posts: Data: 0.05MB + Index: 0.02MB
wp_ps_product_categories: Data: 0.02MB + Index: 0.03MB
wp_ps_product_sku: Data: 0.02MB + Index: 0.02MB
wp_ps_product_tags: Data: 0.02MB + Index: 0.03MB
wp_ps_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_redirection_404: Data: 51.58MB + Index: 43.13MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.06MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 1.52MB + Index: 3.03MB
wp_users: Data: 0.08MB + Index: 0.05MB
wp_vtcrt_purchase_log: Data: 0.02MB + Index: 0.02MB
wp_vtcrt_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wp_vtcrt_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wp_vtprd_lifetime_limits_purchaser: Data: 0.02MB + Index: 0.02MB
wp_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.02MB + Index: 0.02MB
wp_vtprd_lifetime_limits_purchaser_rule: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log: Data: 0.09MB + Index: 0.02MB
wp_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

amn_mi-lite: 2
amn_smtp: 2
attachment: 1041
custom_css: 1
customize_changeset: 4
nav_menu_item: 47
page: 62
post: 234
product: 83
product_variation: 3
question: 11
redirect_rule: 12
revision: 523
scheduled-action: 72
shop_coupon: 30
shop_order: 1384
shop_order_refund: 3
slide: 8
tablepress_table: 1
vtprd-rule: 3
wooframework: 131

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

a3rev Dashboard: by a3rev Software – 2.6.2
BackupBuddy: by iThemes – 7.2.2.0
iThemes Security: by iThemes – 7.0.1
Cache Images: by Matt Mullenweg – 3.1
DHL WooCommerce Shipping with Print Label: by WooForce – 1.8.9 – Not tested with the active version of WooCommerce
Disable Comments: by Samir Shah – 1.7.1
Duplicate Post: by Enrico Battocchi – 3.2.2
Enable Media Replace: by ShortPixel – 3.2.5
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.0.6
Google XML Sitemaps: by Arne Brachhold – 4.0.9
VarkTech Pricing Deals for WooCommerce: by Vark – 1.1.8.3
VarkTech Pricing Deals PRO for WooCommerce: by VarkTech – 1.1.8.3
Redirection: by John Godley – 3.2
Safe Redirect Manager: by 10up – 1.9
SyntaxHighlighter Evolved: by Alex Mills (Viper007Bond) – 3.2.1
TablePress: by Tobias Bäthge – 1.9
Wicked Device Inventory System Hooks: by Victor Aprea – 1.0.0
Stamps.com WooCommerce Extension (USPS) (Basic): by XAdapter – 2.0.7
WooCommerce Bulk Pricing: by WP Lab – 1.9.4 – Not tested with the active version of WooCommerce
WooCommerce Composite Products: by SomewhereWarm – 3.13.10
Follow-Up Emails: by WooCommerce – 4.7.4
WooCommerce Stripe Gateway: by WooCommerce – 4.1.7
WooCommerce MailChimp: by Saint Systems – 2.1.12 – Not tested with the active version of WooCommerce
WooCommerce Order Status Control: by SkyVerge – 1.9.1
WooCommerce Predictive Search PRO: by a3rev Software – 4.6.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.18
WooCommerce: by Automattic – 3.4.2
WordPress FAQ Manager: by Andrew Norcross – 1.331
WP Add Mime Types: by Kimiya Kitani – 2.2.1
WP-DraftsForFriends: by Lester 'GaMerZ' Chan – 1.0.2
WP Mail SMTP: by WPForms – 1.2.5
Zendesk Chat Widget: by Zendesk – 1.4.12

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #503 - /shop/
Cart: #604 - /cart/
Checkout: #505 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: WooStore
Version: 1.8.3 – 1.8.4 is available
Author URL: http://www.woothemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Composite Products ###

Database Version: 3.13.10
Template Overrides: –
`
```
</details>

**Comment by mikejolley** [comment]
> **No, but simply deactivating woocommerce makes this problem go away **

Thats because extensions which rely on WooCommerce will also deactivate...

**Comment by mikejolley** [comment]
> DHL WooCommerce Shipping with Print Label: by WooForce

It's this one.

This appears to be premium so I cannot check, but my thinking is:

- It tries to load an order based on currently edited PAGE
- Since it's a page and not an order, WooCommerce throws an exception
- The DHL plugin does not correctly handle the exception so you see error 500

Disable the DHL plugin and report this to the developer.

Thanks

**Comment by vicatcu** [comment]
thanks @mikejolley I appreciate the diagnostic help
