### ISSUE TITLE
Error on triggering 'woocommerce_variable_add_to_cart' hook

### ISSUE THREAD

**Issue by station72** [woocommerce/woocommerce#21307]
After do_action('woocommerce_variable_add_to_cart') i see    

> Fatal error: Uncaught Error: Call to undefined method WC_Product_Simple::get_available_variations() in E:\USR\www\eshop\wp-content\plugins\woocommerce\includes\wc-template-functions.php:1544 Stack trace: #0 E:\USR\www\eshop\wp-includes\class-wp-hook.php(286): woocommerce_variable_add_to_cart('') #1 E:\USR\www\eshop\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 E:\USR\www\eshop\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #3 E:\USR\www\eshop\wp-content\themes\eshop\woocommerce\content-single-product.php(66): do_action('woocommerce_var...') #4 E:\USR\www\eshop\wp-includes\template.php(690): require('E:\\USR\\www\\esho...') #5 E:\USR\www\eshop\wp-content\plugins\woocommerce\includes\wc-core-functions.php(179): load_template('E:\\USR\\www\\esho...', false) #6 E:\USR\www\eshop\wp-content\themes\eshop\woocommerce\single-product.php(35): wc_get_template_part('content', 'single-product') #7 E:\USR\www\eshop\wp-includes\template-loader.php(74): include('E:\\USR\\www\\esho...') #8 E:\USR\www\esh in E:\USR\www\eshop\wp-content\plugins\woocommerce\includes\wc-template-functions.php on line 1544

I have added some variations to the product. Reinstall WC plugin did not help.
WP ver. 4.9.8
WC ver. 3.4.5

**Comment by station72** [comment]
Sorry, it was my mistake. I did not set needed product type.
