### ISSUE TITLE
Cannot build API documentation

### ISSUE THREAD

**Issue by rkaiser0324** [woocommerce/woocommerce#22236]
**Describe the bug**
`grunt shell` fails.  Enabling `--debug` on `apigen` gets you the stack trace.

**To Reproduce**
```
[root@localhost localproject]# node_modules/.bin/grunt shell
Running "shell:apidocs" (shell) task
ERROR: application encountered an error and can not continue. Unable to log error.
For more information turn on the debug mode using the --debug option.
Warning: Command failed: vendor/bin/apigen generate -q &&cd apigen &&php hook-docs.php
ERROR: application encountered an error and can not continue. Unable to log error.
 Use --force to continue.

Aborted due to warnings.
[root@localhost localproject]# vendor/bin/apigen generate -q
ERROR: application encountered an error and can not continue. Unable to log error.
For more information turn on the debug mode using the --debug option.
[root@localhost localproject]# vendor/bin/apigen generate --debug

Fatal error: Trait 'Nette\SmartObject' not found in /home/vagrant/localproject/vendor/tracy/tracy/src/Bridges/Nette/MailSender.php on line 19

Call Stack:
    0.0001     359952   1. {main}() /home/vagrant/localproject/vendor/apigen/apigen/bin/apigen:0
    0.0091    1729464   2. Nette\Configurator->createContainer() /home/vagrant/localproject/vendor/apigen/apigen/bin/apigen:31
    0.0093    1755128   3. Nette\DI\ContainerLoader->load() /home/vagrant/localproject/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:217
    0.0093    1755176   4. Nette\DI\ContainerLoader->loadFile() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php:44
    0.0095    1755824   5. Nette\DI\ContainerLoader->generate() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php:79
    0.0111    2088472   6. call_user_func_array:{/home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php:114}() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php:114
    0.0111    2088488   7. Nette\Configurator->generateContainer() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php:114
    0.0148    2511104   8. Nette\DI\Compiler->compile() /home/vagrant/localproject/vendor/nette/bootstrap/src/Bootstrap/Configurator.php:264
    0.0404    4832216   9. Nette\DI\Compiler->generateCode() /home/vagrant/localproject/vendor/nette/di/src/DI/Compiler.php:152
    0.1474    8180184  10. Tracy\Bridges\Nette\TracyExtension->afterCompile() /home/vagrant/localproject/vendor/nette/di/src/DI/Compiler.php:236
    0.1476    8182912  11. Nette\DI\ContainerBuilder->formatPhp() /home/vagrant/localproject/vendor/tracy/tracy/src/Bridges/Nette/TracyExtension.php:102
    0.1476    8183632  12. array_walk_recursive() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php:802
    0.1477    8183824  13. Nette\DI\ContainerBuilder->Nette\DI\{closure}() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php:802
    0.1477    8183824  14. Nette\DI\ContainerBuilder->formatStatement() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php:770
    0.1477    8183936  15. ReflectionClass->__construct() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php:710
    0.1477    8183992  16. spl_autoload_call() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php:710
    0.1477    8184048  17. Composer\Autoload\ClassLoader->loadClass() /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php:710
    0.1477    8184048  18. Composer\Autoload\includeFile() /home/vagrant/localproject/vendor/composer/ClassLoader.php:322
    0.1479    8192856  19. include('/home/vagrant/localproject/vendor/tracy/tracy/src/Bridges/Nette/MailSender.php') /home/vagrant/localproject/vendor/composer/ClassLoader.php:444

ErrorException: Trait 'Nette\SmartObject' not found in /home/vagrant/localproject/vendor/tracy/tracy/src/Bridges/Nette/MailSender.php:19
Stack trace:
#0 /home/vagrant/localproject/vendor/composer/ClassLoader.php(444): *unknown*()
#1 /home/vagrant/localproject/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php(710): Composer\Autoload\ClassLoader->loadClass()
#3 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php(710): spl_autoload_call()
#4 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php(710): ReflectionClass->__construct()
#5 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php(770): Nette\DI\ContainerBuilder->formatStatement()
#6 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php(802): Nette\DI\ContainerBuilder->Nette\DI\{closure}()
#7 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerBuilder.php(802): array_walk_recursive()
#8 /home/vagrant/localproject/vendor/tracy/tracy/src/Bridges/Nette/TracyExtension.php(102): Nette\DI\ContainerBuilder->formatPhp()
#9 /home/vagrant/localproject/vendor/nette/di/src/DI/Compiler.php(236): Tracy\Bridges\Nette\TracyExtension->afterCompile()
#10 /home/vagrant/localproject/vendor/nette/di/src/DI/Compiler.php(152): Nette\DI\Compiler->generateCode()
#11 /home/vagrant/localproject/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(264): Nette\DI\Compiler->compile()
#12 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php(114): Nette\Configurator->generateContainer()
#13 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php(114): call_user_func_array:{/home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php:114}()
#14 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate()
#15 /home/vagrant/localproject/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile()
#16 /home/vagrant/localproject/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(217): Nette\DI\ContainerLoader->load()
#17 /home/vagrant/localproject/vendor/apigen/apigen/bin/apigen(31): Nette\Configurator->createContainer()
#18 {main}
Unable to log error: Logging directory is not specified.
```

**Expected behavior**
It should build.  I didn't see any instructions for building the documentation so assumed the following would work:
```
composer update
npm install
grunt shell
```
I did note that `apidocs` will not run on Windows due to the path. What are the other requirements?

**Isolating the problem (mark completed items with an [x]):**
n/a

**WordPress Environment**
<details>
PHP 7.1
CentOS 7.1
</details>

**Comment by claudiosanches** [comment]
This is used internally only, and if you want just the docs, need to use `grunt docs` instead, also APIGEN is not compatible with PHP 7.1.
