### ISSUE TITLE
TypeError Argument 4 passed to ActionScheduler_ActionFactory::get_stored_action() must be an instance of ActionScheduler_Schedule

### ISSUE THREAD

**Issue by mikebronner** [woocommerce/woocommerce#22767]
**Describe the bug**
Getting error reports when running WP_CRON

**To Reproduce**
1. Connect error log service, like Bugsnag.
2. Open command line on server.
3. Run "php -q /home/codepier/imaginethatcomics.com/current/public/wordpress/wp-cron.php"
4. See error in bugsnag dashboard.

**Stacktrace**
```
TypeError Argument 4 passed to ActionScheduler_ActionFactory::get_stored_action() must be an instance of ActionScheduler_Schedule or null, string given, called in /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 111 
    /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php:17 ActionScheduler_ActionFactory::get_stored_action
    /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:111 ActionScheduler_wpPostStore::make_action_from_post
    /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:81 ActionScheduler_wpPostStore::fetch_action
    /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php:57 ActionScheduler_Abstract_QueueRunner::process_action
    /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php:80 ActionScheduler_QueueRunner::do_batch
    /home/myuser/myserver.com/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php:61 ActionScheduler_QueueRunner::run
    /home/myuser/myserver.com/public/wordpress/wp-includes/class-wp-hook.php:286 WP_Hook::apply_filters
    /home/myuser/myserver.com/public/wordpress/wp-includes/class-wp-hook.php:310 WP_Hook::do_action
    /home/myuser/myserver.com/public/wordpress/wp-includes/plugin.php:515 do_action_ref_array
    /home/myuser/myserver.com/public/wordpress/wp-cron.php:126 [main]
```

**Expected behavior**
Would not expect an error to be thrown. Looks like there is still some code somewhere that is passing. string, instead of a `ActionScheduler_Schedule` instance.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: https://imaginethatcomics.com
Site URL: https://imaginethatcomics.com/wordpress
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.15-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 250 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.25-0ubuntu0.18.04.2
Max Upload Size: 250 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: itc_
Total Database Size: 1331.34MB
Database Data Size: 1081.88MB
Database Index Size: 249.46MB
itc_woocommerce_sessions: Data: 196.22MB + Index: 5.23MB
itc_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
itc_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
itc_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
itc_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB
itc_woocommerce_order_itemmeta: Data: 11.52MB + Index: 14.03MB
itc_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
itc_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
itc_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
itc_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
itc_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
itc_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
itc_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
itc_woocommerce_log: Data: 0.02MB + Index: 0.02MB
itc_amazon_accounts: Data: 0.02MB + Index: 0.00MB
itc_amazon_btg: Data: 0.20MB + Index: 0.20MB
itc_amazon_categories: Data: 0.02MB + Index: 0.03MB
itc_amazon_feeds: Data: 59.55MB + Index: 0.00MB
itc_amazon_feed_templates: Data: 0.02MB + Index: 0.00MB
itc_amazon_feed_tpl_data: Data: 0.13MB + Index: 0.08MB
itc_amazon_feed_tpl_values: Data: 0.17MB + Index: 0.05MB
itc_amazon_jobs: Data: 0.08MB + Index: 0.00MB
itc_amazon_listings: Data: 3.52MB + Index: 2.27MB
itc_amazon_log: Data: 0.02MB + Index: 0.05MB
itc_amazon_markets: Data: 0.02MB + Index: 0.00MB
itc_amazon_orders: Data: 61.52MB + Index: 0.20MB
itc_amazon_payment: Data: 0.02MB + Index: 0.00MB
itc_amazon_profiles: Data: 0.02MB + Index: 0.00MB
itc_amazon_reports: Data: 0.08MB + Index: 0.00MB
itc_amazon_shipping: Data: 0.02MB + Index: 0.00MB
itc_amazon_stock_log: Data: 3.52MB + Index: 0.00MB
itc_commentmeta: Data: 0.02MB + Index: 0.03MB
itc_comments: Data: 10.52MB + Index: 10.09MB
itc_ebay_accounts: Data: 0.02MB + Index: 0.00MB
itc_ebay_auctions: Data: 50.58MB + Index: 1.45MB
itc_ebay_categories: Data: 6.52MB + Index: 3.03MB
itc_ebay_jobs: Data: 0.09MB + Index: 0.00MB
itc_ebay_log: Data: 338.05MB + Index: 2.97MB
itc_ebay_messages: Data: 0.02MB + Index: 0.00MB
itc_ebay_orders: Data: 90.56MB + Index: 0.52MB
itc_ebay_payment: Data: 0.02MB + Index: 0.00MB
itc_ebay_profiles: Data: 0.06MB + Index: 0.00MB
itc_ebay_shipping: Data: 0.02MB + Index: 0.00MB
itc_ebay_sites: Data: 0.03MB + Index: 0.00MB
itc_ebay_store_categories: Data: 0.02MB + Index: 0.03MB
itc_ebay_transactions: Data: 4.52MB + Index: 2.27MB
itc_links: Data: 0.02MB + Index: 0.02MB
itc_options: Data: 8.47MB + Index: 1.25MB
itc_postmeta: Data: 181.73MB + Index: 156.45MB
itc_posts: Data: 20.55MB + Index: 13.09MB
itc_termmeta: Data: 0.14MB + Index: 0.20MB
itc_terms: Data: 0.14MB + Index: 0.16MB
itc_term_relationships: Data: 4.52MB + Index: 3.52MB
itc_term_taxonomy: Data: 0.16MB + Index: 0.19MB
itc_usermeta: Data: 19.55MB + Index: 26.09MB
itc_users: Data: 1.52MB + Index: 1.05MB
itc_wc_download_log: Data: 0.02MB + Index: 0.03MB
itc_wc_points_rewards_user_points: Data: 1.52MB + Index: 1.94MB
itc_wc_points_rewards_user_points_log: Data: 1.52MB + Index: 1.09MB
itc_wc_webhooks: Data: 0.02MB + Index: 0.02MB
itc_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
itc_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB

### Post Type Counts ###

attachment: 20481
jetpack_migration: 2
nav_menu_item: 1
page: 7
post: 5
product: 11007
revision: 908
scheduled-action: 2849
shop_coupon: 750
shop_order: 9526
shop_order_refund: 79
wc_stamps_label: 6468
woo_discount: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Anti-spam: by webvitaly – 5.3
Bugsnag Error Monitoring: by Bugsnag Inc. – 1.3.1
Comic Cover Image Importer: by Mike Bronner – 0.1.0 – Not tested with the active version of WooCommerce
Cookie Notice: by dFactory – 1.2.46
WooCommerce Coupon Generator: by Jeroen Sormani – 1.0.1 – Not tested with the active version of WooCommerce
Disable XML-RPC: by Philip Erb – 1.0.1
Homepage Control: by WooThemes – 2.0.3
Limit Post Titles: by Cocoon Development Ltd – 1.0.2
Metorik Helper: by Metorik – 1.0.5
Postmark (Official): by Andrew Yates & Matt Gibbs – 1.11.2
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Hamburger Menu: by WooCommerce – 1.2.2
Storefront Powerpack: by WooCommerce – 1.4.12 – 1.4.14 is available
Storefront Product Pagination: by WooThemes – 1.2.4 – Not tested with the active version of WooCommerce
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Reviews: by WooCommerce – 1.0.4 – Not tested with the active version of WooCommerce
Storefront Sticky Add to Cart: by WooThemes – 1.1.9
Title Remover: by WPGurus – 1.2
WP Twitter Auto Publish: by xyzscripts.com
customized by Mike Bronner (GeneaLabs) for Imagine That! Comics – 999-custom

User Role Editor: by Vladimir Garagulya – 4.49
User Switching: by John Blackbourn & contributors – 1.4.2
Woocommerce Age Restricted Shopping: by Magnigenie – 1.6 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.1
Woocommerce Customizations: by Mike Bronner – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.7
Import from eBay to WooCommerce: by WP Lab – 1.6.4 – Not tested with the active version of WooCommerce
WooCommerce MSRP Pricing: by Lee Willis – 2.9.10
WooCommerce Points and Rewards: by WooCommerce – 1.6.17
WooCommerce Shipment Tracking: by WooCommerce – 1.6.12
WooCommerce Stamps.com API integration: by WooCommerce – 1.3.8
WooCommerce: by Automattic – 3.5.4
Genealabs CDN Rewriter: by Mike Bronner – 0.1.0
Yoast SEO: by Team Yoast – 9.6
WP-Lister Pro for Amazon: by WP Lab – 0.9.19
WP-Lister Pro for eBay: by WP Lab – 2.0.43 – Not tested with the active version of WooCommerce
Remove WooCommerce Connect Your Store Notice: by WPspring – 1.0.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Bookshop
Version: 1.0.15
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by rrennick** [comment]
Can you provide a list of the recent failed actions from the Tools -> Scheduled Actions screen?

**Comment by mikebronner** [comment]
Sorry for the late reply ... looking into this now.

**Comment by mikebronner** [comment]
Using the `Health Check` plugin, I see the following warning:

> Scheduled events | A scheduled event (wpseo_ping_search_engines) has failed to run. Your site still works, but this may indicate that scheduling posts or automated updates may not work as intended.

I have disabled Yoast SEO and am wondering if there is something stuck in the schedule queue. Is there an easy way to see what's there, and remove the offender?

**Comment by mikebronner** [comment]
I just tested it with all plugins and themes (except for Woocommerce and twentynineteen) disabled. I get the following error when accessing the page with debug mode turned on:

>Fatal error: Uncaught TypeError: Argument 4 passed to ActionScheduler_ActionFactory::get_stored_action() must be an instance of ActionScheduler_Schedule or null, string given, called in /home/codepier/maureentaylor.com/20190222231130/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 111 and defined in /home/codepier/maureentaylor.com/20190222231130/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php:17 Stack trace: #0 /home/codepier/maureentaylor.com/20190222231130/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(111): ActionScheduler_ActionFactory->get_stored_action('complete', 'woocommerce_del...', Array, 'O:30:"ActionSch...', 'woocommerce-web...') #1 /home/codepier/maureentaylor.com/20190222231130/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(81): ActionScheduler_wpPostStore->make_a in /home/codepier/maureentaylor.com/20190222231130/public/app/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php on line 17

**Comment by mikejolley** [comment]
This would only happen if the schedule meta was corrupted and not of the correct type. I'll put in a PR to check for this but it won't fix the underlying cause (likely the plugin implementing it).

**Comment by mikejolley** [comment]
See https://github.com/Prospress/action-scheduler/pull/238

**Comment by mikebronner** [comment]
@mikejolley @rrennick Is there a hook (or any other method) I can use to replace this class in in my `function.php` file until the patch is pushed downstream into WooCommerce and released? This is kind of on the urgent side of things for us from a business point of view, and I would like to try to bandage the fix until it is rolled out. Thanks for your help! :)

**Comment by rrennick** [comment]
@mikebronner You can download the zip from https://github.com/Prospress/action-scheduler, install and activate it. Once it's active, it will replace the action scheduler included in WC.

**Comment by mikebronner** [comment]
@rrennick Oh! So I can just add this as a plugin (I'm installing via composer) and it will do the rest? My work-around for now was to write a bash script that runs after deployment and copies over the updated file (which is working for now, but will obviously break when the new version comes out).

**Comment by rrennick** [comment]
> and it will do the rest? 

Yes.

**Comment by mikebronner** [comment]
Unfortunately this didn't work. I installed and activated the `prospress/action-scheduler` plugin directly, but the WooCommerce page `Tools > Scheduled Actions` is still broken. Will stick with my work-around for now.

**Comment by rrennick** [comment]
Have you looked at Tools (main menu) > Scheduled Actions ? If that screen is still broken can you post some details of which plugins you have that are using scheduled actions on https://github.com/Prospress/action-scheduler/pull/238 ?

**Comment by mikebronner** [comment]
@rrennick Yea, that's the page that isn't working. How do I identify which plugins are using scheduled actions? Is there anything specifically I can run a code-search for?

**Comment by rrennick** [comment]
You can search for function calls to any of the functions in https://github.com/Prospress/action-scheduler/blob/master/functions.php

**Comment by mikebronner** [comment]
@rrennick WooCommerce is the only plugin calling any of those functions.

**Comment by rrennick** [comment]
I manually edited the database so the first scheduled action in the list would trigger this error. After verifying that no actions are listed, I installed and activated https://github.com/Prospress/action-scheduler/archive/master.zip . The action list shows but the first action has no scheduled date.
