### ISSUE TITLE
Fatal error ArgumentCountError: Too few arguments to function WC_Template_Loader::unsupported_theme_title_filter()

### ISSUE THREAD

**Issue by norman-pixelkings** [woocommerce/woocommerce#22814]
**Describe the bug**
I created a Pods (custom post type) List on a page for some some custom items. But when enabling Woocommerce I get a fatal error.

**To Reproduce**
1. Create Custom Post (pods) + Pod template with only "post_title" field in it
2. Create a new page and call the shortcode for the Pod
3. Save and browse the page
4. 500 error 
5. Disabling Woocommerce resolves the problem but also removing the post_title field in the Pods template does. 

**Error**
[22-Feb-2019 07:38:18 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Template_Loader::unsupported_theme_title_filter(), 1 passed in /Users/norman/sites/wordpress/www/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /Users/norman/sites/wordpress/www/wp-content/plugins/woocommerce/includes/class-wc-template-loader.php:399
Stack trace:
#0 /Users/norman/sites/wordpress/www/wp-includes/class-wp-hook.php(286): WC_Template_Loader::unsupported_theme_title_filter('test')
#1 /Users/norman/sites/wordpress/www/wp-includes/plugin.php(203): WP_Hook->apply_filters('test', Array)
#2 /Users/norman/sites/wordpress/www/wp-content/plugins/pods/classes/Pods.php(1910): apply_filters('the_title', 'test')
#3 /Users/norman/sites/wordpress/www/wp-content/plugins/pods/classes/Pods.php(699): Pods->field(Array)
#4 /Users/norman/sites/wordpress/www/wp-content/plugins/pods/classes/Pods.php(4176): Pods->display('post_title')

**Screenshots**
White page with 500 error occurs

**Expected behavior**
A normal page rendering. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://dev.haef.nu
Site URL: http://dev.haef.nu
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - Er is een nieuwere versie van WordPress beschikbaar (5.1)
WP Multisite: ✔
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.22 - We raden je aan om PHP-versie 7.2 of hoger te gebruiken voor betere prestaties en beveiliging. Hoe je PHP-versie bijwerken
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wcenv1_37_
MaxMind GeoIP Database: ✔
Totale databasegrootte: 7.14MB
Database datagrootte: 5.31MB
Database index grootte: 1.83MB
wcenv1_37_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wcenv1_37_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wcenv1_37_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wcenv1_37_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wcenv1_37_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wcenv1_37_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wcenv1_37_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wcenv1_37_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wcenv1_37_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wcenv1_37_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wcenv1_37_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wcenv1_37_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wcenv1_37_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wcenv1_37_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wcenv1_37_alm: Data: 0.02MB + Index: 0.00MB
wcenv1_37_commentmeta: Data: 0.02MB + Index: 0.03MB
wcenv1_37_comments: Data: 0.02MB + Index: 0.08MB
wcenv1_37_failed_jobs: Data: 0.02MB + Index: 0.00MB
wcenv1_37_links: Data: 0.02MB + Index: 0.02MB
wcenv1_37_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wcenv1_37_options: Data: 1.06MB + Index: 0.05MB
wcenv1_37_pmxi_files: Data: 0.02MB + Index: 0.00MB
wcenv1_37_pmxi_history: Data: 0.02MB + Index: 0.00MB
wcenv1_37_pmxi_images: Data: 0.02MB + Index: 0.00MB
wcenv1_37_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wcenv1_37_pmxi_posts: Data: 0.02MB + Index: 0.03MB
wcenv1_37_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wcenv1_37_podsrel: Data: 0.02MB + Index: 0.06MB
wcenv1_37_postmeta: Data: 1.52MB + Index: 0.45MB
wcenv1_37_posts: Data: 0.33MB + Index: 0.06MB
wcenv1_37_queue: Data: 0.02MB + Index: 0.00MB
wcenv1_37_relevanssi: Data: 0.02MB + Index: 0.06MB
wcenv1_37_relevanssi_log: Data: 0.02MB + Index: 0.00MB
wcenv1_37_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wcenv1_37_termmeta: Data: 0.02MB + Index: 0.03MB
wcenv1_37_terms: Data: 0.02MB + Index: 0.03MB
wcenv1_37_term_relationships: Data: 0.08MB + Index: 0.02MB
wcenv1_37_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wcenv1_37_wc_download_log: Data: 0.02MB + Index: 0.03MB
wcenv1_37_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wcenv1_37_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wcenv1_37_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wcenv1_blogs: Data: 0.02MB + Index: 0.03MB
wcenv1_blog_versions: Data: 0.02MB + Index: 0.02MB
wcenv1_registration_log: Data: 0.02MB + Index: 0.02MB
wcenv1_signups: Data: 0.02MB + Index: 0.06MB
wcenv1_site: Data: 0.02MB + Index: 0.02MB
wcenv1_sitemeta: Data: 1.08MB + Index: 0.03MB
wcenv1_usermeta: Data: 0.36MB + Index: 0.22MB
wcenv1_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

_pods_field: 6
_pods_pod: 4
_pods_template: 3
attachment: 175
nav_menu_item: 9
oembed_cache: 8
page: 13
panel: 12
post: 2
product: 65
product_variation: 2
revision: 83
test: 2
tribe_events: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ❌Foutmeldingen zouden niet getoond moeten worden aan bezoekers.

### Active Plugins (34) ###

Pods - Custom Content Types and Fields: door Pods Framework Team – 2.7.12
WooCommerce: door Automattic – 3.5.5
All-in-One WP Migration: door ServMask – 6.84
All-in-One WP Migration Multisite Extension: door ServMask – 3.67
BackWPup: door Inpsyde GmbH – 3.6.7
Breadcrumb NavXT: door John Havlik – 6.2.1
Contact Form CFDB7: door Arshid – 1.2.4.6
Elementor: door Elementor.com – 2.4.7
Elementor Pro: door Elementor.com – 2.4.5
Media Library Categories: door Jeffrey-WP – 1.7
Nested Pages: door Kyle Phillips – 3.0.7
Pods Alternative Cache: door Pods Framework Team – 2.0.5
Pods SEO: door Pods Framework Team – 2.1
Show Current Template: door JOTAKI Taisuke – 0.3.0
Surbma - Yoast SEO Breadcrumb Shortcode: door Surbma – 1.0.4
Timber: door Jared Novack + Upstatement – 1.9.0
WP-Optimize: door David Anderson
Ruhani Rabin
Team Updraft – 2.2.12

WPSHAPERE: door AcmeeDesign Softwares and Solutions – 4.8
Adminimize: door Frank Bültge – 1.11.4
Simple Page Ordering: door Jake Goldman
10up – 2.3.2

Post Types Order: door Nsp Code – 1.9.3.9
Better Search Replace: door Delicious Brains – 1.3.2
reSmush.it Image Optimizer: door reSmush.it – 0.1.22
Simple Image Sizes: door Rahe – 3.2.0
Jet Popup: door Zemez – 1.2.4
Unconfirmed: door Boone B Gorges – 1.3.3
Regenerate Thumbnails: door Alex Mills (Viper007Bond) – 3.1.0
Mailgun: door Mailgun – 1.7.1
Advanced Sidebar Menu: door Mat Lipe – 7.4.7
Multisite Plugin Manager: door Aaron Edwards – 3.1.6
Debug Bar: door wordpressdotorg – 1.0
Webcraftic Robin image optimizer: door Webcraftic  – 1.1.5
WP User Profiles: door John James Jacoby – 2.1.0
WP User Avatars: door John James Jacoby – 1.4.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Winkelbasis: #5 - /winkel/
Winkelmand: #6 - /winkelmand/
Afrekenen: #7 - /afrekenen/
Mijn account: #8 - /mijn-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Webchimp subtheme
Version: 0.0.1
Author URL: http://norman.vandermull.nl
Child Theme: ✔
Parent Theme Name: Webchimp base
Parent Theme Version: 2.10.3
Parent Theme Author URL: http://olefredrik.com/
WooCommerce Support: ❌ Niet aangegeven

### Templates ###

Archive Template: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: –
`
```
</details>

**Comment by claudiosanches** [comment]
This sound like conflict coming from that `pods` plugin, please contact the pods author.
