### ISSUE TITLE
Twenty Nineteen back compat conflict with WooCommerce

### ISSUE THREAD

**Issue by mahdiyazdani** [woocommerce/woocommerce#22866]
Activating Twenty Nineteen theme in WordPress 4.7 results to the following fatal error message:

```
Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /Applications/MAMP/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-notices.php:371 Stack trace: #0 /Applications/MAMP/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-notices.php(95): WC_Admin_Notices::add_wootenberg_feature_plugin_notice() #1 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(288): WC_Admin_Notices::reset_admin_notices('Twenty Nineteen') #2 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /Applications/MAMP/htdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /Applications/MAMP/htdocs/wp-includes/theme.php(792): do_action('switch_theme', 'Twenty Nineteen', Object(WP_Theme), Object(WP_Theme)) #5 /Applications/MAMP/htdocs/wp-content/themes/twentynineteen/inc/back-compat.php(22): switch_theme('twentynineteen') #6 /Applications/MAMP/htdocs/wp-includes/class-wp-hook.php(288): twentynineteen_switch_theme('Conj') #7 /Application in /Applications/MAMP/htdocs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-notices.php on line 371
```

**Comment by mikejolley** [comment]
Unable to replicate this one. 

- Downgraded to 4.7
- Activated Storefront/Twenty Nineteen

No errors.

https://codex.wordpress.org/Function_Reference/is_plugin_active has been around since 2.5. If used in the admin area (as we do) it's included.

I can add a check to harden this anyway, but pointing out there are no issues with 4.7.

**Comment by mikejolley** [comment]
I can see one case which could error, if the installer ran on the frontend. Will submit a patch.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22893
