### ISSUE TITLE
unsupported operand on price filter widget

### ISSUE THREAD

**Issue by spyrosvl** [woocommerce/woocommerce#23494]
**Describe the bug**
Line 162 on `/wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-price-filter.php` produces an error in some case when the `$args['meta_query']` isset but its value is false.

It should be set to `$meta_query = isset( $args['meta_query'] ) && $args['meta_query'] !== false ? $args['meta_query'] : array();`

**To Reproduce**
Not sure as I did not enter the products.

The error:
`Fatal error: Uncaught Error: Unsupported operand types in /wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-price-filter.php:162 Stack trace: #0 /wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-price-filter.php(87): WC_Widget_Price_Filter->get_filtered_price() #1 /wp-includes/class-wp-widget.php(378): WC_Widget_Price_Filter->widget(Array, Array) #2 /wp-includes/widgets.php(770): WP_Widget->display_callback(Array, Array) #3 /wp-content/themes/flatmarket/woocommerce/global/sidebar.php(14): dynamic_sidebar('shop-sidebar') #4 /wp-content/plugins/woocommerce/includes/wc-core-functions.php(249): include('/home/-...') #5 /wp-content/plugins/woocommerce/includes/wc-template-functions.php(997): wc_get_template('global/sidebar....') in /wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-price-filter.php on line 162`

**Expected behavior**
I was expecting to load the price filter

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://xxxx
Site address (URL): https://xxxx
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6
PHP Version: 7.1.27 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 9999
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.12-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
Total Database Size: 205.53MB
Database Data Size: 149.53MB
Database Index Size: 56.00MB
wp_woocommerce_sessions: Data: 15.02MB + Index: 0.25MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.68MB + Index: 0.29MB
wp_woocommerce_order_itemmeta: Data: 3.02MB + Index: 2.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_better_user_search_meta_keys: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.06MB + Index: 0.05MB
wp_comments: Data: 2.52MB + Index: 0.77MB
wp_fg_redirect: Data: 0.00MB + Index: 0.01MB
wp_hellaspay_data: Data: 0.09MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 4.52MB + Index: 1.03MB
wp_postmeta: Data: 59.58MB + Index: 20.06MB
wp_posts: Data: 18.52MB + Index: 2.53MB
wp_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB
wp_rank_math_internal_links: Data: 0.44MB + Index: 0.14MB
wp_rank_math_internal_meta: Data: 0.08MB + Index: 0.00MB
wp_rank_math_redirections: Data: 0.05MB + Index: 0.02MB
wp_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB
wp_rank_math_sc_analytics: Data: 4.52MB + Index: 2.52MB
wp_revslider_css: Data: 0.09MB + Index: 0.01MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_revslider_slides: Data: 0.10MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_seopressor_link: Data: 0.08MB + Index: 0.00MB
wp_seopressor_logs: Data: 0.02MB + Index: 0.00MB
wp_seopressor_roles_capabilities: Data: 0.02MB + Index: 0.00MB
wp_seopressor_site_audit: Data: 0.02MB + Index: 0.00MB
wp_seopressor_site_audit_crawler: Data: 0.06MB + Index: 0.02MB
wp_seopressor_smart_linking: Data: 0.02MB + Index: 0.00MB
wp_seopressor_users_custom_roles: Data: 0.02MB + Index: 0.00MB
wp_swpext_metrics_clicks: Data: 0.02MB + Index: 0.03MB
wp_swpext_metrics_ids: Data: 0.02MB + Index: 0.02MB
wp_swpext_metrics_queries: Data: 0.02MB + Index: 0.02MB
wp_swpext_metrics_searches: Data: 0.02MB + Index: 0.08MB
wp_swp_cf: Data: 0.23MB + Index: 0.28MB
wp_swp_index: Data: 28.55MB + Index: 15.03MB
wp_swp_log: Data: 0.02MB + Index: 0.05MB
wp_swp_tax: Data: 0.02MB + Index: 0.05MB
wp_swp_terms: Data: 3.52MB + Index: 4.55MB
wp_termmeta: Data: 0.46MB + Index: 0.31MB
wp_terms: Data: 1.52MB + Index: 1.81MB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 1.52MB + Index: 0.50MB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB
wp_usermeta: Data: 1.52MB + Index: 0.84MB
wp_users: Data: 0.09MB + Index: 0.08MB
wp_vivawallet_data: Data: 0.02MB + Index: 0.00MB
wp_viva_payment_transactions: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_email_notify: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.34MB + Index: 0.69MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woobe_history: Data: 0.02MB + Index: 0.05MB
wp_woobe_history_bulk: Data: 0.02MB + Index: 0.03MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
wp_yoast_seo_links: Data: 0.17MB + Index: 0.05MB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

aiosrs-schema: 5
attachment: 5330
customize_changeset: 6
mc4wp-form: 1
nav_menu_item: 31
oembed_cache: 10
page: 24
post: 80
product: 2014
product_variation: 1347
revision: 42
scheduled-action: 15
shop_coupon: 4
shop_order: 3115
tm_global_cp: 1
tm_product_cp: 117
wc_xml_feeds: 1
wpcf7_contact_form: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (55) ###

AJAX Thumbnail Rebuild: by junkcoder
ristoniinemets – 1.13

Akismet Anti-Spam: by Automattic – 4.1.1
Better User Search: by Dale Higgs – 1.1.1
Bulk Move: by Sudar – 1.3.0
BulkPress: by Jesper van Engelen – 0.3.5
Classic Editor: by WordPress Contributors – 1.4
Codeable theme functions: by Spyros Vlachopoulos – 1.0
CodeStyling Localization: by Heiko Rabe – 1.99.30
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.1.6 – Not tested with the active version of WooCommerce
Envato Market: by Envato – 2.0.1
Export User Data: by Q Studio – 1.3.1
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.8
WooCommerce advanced cash on delivey with fee/surcharge: by idnovate.com – 1.0.8 – Not tested with the active version of WooCommerce
WPBakery Visual Composer: by Michael M - WPBakery.com – 4.12
Lazy Load: by  – 0.6.1
Mailchimp for WordPress: by ibericode – 4.5.1
Mega Main Menu: by MegaMain.com – 2.1.2
Ultimate WooCommerce Brands PRO: by MagniumThemes – 1.1.1 – Not tested with the active version of WooCommerce
Official Facebook Pixel: by Facebook – 1.7.25
Post Type Switcher: by John James Jacoby – 3.1.0
PrettyPhoto: by Babar – 1.2
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.5

reSmush.it Image Optimizer: by reSmush.it – 0.1.22
Rich Text Tags, Categories, and Taxonomies: by Katz Web Services
Inc. – 1.8

SEMrush SEO Writing Assistant: by SEMrush – 1.0.4
Rank Math SEO: by Rank Math – 1.0.23
Simple WP Retina: by Jonathan Desrosiers & Slocum Design Studio – 1.1.1
WooCommerce Skroutz Analytics: by Skroutz – 1.4.0
SyntaxHighlighter Evolved: by Alex Mills (Viper007Bond) – 3.5.0
Term Management Tools: by scribu – 1.1.4
Theme My Login: by Jeff Farthing – 6.4.9
Thumbnail Upscale: by Stanislav Khromov – 1.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.12

WooCommerce Vivawallet Gateway: by Viva Wallet – 3.3.5 – Not tested with the active version of WooCommerce
Widget Title Links: by Illimar Tambek – 1.4.1
Woocommerce Meta Filter by Nitroweb: by Nitroweb – 1.0.0 – Not tested with the active version of WooCommerce
Advanced Order Export For WooCommerce: by AlgolPlus – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce Quickview: by James Kemp – 3.0.5 – Not tested with the active version of WooCommerce
Woocommerce XML Feeds: by Spyros Vlachopoulos – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce Bulk Editor: by realmag777 – 2.0.3 – Not tested with the active version of WooCommerce
WooCommerce COD Advanced: by AheadZen – 1.3.0 – Not tested with the active version of WooCommerce
WooCommerce Shipping Pro with Table Rate: by WooForce – 2.4.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by Bolder Elements – 4.1.3 – Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themeComplete – 4.6.9.4 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.2
WP Add Custom CSS: by Daniele De Santis – 1.1.4
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP DB Clean Up: by Spyros Vlachopoulos – 1.0
WP Featherlight: by Cipher – 1.3.0
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.3.3

WP Rocket: by WP Media – 3.3.1.1
Schema Pro: by Brainstorm Force – 1.2.0
YITH WooCommerce Ajax Search (Modified by MT): by Your Inspiration Themes – 100.1.1.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITH – 2.2.10

### Inactive Plugins (3) ###

Slider Revolution: by ThemePunch – 5.3.1.5
WooCommerce Sales Countdown: by Andy Ha (tu@wpbriz.com) – 1.8.3 – Not tested with the active version of WooCommerce
YITH WooCommerce Compare: by YITH – 2.3.10

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3117 - /%cf%80%cf%81%ce%bf%cf%8a%cf%8c%ce%bd%cf%84%ce%b1/
Cart: #3118 - /cart/
Checkout: #3119 - /checkout/
My account: #3120 - /%ce%bf-%ce%bb%ce%bf%ce%b3%ce%b1%cf%81%ce%b9%ce%b1%cf%83%ce%bc%cf%8c%cf%82-%ce%bc%ce%bf%cf%85/
Terms and conditions: #3217 - /oroi-xrisis/

### Theme ###

Name: flatmarket-child
Version: 1.0
Author URL: http://magniumthemes.com/
Child Theme: ✔
Parent Theme Name: FlatMarket
Parent Theme Version: 1.9.2
Parent Theme Author URL: http://magniumthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatmarket/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php
flatmarket-child/woocommerce/cart/cart-shipping.php version 2.3.0 is out of date. The core version is 3.6.0
flatmarket-child/woocommerce/cart/cart-totals.php version 2.1.0 is out of date. The core version is 2.3.6
flatmarket/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
flatmarket/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.6.0
flatmarket-child/woocommerce/content-product_cat.php version 1.6.4 is out of date. The core version is 2.6.1
flatmarket/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.6.0
flatmarket/woocommerce/content-widget-product.php version 2.5.0 is out of date. The core version is 3.5.5
flatmarket/woocommerce/global/form-login.php version 2.1.0 is out of date. The core version is 3.6.0
flatmarket/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.6.0
flatmarket/woocommerce/global/sidebar.php
flatmarket/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
flatmarket/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
flatmarket/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.3.0
flatmarket/woocommerce/loop/loop-end.php
flatmarket/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
flatmarket/woocommerce/loop/no-products-found.php
flatmarket/woocommerce/loop/price.php
flatmarket/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.6.0
flatmarket/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.3.0
flatmarket/woocommerce/loop/sale-flash.php
flatmarket/woocommerce/notices/error.php version 1.6.4 is out of date. The core version is 3.5.0
flatmarket/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.5.0
flatmarket/woocommerce/notices/success.php version 1.6.4 is out of date. The core version is 3.5.0
flatmarket/product-searchform.php version 2.5.0 is out of date. The core version is 3.3.0
flatmarket/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0
flatmarket/woocommerce/single-product/add-to-cart/grouped.php version 2.1.7 is out of date. The core version is 3.4.0
flatmarket/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.4.0
flatmarket/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.5.5
flatmarket/woocommerce/single-product/meta.php version 1.6.4 is out of date. The core version is 3.0.0
flatmarket/woocommerce/single-product/price.php version 2.5.0 is out of date. The core version is 3.0.0
flatmarket/woocommerce/single-product/product-attributes.php version 2.1.3 is out of date. The core version is 3.6.0
flatmarket/woocommerce/single-product/product-image.php version 2.6.3 is out of date. The core version is 3.5.1
flatmarket/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.5.1
flatmarket/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.6.0
flatmarket/woocommerce/single-product/related.php version 1.6.4 is out of date. The core version is 3.0.0
flatmarket/woocommerce/single-product/review.php version 2.1.0 is out of date. The core version is 2.6.0
flatmarket/woocommerce/single-product/sale-flash.php
flatmarket/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
flatmarket/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
flatmarket/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
flatmarket/woocommerce/single-product/tabs/description.php
flatmarket/woocommerce/single-product/tabs/tabs.php
flatmarket-child/woocommerce/single-product/title.php
flatmarket/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
flatmarket/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.6.0
flatmarket/woocommerce/single-product.php
flatmarket/woocommerce/taxonomy-product_cat.php
flatmarket/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 15
Oldest: 2019-04-24 22:31:20 +0300
Newest: 2019-04-24 22:33:23 +0300

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by claudiosanches** [comment]
This sounds like some plugin or custom code changing it, since `meta_query` should be always be an Array, not Boolean.

Since there's no steps to reproduce, it's hard to know the origin of it.
I'll close for now, since I'm not able to reproduce, but free feel to post if you find a way to reproduce.
