### ISSUE TITLE
Shipping Hook returns 500

### ISSUE THREAD

**Issue by ChristianGiupponi** [woocommerce/woocommerce#23503]
**Describe the bug**
I need to add some meta to the shipping method after the order creation.  
The hook I used is:

`woocommerce_checkout_create_order_shipping_item`

If you try to hook on it, it will returns 500 error with no data or message.
In logs I heve:

```
2019-04-25T08:46:48+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function ZerounoWCMetadata::zerouno_order_shipping_item(), 3 passed in /app/public/wp-includes/class-wp-hook.php on line 286 and exactly 4 expected in /app/public/wp-content/plugins/zerouno-woocommerce-addons/zerouno-wc-metadata/zerouno-wc-metadata.php:71
Stack trace:
#0 /app/public/wp-includes/class-wp-hook.php(286): ZerounoWCMetadata->zerouno_order_shipping_item(Object(WC_Order_Item_Shipping), 0, Array)
#1 /app/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /app/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /app/public/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-checkout.php(304): do_action('woocommerce_che...', Object(WC_Order_Item_Shipping), 0, Array)
#4 /app/public/wp-content/plugins/woocommerce-subscriptions/includes/class-wc-subscriptions-checkout.php(193): WC_Subscriptions_Checkout::add_shipping(Object(WC_Subscription), Object(WC_Cart))
#5 /app/public/wp-content/plugin in /app/public/wp-content/plugins/zerouno-woocommerce-addons/zerouno-wc-metadata/zerouno-wc-metadata.php alla riga 71

```
**To Reproduce**
1. Add this to your function.php or plugin
```
add_action('woocommerce_checkout_create_order_shipping_item', 'custom_order_shipping_item', 10, 4);
function custom_order_shipping_item($item, $package_key, $package, $order){
    $item->update_meta_data('custom title', 'custom value');
}
```
2. Add an item to the cart ( make sure to have at least one shipping method, no metter what)
3. Complete the checkout process

**Screenshots**
![Schermata 2019-04-25 alle 10 59 03](https://user-images.githubusercontent.com/1614796/56723409-2e62a100-6749-11e9-9074-61ea51ddcf1d.png)

**Expected behavior**
I expect to complete the checkout process without error and redirect to the order completed page

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://youfarmer.local
Site address (URL): https://youfarmer.local
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.0
PHP Post Max Size: 1.000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1.000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wsoff_
MaxMind GeoIP Database: ✔
Dimensione totale database: 4.73MB
Dimensione dati database: 2.78MB
Dimensione indice database: 1.95MB
wsoff_woocommerce_sessions: Dati: 0.02MB + Indice: 0.02MB
wsoff_woocommerce_api_keys: Dati: 0.02MB + Indice: 0.03MB
wsoff_woocommerce_attribute_taxonomies: Dati: 0.02MB + Indice: 0.02MB
wsoff_woocommerce_downloadable_product_permissions: Dati: 0.02MB + Indice: 0.06MB
wsoff_woocommerce_order_items: Dati: 0.02MB + Indice: 0.02MB
wsoff_woocommerce_order_itemmeta: Dati: 0.05MB + Indice: 0.03MB
wsoff_woocommerce_tax_rates: Dati: 0.02MB + Indice: 0.06MB
wsoff_woocommerce_tax_rate_locations: Dati: 0.02MB + Indice: 0.03MB
wsoff_woocommerce_shipping_zones: Dati: 0.02MB + Indice: 0.00MB
wsoff_woocommerce_shipping_zone_locations: Dati: 0.02MB + Indice: 0.03MB
wsoff_woocommerce_shipping_zone_methods: Dati: 0.02MB + Indice: 0.00MB
wsoff_woocommerce_payment_tokens: Dati: 0.02MB + Indice: 0.02MB
wsoff_woocommerce_payment_tokenmeta: Dati: 0.02MB + Indice: 0.03MB
wsoff_woocommerce_log: Dati: 0.02MB + Indice: 0.02MB
wsoff_commentmeta: Dati: 0.02MB + Indice: 0.03MB
wsoff_comments: Dati: 0.08MB + Indice: 0.09MB
wsoff_gf_draft_submissions: Dati: 0.02MB + Indice: 0.02MB
wsoff_gf_entry: Dati: 0.02MB + Indice: 0.03MB
wsoff_gf_entry_meta: Dati: 0.02MB + Indice: 0.05MB
wsoff_gf_entry_notes: Dati: 0.02MB + Indice: 0.03MB
wsoff_gf_form: Dati: 0.02MB + Indice: 0.00MB
wsoff_gf_form_meta: Dati: 0.03MB + Indice: 0.00MB
wsoff_gf_form_revisions: Dati: 0.02MB + Indice: 0.03MB
wsoff_gf_form_view: Dati: 0.02MB + Indice: 0.03MB
wsoff_links: Dati: 0.02MB + Indice: 0.02MB
wsoff_options: Dati: 1.09MB + Indice: 0.06MB
wsoff_pmxi_files: Dati: 0.02MB + Indice: 0.00MB
wsoff_pmxi_history: Dati: 0.02MB + Indice: 0.00MB
wsoff_pmxi_images: Dati: 0.02MB + Indice: 0.00MB
wsoff_pmxi_imports: Dati: 0.02MB + Indice: 0.00MB
wsoff_pmxi_posts: Dati: 0.02MB + Indice: 0.03MB
wsoff_pmxi_templates: Dati: 0.02MB + Indice: 0.00MB
wsoff_postmeta: Dati: 0.38MB + Indice: 0.41MB
wsoff_posts: Dati: 0.20MB + Indice: 0.09MB
wsoff_pum_subscribers: Dati: 0.02MB + Indice: 0.06MB
wsoff_smush_dir_images: Dati: 0.02MB + Indice: 0.03MB
wsoff_termmeta: Dati: 0.02MB + Indice: 0.03MB
wsoff_terms: Dati: 0.02MB + Indice: 0.03MB
wsoff_term_relationships: Dati: 0.02MB + Indice: 0.02MB
wsoff_term_taxonomy: Dati: 0.02MB + Indice: 0.03MB
wsoff_toolset_associations: Dati: 0.02MB + Indice: 0.05MB
wsoff_toolset_post_guid_id: Dati: 0.02MB + Indice: 0.02MB
wsoff_toolset_relationships: Dati: 0.02MB + Indice: 0.08MB
wsoff_toolset_type_sets: Dati: 0.02MB + Indice: 0.03MB
wsoff_usermeta: Dati: 0.03MB + Indice: 0.03MB
wsoff_users: Dati: 0.02MB + Indice: 0.05MB
wsoff_wcs_payment_retries: Dati: 0.02MB + Indice: 0.02MB
wsoff_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
wsoff_wc_product_meta_lookup: Dati: 0.02MB + Indice: 0.09MB
wsoff_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
wsoff_woof_query_cache: Dati: 0.02MB + Indice: 0.02MB
wsoff_yoast_seo_links: Dati: 0.02MB + Indice: 0.02MB
wsoff_yoast_seo_meta: Dati: 0.02MB + Indice: 0.00MB

### Post Type Counts ###

acf-field: 17
acf-field-group: 5
attachment: 9
azienda-agricola: 7
customize_changeset: 4
dicono-di-noi: 4
naturasi: 1
page: 13
partner: 2
popup_theme: 6
post: 4
product: 10
product_variation: 82
revision: 29
scheduled-action: 116
shop_order: 15
shop_subscription: 3
verdura: 2
verdura-azienda-agri: 1
yf_faq: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌I messaggi di errore non saranno mostrati ai visitatori.

### Active Plugins (20) ###

Gravity Forms: by rocketgenius – 2.4.8
Advanced Custom Fields PRO: by Elliot Condon – 5.7.13
Classic Editor: by Contributori WordPress – 1.4
Elementor Pro: by Elementor.com – 2.5.5
Elementor: by Elementor.com – 2.5.14
Kadence WooCommerce Email Designer: by Kadence Themes – 1.1.8 – Non testato con la versione attiva di WooCommerce
Popup Maker: by WP Popup Maker – 1.8.5
Post Types Order: by Codice Nsp – 1.9.3.9
Simple 301 Redirects: by Scott Nellé – 1.07
SVG Support: by Benbodhi – 2.3.15
Toolset Types: by OnTheGoSystems – 3.2.7
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce Subscriptions: by Prospress Inc. – 2.5.3 – Non testato con la versione attiva di WooCommerce
WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.0 – Non testato con la versione attiva di WooCommerce
WP Mail SMTP: by WPForms – 1.4.2
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.93
01DEV - Custom Post Types: by 01DEV SRL – 1.0.0
01DEV - GF & WC bridge: by 01DEV SRL – 1.0.0 – Non testato con la versione attiva di WooCommerce
01DEV - WooCommerce Addons: by 01DEV SRL – 1.0.0 – Non testato con la versione attiva di WooCommerce

### Inactive Plugins (13) ###

Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.15
Smush: by WPMU DEV – 3.2.0.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.9
WOOF - WooCommerce Products Filter: by realmag777 – 2.2.0 – Non testato con la versione attiva di WooCommerce
Woo Local PickUp: by Swetanka Jaiswal – 1.0.1 – Non testato con la versione attiva di WooCommerce
WP All Import: by Soflyy – 3.5.0
WP All Import - ACF Add-On: by Soflyy – 3.2.0
WP All Import - WooCommerce Add-On: by Soflyy – 1.4.1
WPML Media: by OnTheGoSystems – 2.5.2
WPML Multilingual CMS: by OnTheGoSystems – 4.2.6
WPML String Translation: by OnTheGoSystems – 2.10.4
WPML Translation Management: by OnTheGoSystems – 2.8.5
YITH WooCommerce Social Login: by YITH – 1.3.1

### Must Use Plugins (3) ###

01DEV - Custom Login: by 01DEV SRL – 1.0
01DEV - Dashboard: by 01DEV SRL – 1.0.0
01DEV - Utilities: by 01DEV SRL – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ La pagina non è impostata
Carrello: #81 - /carrello/
Cassa: #83 - /pagamento/
Il mio account: #85 - /pannello-utente/
Termini e condizioni: #16 - /termini-e-condizioni/

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se stai modificando WooCommerce o un tema genitore che non hai costruito personalmente
ti consigliamo di utilizzare un child theme. Vedi: Come creare un child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://youfarmer.local
Subscription Statuses: trash: 2
wc-active: 1

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Italia — Pavia

### Subscriptions by Payment Gateway ###

Stripe: trash: 2
wc-active: 1


### Payment Gateway Support ###

PayPal: products
refunds

PayPal Reference Transactions Enabled: ❌ No
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders


### Action Scheduler ###

Complete: 96
Oldest: 2019-03-25 10:18:44 +0000
Newest: 2019-04-25 08:56:41 +0000

Pending: 2
Oldest: 2019-05-01 15:44:29 +0000
Newest: 2019-05-09 08:31:11 +0000

Canceled: 18
Oldest: 2019-04-18 16:01:24 +0000
Newest: 2019-05-16 12:11:04 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by ChristianGiupponi** [comment]
Ok, the problem is` woocommerce-subscription` that send only 3 params to the function.

**Comment by thenbrent** [comment]
Thanks for the report @ChristianGiupponi. I've opened a PR on the WooCommerce Subscriptions repository to fix this.

**Comment by ChristianGiupponi** [comment]
Great! Thanks!
