### ISSUE TITLE
problem with login

### ISSUE THREAD

**Issue by mokerosan** [woocommerce/woocommerce#24125]
**Describe the bug**
when i try to login with the [okta plugin](https://github.com/oktadeveloper/okta-wordpress-sign-in-widget) enabled without woocommerce enabled this starts perfectly, but when woocommerce active stops working and sends me an error.

**To Reproduce**
1. first active "[okta-wordpress-sign-in-widget](https://github.com/oktadeveloper/okta-wordpress-sign-in-widget)" and "woocommerce" plugins.
2. then I close session
3. and I will login
```

Error details
==================
An error of type E_ERROR occurred on line 809 of the file

/home/sec/public_html/intranet/wp-content/plugins/woocommerce/includes/wc-user-functions.php. Mensaje de error: Uncaught ArgumentCountError: Too few arguments to function wc_maybe_store_user_agent(), 1 passed in /home/sec/public_html/intranet/wp-includes/class-wp-hook.php on line 286 and exactly 2 expected in /home/sec/public_html/intranet/wp-content/plugins/woocommerce/includes/wc-user-functions.php:809
Stack trace:
#0 /home/sec/public_html/intranet/wp-includes/class-wp-hook.php(286): wc_maybe_store_user_agent('peter')
#1 /home/sec/public_html/intranet/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/sec/public_html/intranet/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/sec/public_html/intranet/wp-content/plugins/okta-wordpress-sign-in-widget-master/okta-widget.php(215): do_action('wp_login', 'peter')
#4 /home/sec/public_html/intranet/wp-content/plugins/okta-wordpress-sign-in-widget-master/okta-widget.php(157): Okta\OktaSignIn->logUserIntoWordPressFromEmail('p.albina@live.c...', NULL)
#5 /home/sec/public_html/intranet/wp-includes/class-wp-hook.php(286): Okta\OktaSignIn->
```

**Screenshots**
![image](https://user-images.githubusercontent.com/31668345/61009551-fa0e8200-a340-11e9-9438-936478da2c65.png)

**Expected behavior**
start session without any problem

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://intranet.demosec.ml
Site address (URL): https://intranet.demosec.ml
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6
PHP Post Max Size: 64 MB
PHP Time Limit: 90
PHP Max Input Vars: 5000
cURL Version: 7.65.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 2.68MB
Tamaño de los datos de la base de datos: 2.29MB
Tamaño del índice de la base de datos: 0.39MB
wp_woocommerce_sessions: Datos: 0.01MB + Índice: 0.00MB
wp_woocommerce_api_keys: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_attribute_taxonomies: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_downloadable_product_permissions: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_order_items: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_order_itemmeta: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_tax_rates: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_tax_rate_locations: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_shipping_zones: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_shipping_zone_locations: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_shipping_zone_methods: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_payment_tokens: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_payment_tokenmeta: Datos: 0.00MB + Índice: 0.00MB
wp_woocommerce_log: Datos: 0.00MB + Índice: 0.00MB
wp_bp_activity: Datos: 0.00MB + Índice: 0.01MB
wp_bp_activity_meta: Datos: 0.00MB + Índice: 0.00MB
wp_bp_groups: Datos: 0.00MB + Índice: 0.00MB
wp_bp_groups_groupmeta: Datos: 0.00MB + Índice: 0.00MB
wp_bp_groups_members: Datos: 0.00MB + Índice: 0.00MB
wp_bp_notifications: Datos: 0.00MB + Índice: 0.00MB
wp_bp_notifications_meta: Datos: 0.00MB + Índice: 0.00MB
wp_bp_xprofile_data: Datos: 0.00MB + Índice: 0.00MB
wp_bp_xprofile_fields: Datos: 0.00MB + Índice: 0.01MB
wp_bp_xprofile_groups: Datos: 0.00MB + Índice: 0.00MB
wp_bp_xprofile_meta: Datos: 0.00MB + Índice: 0.00MB
wp_buddykit_user_files: Datos: 0.00MB + Índice: 0.00MB
wp_commentmeta: Datos: 0.00MB + Índice: 0.00MB
wp_comments: Datos: 0.00MB + Índice: 0.01MB
wp_icl_content_status: Datos: 0.00MB + Índice: 0.00MB
wp_icl_core_status: Datos: 0.00MB + Índice: 0.00MB
wp_icl_flags: Datos: 0.00MB + Índice: 0.00MB
wp_icl_languages: Datos: 0.00MB + Índice: 0.01MB
wp_icl_languages_translations: Datos: 0.10MB + Índice: 0.11MB
wp_icl_locale_map: Datos: 0.00MB + Índice: 0.00MB
wp_icl_message_status: Datos: 0.00MB + Índice: 0.00MB
wp_icl_node: Datos: 0.00MB + Índice: 0.00MB
wp_icl_reminders: Datos: 0.00MB + Índice: 0.00MB
wp_icl_strings: Datos: 0.00MB + Índice: 0.00MB
wp_icl_string_positions: Datos: 0.00MB + Índice: 0.00MB
wp_icl_string_status: Datos: 0.00MB + Índice: 0.00MB
wp_icl_string_translations: Datos: 0.00MB + Índice: 0.00MB
wp_icl_translate: Datos: 0.00MB + Índice: 0.00MB
wp_icl_translate_job: Datos: 0.00MB + Índice: 0.00MB
wp_icl_translations: Datos: 0.01MB + Índice: 0.03MB
wp_icl_translation_batches: Datos: 0.00MB + Índice: 0.00MB
wp_icl_translation_status: Datos: 0.00MB + Índice: 0.00MB
wp_links: Datos: 0.00MB + Índice: 0.00MB
wp_options: Datos: 1.80MB + Índice: 0.04MB
wp_pollsa: Datos: 0.00MB + Índice: 0.00MB
wp_pollsip: Datos: 0.00MB + Índice: 0.00MB
wp_pollsq: Datos: 0.00MB + Índice: 0.00MB
wp_postmeta: Datos: 0.10MB + Índice: 0.07MB
wp_posts: Datos: 0.14MB + Índice: 0.04MB
wp_revslider_css: Datos: 0.09MB + Índice: 0.00MB
wp_revslider_layer_animations: Datos: 0.00MB + Índice: 0.00MB
wp_revslider_navigations: Datos: 0.00MB + Índice: 0.00MB
wp_revslider_sliders: Datos: 0.00MB + Índice: 0.00MB
wp_revslider_slides: Datos: 0.00MB + Índice: 0.00MB
wp_revslider_static_slides: Datos: 0.00MB + Índice: 0.00MB
wp_signups: Datos: 0.00MB + Índice: 0.00MB
wp_task_breaker_comments: Datos: 0.00MB + Índice: 0.00MB
wp_task_breaker_tasks: Datos: 0.00MB + Índice: 0.00MB
wp_task_breaker_tasks_user_assignment: Datos: 0.00MB + Índice: 0.00MB
wp_task_breaker_task_meta: Datos: 0.00MB + Índice: 0.00MB
wp_termmeta: Datos: 0.00MB + Índice: 0.01MB
wp_terms: Datos: 0.01MB + Índice: 0.01MB
wp_term_relationships: Datos: 0.01MB + Índice: 0.01MB
wp_term_taxonomy: Datos: 0.01MB + Índice: 0.01MB
wp_usermeta: Datos: 0.01MB + Índice: 0.01MB
wp_users: Datos: 0.00MB + Índice: 0.01MB
wp_visual_form_builder_entries: Datos: 0.00MB + Índice: 0.00MB
wp_visual_form_builder_fields: Datos: 0.00MB + Índice: 0.00MB
wp_visual_form_builder_forms: Datos: 0.00MB + Índice: 0.00MB
wp_wc_admin_notes: Datos: 0.00MB + Índice: 0.00MB
wp_wc_admin_note_actions: Datos: 0.00MB + Índice: 0.00MB
wp_wc_customer_lookup: Datos: 0.00MB + Índice: 0.00MB
wp_wc_download_log: Datos: 0.00MB + Índice: 0.00MB
wp_wc_order_coupon_lookup: Datos: 0.00MB + Índice: 0.00MB
wp_wc_order_product_lookup: Datos: 0.00MB + Índice: 0.00MB
wp_wc_order_stats: Datos: 0.00MB + Índice: 0.00MB
wp_wc_order_tax_lookup: Datos: 0.00MB + Índice: 0.00MB
wp_wc_product_meta_lookup: Datos: 0.00MB + Índice: 0.00MB
wp_wc_webhooks: Datos: 0.00MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 2
bp-email: 47
bp_doc: 1
bp_docs_folder: 9
buddydrive-file: 5
buddydrive-folder: 1
customize_changeset: 6
dsc-knowledgebase: 7
forum: 3
nav_menu_item: 63
page: 43
post: 7
product: 23
product_variation: 4
project: 4
reply: 1
revision: 2
scheduled-action: 11
topic: 1
tribe_events: 3
tribe_organizer: 1
tribe_venue: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

bbPress: por La comunidad bbPress – 2.5.14
BuddyDrive: por mrpritchett – 2.1.1
BuddyKit: por Dunhakdis
Joseph G. – 0.0.3

Documentos BuddyPress: por Boone B Gorges
David Cavins – 2.1.2

Buddypress: por La Comunidad de BuddyPress – 4.3.0
Gears: por Dunhakdis – 4.2.1
WPBakery Page Builder: por Michael M - WPBakery.com – 6.0.3
Kirki Customizer Framework: por Ari Stathopoulos (@aristath) – 3.0.44
Nifty Menu Options: por Dunhakdis – 1.0.1
Okta Sign-In Widget: por Aaron Parecki
Tom Smith
Nico Triballier
Joël Franusic – 0.11.0

Reference Knowledgebase and Docs: por Dunhakdis – 1.0.4
Slider Revolution: por ThemePunch – 5.4.8.3
Subway: por Dunhakdis – 2.1.3
TaskBreaker - Group Project Management: por Dunhakdis – 1.5.1
The Events Calendar: por Modern Tribe
Inc. – 4.9.4

Visual Form Builder: por Matthew Muro – 3.0.1
WooCommerce: por Automattic – 3.6.5
WP-Polls: por Lester 'GaMerZ' Chan – 2.75.2

### Inactive Plugins (4) ###

Akismet Anti-Spam: por Automattic – 4.1.2
Hello Dolly: por Matt Mullenweg – 1.7.2
WooCommerce Admin: por WooCommerce – 0.14.0 – No probado con la versión activa de WooCommerce
WPML Multilingual CMS: por OnTheGoSystems – 4.2.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: CLP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #27 - /tienda/
Carrito: #28 - /carrito/
Finalizar compra: #29 - /finalizar-compra/
Mi cuenta: #30 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Thrive Nouveau
Version: 3.1.2
Author URL: http://themeforest.net/user/dunhakdis
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Archive Template: Tu tema tiene un archivo woocommerce.php
no podrás sobreescribir la plantilla personalizada woocommerce/archive-product.php ya que woocommerce.php tiene prioridad sobre archive-product.php. Esto es intencionado para prevenir problemas de visualización.

Overrides: –

### Action Scheduler ###

Complete: 10
Oldest: 2019-07-08 04:49:18 +0000
Newest: 2019-07-10 20:57:03 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 1
Oldest: 2019-07-10 21:57:03 +0000
Newest: 2019-07-10 21:57:03 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by malviyaritesh** [comment]
From the error details you provided, I can see that the problem lies in [okta plugin](https://github.com/oktadeveloper/okta-wordpress-sign-in-widget).
You've created similar issue there also. I've created a PR oktadeveloper/okta-wordpress-sign-in-widget#12 there which should fix this.

**Comment by mokerosan** [comment]
thank you very much **malviyaritesh**  this has solved my problem!

**Comment by claudiosanches** [comment]
Closing since the problem comes from a 3rd party plugin and there's already a PR to fix it.
@malviyaritesh thanks for let us know about it.
