### ISSUE TITLE
Error when creating order: Called member function date() on null

### ISSUE THREAD

**Issue by Foxite** [woocommerce/woocommerce#24416]
**Describe the bug**
I tried to create a test order in the admin page using my own account as the customer. When setting the customer account, my billing info is loaded but no shipping info is loaded (see note below). After adding a product and clicking "create", I get an error message "The site is experiencing technical difficulties" with no further information. This is added to the PHP error log:

```
PHP Fatal error: Uncaught Error:
Call to a member function date() on null in [REDACTED]/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php:
Stack trace:
#0 [REDACTED]/wp-includes/class-wp-hook.php(288): WC_Orders_Tracking->track_created_date_change(2968)
#1 [REDACTED]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 [REDACTED]/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 [REDACTED]/wp-includes/post.php(3727): do_action('pre_post_update', 2968, Array)
#4 [REDACTED]/wp-includes/post.php(4028): wp_insert_post(Array, false)
#5 [REDACTED]/wp-admin/includes/post.php(405): wp_update_post(Array)
#6 [REDACTED]/wp-admin/post.php(218): edit_post()
#7 {main}
  thrown in [REDACTED]/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php on line 81, referer: [REDACTED]/wp-admin/post-new.php?post_type=shop_order
```
I have redacted my site address.

I could provide some data about my account, if it is necessary to reproduce this bug. I noticed that the billing information is filled, but the shipping information is not. When I fill in the shipping info using the copy button, this **does not** happen.

**To Reproduce**
1. Have an account that can create orders in the backend, which does not have shipping info, but does have billing info.
2. Using that account, go to the Orders page and create a new order.
3. Add a product, set your own account as the customer.
4. Click the Create Order button

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. (I have **not** done this, since I don't have any sort of test environment to do it. I could try this during off hours, but it'll have to wait some time)
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above. (I'm not sure if this can be reproduced on any other installation using these steps, but they reliably reproduce it on mine.) 

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): [REDACTED]
Site address (URL): [REDACTED]
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6-1+0~20190531112735.39+stretch~1.gbp6131b7
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.12-MariaDB-log
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
Totale databasegrootte: 8.18MB
Database datagrootte: 5.75MB
Database index grootte: 2.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.31MB + Index: 0.44MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.06MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 1.22MB + Index: 0.50MB + Engine InnoDB
wp_posts: Data: 1.16MB + Index: 0.38MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Codefragmenten: door Shea Bunge – 2.13.3
Custom Product Stickers voor Woocommerce: door starblank.com – 1.9.0 – Niet getest met de actieve versie van WooCommerce
Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 7.7.1
Jetpack door WordPress.com: door Automattic – 7.6
Really Simple SSL: door Rogier Lankhorst
Mark Wolters – 3.2.3

WooCommerce Sisow Betaal Opties: door Sisow – 5.2.11 – Niet getest met de actieve versie van WooCommerce
Page Builder by SiteOrigin: door SiteOrigin – 2.10.6
Checkout Field Editor for WooCommerce: door ThemeHiGH – 1.3.5
WooCommerce Blocks: door Automattic – 2.3.0
Advanced Order Export For WooCommerce: door AlgolPlus – 3.0.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Admin: door WooCommerce – 0.17.0
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.3.1
WooCommerce Services: door Automattic – 1.21.1
WooCommerce: door Automattic – 3.7.0

### Inactive Plugins (9) ###

Akismet Anti-Spam: door Automattic – 4.1.2
Complianz | GDPR Cookie Consent: door RogierLankhorst
complianz – 3.0.9

JSON API: door Dan Phiffer – 1.1.1
JSON Content Importer: door Bernhard Kux – 1.3.4
Mailchimp for WooCommerce: door Mailchimp – 2.1.17 – Niet getest met de actieve versie van WooCommerce
Mailchimp for WordPress: door ibericode – 4.5.3
Perfect WooCommerce Brands: door Alberto de Vera Sevilla – 1.7.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce PayPal Checkout Gateway: door WooCommerce – 1.6.17
Yoast SEO: door Team Yoast – 11.8 – Niet getest met de actieve versie van WooCommerce

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #21 - /
Winkelmand: #22 - /winkelmand/
Afrekenen: #23 - /afrekenen/
Mijn account: #24 - /mijn-account/
Algemene voorwaarden: #533 - /over-ons/

### Theme ###

Name: Storefront
Version: 2.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 910
Oldest: 2019-07-16 15:31:39 +0000
Newest: 2019-08-16 14:53:47 +0000

Pending: 1
Oldest: 2019-08-16 15:48:39 +0000
Newest: 2019-08-16 15:48:39 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 14
Oldest: 2019-06-02 14:04:35 +0000
Newest: 2019-06-13 15:33:58 +0000

`
```
</details>

**Comment by Foxite** [comment]
Additionally, executing the reproduction steps creates a broken draft order that cannot be changed in any way, as attempting to do so will cause the same "technical problems" message. The error log message appears to be the same:

<details>
```
PHP Fatal error:
Uncaught Error:
Call to a member function date() on null in [REDACTED]/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php:81
Stack trace:
#0 [REDACTED]/wp-includes/class-wp-hook.php(288): WC_Orders_Tracking->track_created_date_change(3028)
#1 [REDACTED]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 [REDACTED]/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 [REDACTED]/wp-includes/post.php(3727): do_action('pre_post_update', 3028, Array)
#4 [REDACTED]/wp-includes/post.php(4028): wp_insert_post(Array, false)
#5 [REDACTED]/wp-includes/post.php(2988): wp_update_post(Array)
#6 [REDACTED]/wp-admin/edit.php(118): wp_trash_post(3028)
#7 {main}
  thrown in [REDACTED]/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php on line 81, referer: [REDACTED]/wp-admin/edit.php?post_status=draft&post_type=shop_order
```
</details>

**Comment by NiftyMaker** [comment]
Having the same problem while trying to create an order from the backend. When I add the product and click on Recalculate the loading circle loops forever and never refreshes de total amount. And if I click on create order, it shows this:

**Fatal Error**
    Line 81
    Message Uncaught Error: Call to a member function date() on null in [REDACTED]/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php:81 Stack trace: #0 [REDACTED]/wp-includes/class-wp-hook.php(288):  WC_Orders_Tracking->track_created_date_change(9942) 
    #1 [REDACTED]/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) 
    #2 [REDACTED]/wp-includes/plugin.php(465): WP_Hook->do_action(Array) 
    #3 [REDACTED]/wp-includes/post.php(3727): do_action('pre_post_update', 9942, Array) 
    #4 [REDACTED]/wp-includes/post.php(4028): wp_insert_post(Array, false) 
    #5 [REDACTED]/wp-admin/includes/post.php(405): wp_update_post(Array) 
    #6 [REDACTED]/wp-admin/post.php(218): edit_post() 
    #7 {main} thrown     
    File [REDACTED]/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php

However, nothing was logged on woocomerce debuging log.

I'm running Wordpress 5.1.1 and Woocommerce 3.7.0

**Comment by NiftyMaker** [comment]
Also, if I try to delete the broken drafts, it causes the same fatal error.

**Fatal Error**
`Line 81
Message Uncaught Error: Call to a member function date() on null in /home2/restaur6/public_html/underfree.mx/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php:81 Stack trace: #0 /home2/restaur6/public_html/underfree.mx/wp-includes/class-wp-hook.php(288): WC_Orders_Tracking->track_created_date_change(9942) #1 /home2/restaur6/public_html/underfree.mx/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /home2/restaur6/public_html/underfree.mx/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #3 /home2/restaur6/public_html/underfree.mx/wp-includes/post.php(3727): do_action('pre_post_update', 9942, Array) #4 /home2/restaur6/public_html/underfree.mx/wp-includes/post.php(4028): wp_insert_post(Array, false) #5 /home2/restaur6/public_html/underfree.mx/wp-includes/post.php(2988): wp_update_post(Array) #6 /home2/restaur6/public_html/underfree.mx/wp-admin/edit.php(118): wp_trash_post(9942) #7 {main} thrown
File /home2/restaur6/public_html/underfree.mx/wp-content/plugins/woocommerce/includes/tracks/events/class-wc-orders-tracking.php`

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24441.
