### ISSUE TITLE
WC_REST_Coupons_V1_Controller

### ISSUE THREAD

**Issue by Lewiscowles1986** [woocommerce/woocommerce#24985]
**Describe the bug**

This is apparently from WordPress, it may be a phishing scam as it's for a test demo site (latest WooCommerce & WordPress) on shared hosting, so there is no log aggregation etc

<details>
<summary>From an automated email</summary>

```
To keep your site safe, this link will expire in 1 day. Don't worry about that, though: a new link will be emailed to you if the error occurs again after it expires.



Error Details
=============
An error of type E_ERROR was caused in line 360 of the file /####/public/wp-content/plugins/woocommerce/includes/class-wc-api.php. Error message: Uncaught Error: Class 'WC_REST_Coupons_V1_Controller' not found in /####/public/wp-content/plugins/woocommerce/includes/class-wc-api.php:360
Stack trace:
#0 /####/public/wp-includes/class-wp-hook.php(286): WC_API->register_rest_routes(Object(WP_REST_Server))
#1 /####/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /####/public/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /####/public/wp-includes/rest-api.php(475): do_action('rest_api_init', Object(WP_REST_Server))
#4 /####/public/wp-includes/rest-api.php(433): rest_get_server()
#5 /####/public/wp-includes/rest-api.php(1396): rest_do_request(Object(WP_REST_Request))
#6 [internal function]: rest_preload_api_request(Array, '/wc/v3')
#7 /####/public/
```

</details>

**To Reproduce**

Latest WordPress, latest plugins including WooCommerce

**Screenshots**

N/A

**Expected behavior**

Not getting this email

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). (StoreFront in my case)
- [?] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): ####
Site address (URL): ####
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.22
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.25-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: cd2_dh_
MaxMind GeoIP Database: ✔
Total Database Size: 22.73MB
Database Data Size: 13.30MB
Database Index Size: 9.43MB
cd2_dh_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
cd2_dh_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
appts: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_cf_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_cf_form_entries: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
cd2_dh_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_cf_pdf_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_cf_pro_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_cf_tracking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_cf_tracking_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
cd2_dh_cpm_file_relationship: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_cpm_project_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_cpm_tasks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_cpm_user_role: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_kanban_boards: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_kanban_estimates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_kanban_log_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_kanban_log_status_changes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_kanban_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_kanban_projects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_kanban_statuses: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_kanban_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_kanban_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_kanban_task_hours: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_options: Data: 2.02MB + Index: 0.09MB + Engine InnoDB
cd2_dh_postmeta: Data: 3.02MB + Index: 0.11MB + Engine InnoDB
cd2_dh_posts: Data: 6.52MB + Index: 7.58MB + Engine InnoDB
cd2_dh_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_usermeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_vtwpr_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_vtwpr_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_vtwpr_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cd2_dh_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
cd2_dh_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
cd2_dh_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
cd2_dh_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
cd2_dh_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cd2_dh_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_hook_log: Data: 0.45MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

Admin Columns Pro - Advanced Custom Fields (ACF): by Admin Columns – 2.5.3
Admin Columns Pro - WooCommerce: by Admin Columns – 3.3.4 – Not tested with the active version of WooCommerce
ACF to REST API: by Aires Gonçalves – 3.1.0
Admin Columns Pro: by AdminColumns.com – 4.6.3
Advanced Custom Fields PRO: by Elliot Condon – 5.8.6
Advanced Custom Fields: by Elliot Condon – 5.8.6
CD2 FullStory Integration: by CD2 Team – 1.05
CD2 Gutenberg Shortcode Preview Block: by Lewis Cowles – 1.0.5
CODESIGN2 Content Section Plugin Same-site oEmbed: by CODESIGN2 – 0.0.1
CODESIGN2 Content Section Plugin: by CODESIGN2 – 2.6.4
CODESIGN2 Media Taxonomy Modifications: by CODESIGN2 – 1.3.6
Enable SVG Uploads: by Lewis Cowles – 2.0.1
Enhanced Media Library: by wpUXsolutions – 2.7.2
Media Playback Speed Highlight: by Lewis Cowles – 1.0.0
Media Playback Speed: by LewisCowles – 1.0.3
Webmention: by Matthias Pfefferle – 4.0.0
WooCommerce Blocks: by Automattic – 2.4.4
WooCommerce Admin: by WooCommerce – 0.21.0
WooCommerce: by Automattic – 3.7.1 – 3.8.0 is available

### Inactive Plugins (0) ###

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /basket/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 50
Oldest: 2019-10-08 09:36:52 +0100
Newest: 2019-11-05 23:24:19 +0000

Pending: 1
Oldest: 2019-11-06 00:24:19 +0000
Newest: 2019-11-06 00:24:19 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by Lewiscowles1986** [comment]
I believe this might have been an issue with the mechanism to send out these emails. Not only has the version number since increased, I've had no further warnings
