### ISSUE TITLE
grunt e2e-tests error: Chrome version must be between 71 and 75

### ISSUE THREAD

**Issue by 4selin** [woocommerce/woocommerce#25147]
**Describe the bug**
`grunt e2e-tests` throws errors on every test:
" SessionNotCreatedError: session not created: Chrome version must be between 71 and 75                                (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)      "

**To Reproduce**
1. git clone woocommerce fork
2. go through these [steps ](https://github.com/woocommerce/woocommerce/wiki/End-to-end-Testing#getting-started)

**Expected behavior**
pass test

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://one.wordpress.test
Site address (URL): http://one.wordpress.test
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.6
PHP Version: 7.2.25-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.20-MariaDB-1:10.3.20+maria~bionic
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.36MB
Database Data Size: 2.32MB
Database Index Size: 1.04MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.0-dev

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 61
Oldest: 2019-11-30 13:15:02 +0000
Newest: 2019-11-30 13:18:17 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by 4selin** [comment]
`grunt e2e-test --file="front-end/single-product.js"`

Command Prompt Output:
<details>
Running "shell:e2e_test" (shell) task


  Single Product Page
    1) "before all" hook: ret for "should be able to add simple products to the cart"
    2) "after all" hook: ret for "should be able to add variation products to the cart"


  0 passing (1s)
  2 failing

  1) Single Product Page
       "before all" hook: ret for "should be able to add simple products to the cart":
     SessionNotCreatedError: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)
      at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
      at doSend.then.response (node_modules\selenium-webdriver\lib\http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules\selenium-webdriver\lib\webdriver.js:769:24)
      at Function.createSession (node_modules\selenium-webdriver\chrome.js:761:15)
      at createDriver (node_modules\selenium-webdriver\index.js:170:33)
      at Builder.build (node_modules\selenium-webdriver\index.js:642:16)
      at Manager.buildChromeDriver (node_modules\wp-e2e-webdriver\lib\manager.js:186:88)
      at Manager.setupDriver (node_modules\wp-e2e-webdriver\lib\manager.js:123:26)
      at new Manager (node_modules\wp-e2e-webdriver\lib\manager.js:92:8)
      at Context.<anonymous> (E:/vagrant-local/www/wordpress-one/public_html/wp-content/plugins/woocommerce/tests/e2e-tests/front-end/single-product.js:30:13)
      at runTest (node_modules\selenium-webdriver\testing\index.js:163:22)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\selenium-webdriver\testing\index.js:184:16
      at new ManagedPromise (node_modules\selenium-webdriver\lib\promise.js:1077:7)
      at controlFlowExecute (node_modules\selenium-webdriver\testing\index.js:183:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2974:25)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\selenium-webdriver\lib\promise.js:668:7
  From: Task: Single Product Page "before all" hook: ret
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:182:10)
  From: Task: WebDriver.quit()
      at thenableWebDriverProxy.schedule (node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at thenableWebDriverProxy.quit (node_modules\selenium-webdriver\lib\webdriver.js:840:23)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\wp-e2e-webdriver\lib\manager.js:332:19
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2927:27)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\selenium-webdriver\lib\promise.js:668:7
  From: Task: Single Product Page "after all" hook: ret
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:182:10)

  2) Single Product Page
       "after all" hook: ret for "should be able to add variation products to the cart":
     SessionNotCreatedError: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)
      at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
      at doSend.then.response (node_modules\selenium-webdriver\lib\http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules\selenium-webdriver\lib\webdriver.js:769:24)
      at Function.createSession (node_modules\selenium-webdriver\chrome.js:761:15)
      at createDriver (node_modules\selenium-webdriver\index.js:170:33)
      at Builder.build (node_modules\selenium-webdriver\index.js:642:16)
      at Manager.buildChromeDriver (node_modules\wp-e2e-webdriver\lib\manager.js:186:88)
      at Manager.setupDriver (node_modules\wp-e2e-webdriver\lib\manager.js:123:26)
      at new Manager (node_modules\wp-e2e-webdriver\lib\manager.js:92:8)
      at Context.<anonymous> (E:/vagrant-local/www/wordpress-one/public_html/wp-content/plugins/woocommerce/tests/e2e-tests/front-end/single-product.js:30:13)
      at runTest (node_modules\selenium-webdriver\testing\index.js:163:22)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\selenium-webdriver\testing\index.js:184:16
      at new ManagedPromise (node_modules\selenium-webdriver\lib\promise.js:1077:7)
      at controlFlowExecute (node_modules\selenium-webdriver\testing\index.js:183:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2974:25)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\selenium-webdriver\lib\promise.js:668:7
  From: Task: Single Product Page "before all" hook: ret
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:182:10)
  From: Task: WebDriver.quit()
      at thenableWebDriverProxy.schedule (node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at thenableWebDriverProxy.quit (node_modules\selenium-webdriver\lib\webdriver.js:840:23)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\wp-e2e-webdriver\lib\manager.js:332:19
      at ManagedPromise.invokeCallback_ (node_modules\selenium-webdriver\lib\promise.js:1376:14)
      at TaskQueue.execute_ (node_modules\selenium-webdriver\lib\promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules\selenium-webdriver\lib\promise.js:3067:27)
      at asyncRun (node_modules\selenium-webdriver\lib\promise.js:2927:27)
      at E:\vagrant-local\www\wordpress-one\public_html\wp-content\plugins\woocommerce\node_modules\selenium-webdriver\lib\promise.js:668:7
  From: Task: Single Product Page "after all" hook: ret
      at Context.ret (node_modules\selenium-webdriver\testing\index.js:182:10)



Warning: Command failed: npm run --silent test:single tests/e2e-tests/front-end/single-product.js
 Use --force to continue.

Aborted due to warnings.
</details>

**Comment by juliaamosova** [comment]
Thanks for raising the issue @4selin. We are in the process of migrating the existing E2E test suite from Selenium Webdriver to Puppeteer: https://github.com/woocommerce/woocommerce/pull/24218. The work on the migration is about to be completed which is the reason why we are no longer working on addressing the existing e2e test issues. 

With the above in mind, I am going to mark this issue as `won't fix`. Please be on the lookout for a new e2e test suite before the end of the year.
