### ISSUE TITLE
Uncaught error in WC_Privacy::delete_inactive_accounts_query

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#25338]
**Describe the bug**
While running the job to remove inactive accounts, the following exception will be thrown:

Uncaught Error: Call to undefined function wp_delete_user() in /www/eval.firewoodshop.ch/wp-content/plugins/woocommerce/includes/class-wc-privacy.php:344 Stack trace: #0 /www/eval.firewoodshop.ch/wp-content/plugins/woocommerce/includes/class-wc-privacy.php(303): WC_Privacy::delete_inactive_accounts_query(1577495079, 20) #1 /www/eval.firewoodshop.ch/wp-content/plugins/woocommerce/includes/class-wc-privacy-background-process.php(59): WC_Privacy::delete_inactive_accounts(20) #2 /www/eval.firewoodshop.ch/wp-content/plugins/woocommerce/includes/abstracts/class-wc-background-process.php(102): WC_Privacy_Background_Process->task(Array) #3 /www/eval.firewoodshop.ch/wp-content/plugins/woocommerce/includes/libraries/wp-background-process.php(447): WC_Background_Process->handle() #4 /www/eval.firewoodshop.ch/wp-includes/class-wp-hook.php(288): WP_Background_Process->handle_cron_healthcheck() #5 /www/eval.firewoodshop.ch/wp- in /www/eval.firewoodshop.ch/wp-content/plugins/woocommerce/includes/class-wc-privacy.php on line 344  

**To Reproduce**
1. Use an existing database or create a condition with a user account that will be removed because of the `Retain inactive accounts` setting value. 
2. Wait until the background job is executed.
3. Check the error log.

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://eval.firewoodshop.ch
Site address (URL): https://eval.firewoodshop.ch
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.24
PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.43-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: xyz_
Total Database Size: 3.42MB
Database Data Size: 2.02MB
Database Index Size: 1.40MB
xyz_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
xyz_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
xyz_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
xyz_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xyz_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
xyz_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xyz_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_comments: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
xyz_jckwds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xyz_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_options: Data: 1.05MB + Index: 0.06MB + Engine InnoDB
xyz_postmeta: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
xyz_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
xyz_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
xyz_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xyz_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xyz_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
xyz_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
xyz_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
xyz_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
xyz_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
xyz_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
xyz_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Admin: by WooCommerce – 0.23.3
WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CHF (CHF)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /warenkorb/
Checkout: #7 - /kasse/
My account: #8 - /mein-konto/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 59
Oldest: 2019-12-03 14:11:29 +0100
Newest: 2019-12-29 15:41:23 +0100

Pending: 1
Oldest: 2019-12-29 16:41:23 +0100
Newest: 2019-12-29 16:41:23 +0100

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25489.
