### ISSUE TITLE
Problem with only one of many similar coupon codes

### ISSUE THREAD

**Issue by robwatson-intechra** [woocommerce/woocommerce#25346]
**Describe the bug**
We think we found a bug in some legacy includes of WooCommerce core code that is related to the use of coupons. This morning when I logged into my hosting dashboard after vacation, I noticed the following error:

Uncaught Exception: Invalid coupon. in 
/wp-content/plugins/woocommerce/includes/data-stores/class-wc-coupon-data-store-cpt.php:108
Stack trace:
#0 /wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Coupon_Data_Store_CPT->read(Object(WC_Coupon))
#1 /wp-content/plugins/woocommerce/includes/class-wc-coupon.php(129): WC_Data_Store->read(Object(WC_Coupon))
#2 /wp-content/plugins/woocommerce/includes/class-wc-coupon.php(117): WC_Coupon->read_object_from_database()
#3 /wp-content/plugins/woocommerce/includes/class-wc-cart.php(1581): WC_Coupon->__construct('**newdecade2020**')
#4 /wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-cart.php(267): WC_Cart->apply_co

I tried applying the coupon NEWDECADE2020 and the progress icon kept spinning without timing out. I deleted and re-created that coupon, but same result. I tested the other coupons we have and they all worked fine. Then I removed the last "20" from the end of the coupon code, to make it NEWDECADE20, and it worked. All other coupons that have "2020" in them, either at the beginning or the end, worked just fine. This one did not. I walked through the stack trace in the PHP code and couldn't find a reason for this one weird exception.

What it ended up being was that Redis was caching "something", whether it was old plugin code or a database entry that no longer matched with a new feature. Either way, once we cleared Redis, the problem was resolved. So, I'm wondering if there is something inherent to the way the coupons code works that might be affected by how Redis maintains its cache.

**To Reproduce**
Could not reproduce the behavior on any other test or dev system. It was fixed on live only after Redis cache was cleared, which was what made it so maddening.

**Screenshots**
https://snipboard.io/LFTnop.jpg

https://snipboard.io/mrAQI8.jpg

https://snipboard.io/jw2dXz.jpg

https://snipboard.io/3IrFyf.jpg

**Expected behavior**
Expected the coupon code to work just like the others did. It had been previously set up, like all the others, with the same naming scheme. While the others containing "2020" in them all worked, only NEWDECADE2020 didn't. Removing the last "20" in the coupon code name resulted in a working code. It was oddly-specific behavior with just one code.

**Isolating the problem (mark completed items with an [x]):**

**(Didn't even get to these steps. Redis cache clearing fixed the issue.)**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. 
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://www.intechrahealth.com
Site address (URL): https://www.intechrahealth.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.8.1
PHP Version: 7.2.25
PHP Post Max Size: 100 MB
PHP Time Limit: 6000
PHP Max Input Vars: 10000
cURL Version: 7.40.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.23-MariaDB-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: intechra_
MaxMind GeoIP Database: ✔
Total Database Size: 1554.64MB
Database Data Size: 1055.44MB
Database Index Size: 499.20MB
intechra_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
intechra_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_woocommerce_order_items: Data: 5.52MB + Index: 1.52MB + Engine InnoDB
intechra_woocommerce_order_itemmeta: Data: 20.55MB + Index: 18.03MB + Engine InnoDB
intechra_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
intechra_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_abandoned_cart_aelia_currency: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ac_abandoned_cart_history: Data: 19.55MB + Index: 0.00MB + Engine InnoDB
intechra_ac_abandoned_cart_history_lite: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
intechra_ac_email_templates: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
intechra_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ac_guest_abandoned_cart_history: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
intechra_ac_guest_abandoned_cart_history_lite: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
intechra_ac_link_clicked_email: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
intechra_ac_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ac_notifications_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ac_opened_emails: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
intechra_ac_sent_history: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
intechra_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ac_tiny_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_amazon_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_btg: Data: 0.33MB + Index: 0.25MB + Engine InnoDB
intechra_amazon_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_amazon_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_feed_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_feed_tpl_data: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
intechra_amazon_feed_tpl_values: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_amazon_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_listings: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
intechra_amazon_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_amazon_markets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_orders: Data: 2.52MB + Index: 0.05MB + Engine InnoDB
intechra_amazon_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_reports: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_shipping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_amazon_stock_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_cart_abandonment: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
intechra_commentmeta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
intechra_comments: Data: 43.58MB + Index: 32.05MB + Engine InnoDB
intechra_csvexport_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
intechra_duplicator_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_ebay_accounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_auctions: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
intechra_ebay_categories: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
intechra_ebay_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_ebay_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_orders: Data: 16.52MB + Index: 0.06MB + Engine InnoDB
intechra_ebay_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_profiles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_shipping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_sites: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
intechra_ebay_store_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_ebay_transactions: Data: 16.52MB + Index: 0.09MB + Engine InnoDB
intechra_et_bloom_stats: Data: 74.59MB + Index: 0.00MB + Engine InnoDB
intechra_et_divi_ab_testing_clients: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_et_divi_ab_testing_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_exportsreports_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_exportsreports_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_exportsreports_reports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_ic_order_audit_log: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
intechra_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
intechra_itsec_log: Data: 19.52MB + Index: 0.38MB + Engine InnoDB
intechra_itsec_logs: Data: 8.52MB + Index: 0.33MB + Engine InnoDB
intechra_itsec_temp: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
intechra_iwp_backup_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_archive_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_attributes_table: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_jet_catgory_attribute: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_jet_cron_inventory: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_errorfile_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_file_info: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
intechra_jet_order_detail: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
intechra_jet_order_import_error: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_profile_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_refund_detail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_return_detail: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_settlement_report: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_jet_shipping_exception: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_mailchimp_carts: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
intechra_mailchimp_jobs: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
intechra_mail_bank: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_mail_bank_email_logs: Data: 136.55MB + Index: 0.22MB + Engine InnoDB
intechra_mail_bank_logs: Data: 161.58MB + Index: 0.00MB + Engine InnoDB
intechra_mail_bank_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_options: Data: 7.47MB + Index: 1.86MB + Engine InnoDB
intechra_pantheon_sessions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
intechra_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_postmeta: Data: 275.86MB + Index: 316.67MB + Engine InnoDB
intechra_posts: Data: 82.44MB + Index: 50.05MB + Engine InnoDB
intechra_promo_code: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
intechra_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_redirection_404: Data: 3.02MB + Index: 4.41MB + Engine InnoDB
intechra_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_redirection_items: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
intechra_redirection_logs: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
intechra_sfauthcats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sfauths: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sfdefpermissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_sferrorlog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sfforums: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_sfgroups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sflog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_sflogmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sfmembers: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
intechra_sfmemberships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_sfmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_sfnotices: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sfoptions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_sfpermissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_sfposts: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
intechra_sfroles: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sftopics: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
intechra_sftrack: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_sfusergroups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_sfwaiting: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_shareasale_wc_tracker_datafeeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_shareasale_wc_tracker_logs: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
intechra_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_term_relationships: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
intechra_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_usermeta: Data: 58.63MB + Index: 44.11MB + Engine InnoDB
intechra_useronline: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_userPaymentDone: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
intechra_users: Data: 3.52MB + Index: 4.55MB + Engine InnoDB
intechra_usertrack: Data: 30.56MB + Index: 0.00MB + Engine InnoDB
intechra_w3tc_cdn_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wc_customer_lookup: Data: 4.52MB + Index: 5.03MB + Engine InnoDB
intechra_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
intechra_wc_order_product_lookup: Data: 4.50MB + Index: 6.05MB + Engine InnoDB
intechra_wc_order_stats: Data: 3.50MB + Index: 3.53MB + Engine InnoDB
intechra_wc_order_tax_lookup: Data: 0.36MB + Index: 0.31MB + Engine InnoDB
intechra_wc_product_meta_lookup: Data: 3.03MB + Index: 3.61MB + Engine InnoDB
intechra_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wfBadLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfBlocks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfConfig: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
intechra_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfFileMods: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
intechra_wfHits: Data: 0.39MB + Index: 0.19MB + Engine InnoDB
intechra_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wfIssues: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
intechra_wfKnownFileList: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
intechra_wfLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfLockedOut: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfLogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
intechra_wfNet404s: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfPendingIssues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
intechra_wfStatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
intechra_wfThrottleLog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_wfVulnScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
intechra_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
intechra_yoast_seo_meta: Data: 23.25MB + Index: 0.00MB + Engine InnoDB
intechra_zendesk_woo_auto_create_ticket: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_zendesk_woo_custom_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_zendesk_woo_log_user: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_zendesk_woo_user_mapping: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
intechra_zendesk_woo_webhook_db: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
_pantheon_heartbeat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Advanced Cron Manager: by BracketSpace – 2.3.9
Advanced Custom Fields PRO: by Elliot Condon – 5.8.7
Bloom: by Elegant Themes – 1.3.10
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: by SeedProd – 5.1.0
Contact Form 7: by Takayuki Miyoshi – 5.1.6
Woo Layout Injector: by Sean Barton - Tortoise IT – 4.7 – Not tested with the active version of WooCommerce
imPower Health Calculator: by imPower – 1.0
Jilt for WooCommerce: by Jilt – 1.7.1
LH HSTS: by Peter Shaw – 1.25
Mailchimp for WooCommerce: by Mailchimp – 2.3 – Not tested with the active version of WooCommerce
Manage Notification E-mails: by Virgial Berveling – 1.5.0
Pantheon Advanced Page Cache: by Pantheon – 0.3.1
Redirection: by John Godley – 4.5.1
ShareASale WooCommerce Tracker: by ShareASale.com
Inc. – 1.4.3

Two Factor: by Plugin Contributors – 0.4.7
USPS WooCommerce Shipping and Handling: by Xadapter – 4.0.7 – Not tested with the active version of WooCommerce
Aelia - Custom free gifts: by Aelia – 1.0.2.191213
WooCommerce Admin: by WooCommerce – 0.22.0
WooCommerce AvaTax: by SkyVerge – 1.9.0
Woocommerce Checkout Terms Conditions Popup: by WC Marketplace
The Grey Parrots – 1.1.9.3 – Not tested with the active version of WooCommerce

WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.15 – Not tested with the active version of WooCommerce
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.1.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.15
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 1.5.4 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.9.4 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 4.5.2
WooCommerce Tab Manager: by SkyVerge – 1.11.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping and Handling: by WooCommerce – 3.0.18
WooCommerce: by Automattic – 3.8.1
Yoast SEO: by Team Yoast – 12.7.1
WP Mail SMTP Plugin by Mail Bank: by Tech Banker – 4.0.10
WP Redis: by Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 0.7.1

WP Rocket | Disable Page Caching: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.4.2.1
Yotpo Social Reviews for Woocommerce: by Yotpo – 1.1.8 – Not tested with the active version of WooCommerce

### Inactive Plugins (8) ###

Asset CleanUp: Page Speed Booster: by Gabriel Livan – 1.3.5.2
Child Theme Configurator: by Lilaea Media – 2.5.0
Disable XML-RPC Pingback: by Samuel Aguilera – 1.2.1
IntechraHealth Commerce Tracking: by  – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.2
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.5
WordPress Importer: by wordpressdotorg – 0.6.4
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.15


### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (5) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –
MU WP Native PHP Sessions: by Pantheon – 0.1
Pantheon: by Pantheon – 0.1
stagingpilot.php: by  –
Support Git Mode Debug Logging: by  –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #152 - /products/
Cart: ❌ Page does not contain the shortcode.
Checkout: #198441 - /checkout/
My account: #198442 - /my-account/
Terms and conditions: #40 - /terms-conditions/

### Theme ###

Name: Divi Child
Version: 3.0.55.191219
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.0.6
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/checkout/thankyou.php

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Brand: Defaults to "Intechra Health".
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: 
Google Product Category: 
Size system: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No

### Jilt ###

Plugin Version: 1.7.1
Jilt API Version: v2
Jilt API Authentication Method: OAuth
Jilt API Connected: ✔
Linked to Jilt: ✔
Enabled: ✔
WooCommerce API: ✔

### Jilt ###

Plugin Version: 1.7.1
Jilt API Version: v2
Jilt API Authentication Method: OAuth
Jilt API Connected: ✔
Linked to Jilt: ✔
Enabled: ✔
WooCommerce API: ✔

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
Webhooks Enabled: ❌
						No signature key configured

### Action Scheduler ###

Complete: 3,937
Oldest: 2019-12-02 07:05:28 -0800
Newest: 2020-01-02 07:01:55 -0800

Pending: 14
Oldest: 2020-01-02 07:02:03 -0800
Newest: 2020-01-09 04:01:55 -0800

Canceled: 24
Oldest: 2020-01-01 11:27:32 -0800
Newest: 2020-01-02 07:22:05 -0800

In-progress: 0
Oldest: –
Newest: –

Failed: 38
Oldest: –
Newest: –
```
</details>

**Comment by tammullen** [comment]
Hi @robwatson-intechra,
Thank you for submitting the issue. However, as it appears the issue can’t be reproduced I am closing this issue for now. If I missed something or if the issue re-occurs, please leave a comment and we will take a second look.
