### ISSUE TITLE
Too few arguments to function WC_Install::run_update_callback()

### ISSUE THREAD

**Issue by javadev** [woocommerce/woocommerce#25494]
**Describe the bug**
When I start update woocommerce, then I see error in console.

**To Reproduce**
1. Update woocommerce with version 3.9
2. Click on 'Update woocommerce'
3. Check logs

**Screenshots**
2020-01-26T13:05:18.439484+00:00 app[web.1]: [26-Jan-2020 13:05:18 UTC] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function WC_Install::run_update_callback(), 0 passed in /app/wp-includes/class-wp-hook.php on line 288 and exactly 1 expected in /app/wp-content/plugins/woocommerce/includes/class-wc-install.php:195
2020-01-26T13:05:18.439494+00:00 app[web.1]: Stack trace:
2020-01-26T13:05:18.439643+00:00 app[web.1]: #0 /app/wp-includes/class-wp-hook.php(288): WC_Install::run_update_callback()
2020-01-26T13:05:18.439797+00:00 app[web.1]: #1 /app/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
2020-01-26T13:05:18.439925+00:00 app[web.1]: #2 /app/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
2020-01-26T13:05:18.440246+00:00 app[web.1]: #3 /app/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('woocommerce_run...', Array)
2020-01-26T13:05:18.440550+00:00 app[web.1]: #4 /app/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(59): ActionScheduler_Action->execute()
2020-01-26T13:05:18.440891+00:00 app[web.1]: #5 /app/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_QueueRunner.php(80): ActionScheduler_Abstract_QueueRunner->process_action('454')
2020-01-26T13:05:18.441078+00:00 app[web.1]: #6 /app/wp-content/plugins/woocommer in /app/wp-content/plugins/woocommerce/includes/class-wc-install.php on line 195

**WordPress Environment**
<details>
```
2020-01-26T13:22:18.341371+00:00 app[web.1]: [26-Jan-2020 13:22:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_get_server_info() in /app/wp-content/plugins/woocommerce/includes/wc-core-functions.php:2277
```
</details>

**Comment by juliaamosova** [comment]
Hi @javadev,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

Please provide us with more details about the issue which may help us to evaluate it further. 

What version of WooCommerce are you updating from? Are there any other plugins installed on your site?

**Comment by javadev** [comment]
I updated from version 3.8.1 to the 3.9.0.
The database is PostgreSQL.

**Comment by claudiosanches** [comment]
@javadev have you already updated from another version using PostgreSQL? Just checking if PostgreSQL have something related to it.
What PHP version are you running your store? Have you updated your PHP version before or after updating to 3.9?

**Comment by javadev** [comment]
I used heroku to host my site. Ghey have php 7.3.

**Comment by javadev** [comment]
Вы можете запустить приложение из github репозитория для heroku.

https://github.com/php4dev/heroku-wordpress

**Comment by claudiosanches** [comment]
Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> You can run the application from the github repository for heroku.

Sorry, but you haven't replied if you have already updated using PostgreSQL before.
Also note that WordPress core doesn't officially supports PostgreSQL.

**Comment by javadev** [comment]
I tried to start the update for version 3.8 to the latest version 3.9. I have got an error message in the application console as a result. This error message doesn't contain database-related exceptions, only PHP.

**Comment by rodrigoprimo** [comment]
Almost identical to #24593 but when updating to different WooCommerce versions and presumably in the same environment as it was created by the same user. See https://github.com/woocommerce/woocommerce/issues/25691#issuecomment-592163991 for a discussion of a possible workaround to this problem.

**Comment by tammullen** [comment]
Hi @javadev 
 
As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
