### ISSUE TITLE
Call to a member function get() on null when Geolocate (with caching) is enabled

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#25798]
**Describe the bug**
When "Geolocate (with page caching support)" is enabled, visiting a URL similar to /whatever/wp-json/wp/v2/posts/None throws a fatal error.

```
[02-Mar-2020 11:57:11 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/site/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php:96
Stack trace:
#0 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Customer_Data_Store_Session->read(Object(WC_Customer))
#1 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-customer.php(116): WC_Data_Store->read(Object(WC_Customer))
#2 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-cache-helper.php(130): WC_Customer->__construct(0, true)
#3 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-cache-helper.php(161): WC_Cache_Helper::geolocation_ajax_get_location_hash()
#4 /home/site/public_html/wp-includes/class-wp-hook.php(288): WC_Cache_Helper::geolocation_ajax_redirect('')
#5 /home/site/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#6 /home/site/public_ in /home/site/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php on line 96

```

**To Reproduce**
1. Enable Geolocate (with page caching support) on WooCommerce settings
2. Visit /whatever/wp-json/wp/v2/posts/None

**Expected behavior**
When the "Geolocate" option is enabled, the above returns a 404 page and there is no error.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @glagonikas 

Thank you for reporting the issue. WooCommerce REST API is being developed in another repository: https://github.com/woocommerce/woocommerce-rest-api.

I am going to move your bug report there so that we could take a look there further.

I can’t reproduce the issue you reported using the steps you provided using WooCommerce 3.92 and setting Default customer location to Geolocate (with page caching support) in WooCommerce / Settings / General and then adding a MaxMind License Key in WooCommerce / Settings / Integration
 
(Since WooCommerce 3.9 you need a MaxMind License Key to use Geolocate (with page caching support)
https://woocommerce.wordpress.com/2020/01/22/woocommerce-3-9-has-landed/#more-6153
https://docs.woocommerce.com/document/maxmind-geolocation-integration/ )

Can you copy and paste the system status report from **WooCommerce > System Status** in WordPress admin as requested in the Bug Report template so we can investigate further.
