### ISSUE TITLE
WooCommerce REST API endpoints for Email Template Types Failing

### ISSUE THREAD

**Issue by wywarren** [woocommerce/woocommerce#25796]
**Describe the bug**
WooCommerce REST API endpoint for email settings are no longer working. This applies to all subgroup endpoints under settings:

/wp-json/wc/v3/settings/email_new_order
/wp-json/wc/v3/settings/email_cancelled_order
/wp-json/wc/v3/settings/email_failed_order
/wp-json/wc/v3/settings/email_customer_on_hold_order
/wp-json/wc/v3/settings/email_customer_processing_order
/wp-json/wc/v3/settings/email_customer_completed_order
/wp-json/wc/v3/settings/email_customer_refunded_order
/wp-json/wc/v3/settings/email_customer_invoice
/wp-json/wc/v3/settings/email_customer_note
/wp-json/wc/v3/settings/email_customer_reset_password
/wp-json/wc/v3/settings/email_customer_new_account

**To Reproduce**
1. Send an authorized GET command to any of the endpoints listed above

**Screenshots**
![image](https://user-images.githubusercontent.com/5181711/75645940-e7a3d880-5c82-11ea-8604-30a8ee2c9dc6.png)

**Expected behavior**
Return all settings for email template

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional Error Logs**
```
[02-Mar-2020 04:32:13 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-setting-options-controller.php:93
Stack trace:
#0 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version2/class-wc-rest-setting-options-v2-controller.php(131): WC_REST_Setting_Options_Controller->get_group_settings('email_new_order')
#1 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(946): WC_REST_Setting_Options_V2_Controller->get_items(Object(WP_REST_Request))
#2 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(329): WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /var/www/html/wp-includes/rest-api.php(305): WP_REST_Server->serve_request('/wc/v3/settings...')
#4 /var/www/html/wp-includes/class-wp-hook.php(288): rest_api_loaded(Object(WP))
#5 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_fi in /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/
```

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): *
Site address (URL): *
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.1.25-1+ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: *
Total Database Size: 15.34MB
Database Data Size: 12.23MB
Database Index Size: 3.11MB
*

### Post Type Counts ###

acf: 2
attachment: 3
custom_css: 1
customize_changeset: 1
iwp_log: 23
nav_menu_item: 9
page: 15
post: 1
product: 2
revision: 11
scheduled-action: 1637
shop_coupon: 2
shop_order: 30
shop_order_refund: 5
wc_order_status: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Cloudflare Flexible SSL: by One Dollar Plugin – 1.3.0
JSON Basic Authentication: by WordPress API Team – 0.1
Classic Editor: by WordPress Contributors – 1.5
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.4.1

Force HTTPS: by LittleBizzy – 1.2.0
Hide Admin Bar: by Shelby DeNike – 0.3.9.9
qTranslate-XT: by qTranslate Community – 3.7.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.9

WooCommerce: by Automattic – 3.9.2

### Inactive Plugins (79) ###

ACF to REST API: by Aires Gonçalves – 3.2.0
Advanced Access Manager: by Vasyl Martyniuk <vasyl@vasyltech.com> – 6.3.3
Advanced Custom Fields: by Elliot Condon – 5.8.7
Advanced Database Cleaner: by Younes JFR. – 3.0.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.0 – Not tested with the active version of WooCommerce
Customizer Field EndPoint: by Bishal Basnet – 1.0.0
Custom Post Type UI: by WebDevStudios – 1.7.3
Disable WooCommerce Reviews: by pipdig – 1.1 – Not tested with the active version of WooCommerce
Easypost WooCommerce Extension (BASIC): by XAdapter – 1.2.0 – Not tested with the active version of WooCommerce
ECPay Invoice for WooCommerce: by ECPay Green World FinTech Service Co.
Ltd. – 1.1.1910210 – Not tested with the active version of WooCommerce

ECPay Logistics for WooCommerce: by ECPay Green World FinTech Service Co.
Ltd. – 1.3.1910240 – Not tested with the active version of WooCommerce

ECPay Payment for WooCommerce: by ECPay Green World FinTech Service Co.
Ltd. – 1.2.2001070 – Not tested with the active version of WooCommerce

Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
FB Messenger Live Chat: by Zotabox – 1.5.0
FedEx WooCommerce Extension (BASIC): by PluginHive – 2.1.4 – Not tested with the active version of WooCommerce
Flexible Woocommerce Checkout Field Editor: by heoLixfy – 1.0.0 – Not tested with the active version of WooCommerce
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.2 – Not tested with the active version of WooCommerce
Google XML Sitemaps: by Arne Brachhold – 4.1.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.2
JWT Authentication for WP-API: by Enrique Chavez – 1.2.6
ManageWP - Worker: by GoDaddy – 4.9.3
Perfect WooCommerce Brands: by Alberto de Vera Sevilla – 1.7.9
Pixel Cat Elite: by Fatcat Apps – 2.4.1
PixelYourSite: by PixelYourSite – 7.1.4 – Not tested with the active version of WooCommerce
*
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
*
Thumbnail Upscale: by Stanislav Khromov – 1.1
User Role Editor: by Vladimir Garagulya – 4.53
WebRotate 360 Product Viewer for WordPress: by WebRotate 360 LLC – 3.1.5
WooCommerce Admin: by WooCommerce – 0.25.1
WooCommerce Composite Products: by SomewhereWarm – 3.14.1 – Not tested with the active version of WooCommerce
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.3.5 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.0 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.3 – Not tested with the active version of WooCommerce
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.2 – Not tested with the active version of WooCommerce
WooCommerce Google Ads Dynamic Remarketing: by Wolf+Bär Agency – 1.7.14 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.17
WooCommerce Google Analytics Pro: by SkyVerge – 1.7.0 – Not tested with the active version of WooCommerce
WooCommerce Helper: by WooCommerce – 1.7.2 – Not tested with the active version of WooCommerce – Network enabled
WooCommerce LINEPay Gateway: by LINEPay – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Mix and Match: by Kathy Darling – 1.3.3 – Not tested with the active version of WooCommerce
WooCommerce Order Status Manager: by SkyVerge – 1.9.2 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.7.11 – Not tested with the active version of WooCommerce
WooCommerce Product Feed: by WebAppick – 3.3.2
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.10 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking Basic: by PluginHive – 1.0.9 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooCommerce – 2.2.13 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 3.8.1 – Not tested with the active version of WooCommerce
WooCommerce Social Login: by SkyVerge – 2.6.2 – Not tested with the active version of WooCommerce
WooCommerce Stock Manager: by Vladislav Musílek – 2.0.2 – Not tested with the active version of WooCommerce
WooCommerce WishLists: by Lucas Stark – 1.11.2 – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 2.2.1 – Not tested with the active version of WooCommerce
WP All Export Pro: by Soflyy – 1.5.10
WP All Import - ACF Add-On: by Soflyy – 3.2.5
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.1.1 – Not tested with the active version of WooCommerce
WP All Import Pro: by Soflyy – 4.5.9
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
WP Mail SMTP: by WPForms – 1.8.1
WP Offload Media Lite: by Delicious Brains – 2.3.2
WP Remote: by WP Remote – 3.4
WP REST API: by WP REST API Team – 2.0-beta15
WP REST API Controller: by YIKES
Inc. – 2.0.3

WP REST Filter: by SK8Tech – 1.4.3
YITH Automatic Role Changer for WooCommerce: by YITHEMES – 1.1.6 – Not tested with the active version of WooCommerce
Yoast SEO: by Team Yoast – 13.1
藍新金流: by 藍新金流 newebpay – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: TWD (NT$)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Sellerlinx Storefront Theme
Version: 1.0.0
Author URL: https://qoobit.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.2 – 2.5.5 is available
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: sellerlinx-storefront-theme/woocommerce/emails/customer-new-account.php version 3.5.2 is out of date. The core version is 3.7.0
sellerlinx-storefront-theme/woocommerce/single-product/meta.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 1,561
Oldest: 2020-01-31 12:49:04 +0800
Newest: 2020-03-02 11:57:38 +0800

Pending: 1
Oldest: 2020-03-03 20:23:45 +0800
Newest: 2020-03-03 20:23:45 +0800

Canceled: 2
Oldest: 2020-03-02 12:57:38 +0800
Newest: 2020-03-02 12:57:38 +0800

In-progress: 0
Oldest: –
Newest: –

Failed: 73
Oldest: 2020-02-09 11:22:39 +0800
Newest: 2020-02-09 21:56:24 +0800

`
```
</details>

**Comment by wywarren** [comment]
I've managed to get this to go away by going to the email settings tab and re-saving each of the template settings. Perhaps it was caused at some point by a database upgrade which required these to be saved into a new format.
