### ISSUE TITLE
[4.0] WC Admin fatal error

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#25869]
**Describe the bug**
I am not sure if this is a bug with WooCommerce but I suspect it might be.

I have this error on a customer's site:

```
Fatal error: Uncaught Exception: Invalid data store. in /home/xxx/yyy/wp-content/plugins/woocommerce/includes/class-wc-data-store.php:107

Stack trace:
#0 /home/xxx/yyy/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(139): WC_Data_Store->__construct('admin')
#1 /home/xxx/yyy/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(121): WC_Data_Store::load('admin-note')
#2 /home/xxx/yyy/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(59): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name('wc-admin-deacti...')
#3 /home/xxx/yyy/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Deactivate_Plugin::delete_note()
#4 [internal function]: Automattic\WooCommerce\Admin\Composer\Package::init()
#5 /home/xxx/yyy/wp-content/plugins/woocommerce/src/Pac in /home/xxx/yyy/wp-content/plugins/woocommerce/includes/class-wc-data-store.php on line 107

There has been a critical error on your website. Please check your site admin email inbox for instructions.
```

It is shown on the `plugins.php` page. The site is a multisite, it's shown on the Network tab but also when opening `wp-admin` of some subsites.

My suspect is this line

```
WC_Data_Store->__construct('admin')
```

The Data Store `admin` does not seem to exist anywhere and it's causing this error to appear.

**To Reproduce**
Not sure.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

In the ticket. Private data are included so I cannot post it here.

2781410-zen

**Comment by peterfabian** [comment]
It seems to me that inside `\Automattic\WooCommerce\Admin\Composer\Package::init`, `add_note` and `delete_note` is getting called before the `admin-note` data store is registered in `FeaturePlugin::instance()->init();`. 

In this case, the plugin must be installed and it is up to date (judging by the fact that `delete_note` is in the stack trace). 

WC Admin data stores are hooked to `plugins_loaded`, default priority in `\Automattic\WooCommerce\Admin\FeaturePlugin::init` via `\Automattic\WooCommerce\Admin\FeaturePlugin::on_plugins_loaded`, `\Automattic\WooCommerce\Admin\FeaturePlugin::includes` and `\Automattic\WooCommerce\Admin\API\Init::__construct`

However, also hooked to `plugins_loaded`, `\Automattic\WooCommerce\Packages::on_init` runs from the WC Admin package. This then calls `\Automattic\WooCommerce\Admin\Composer\Package::init` which is where the error happens. 

So it seems to me, both 1. registering the data stores and 2. potentially using them runs at `plugins_loaded` with the default priority, which can lead to a problem.
