### ISSUE TITLE
Uncaught Exception on WPMU

### ISSUE THREAD

**Issue by tobiasfeistmantl** [woocommerce/woocommerce#25947]
**Describe the bug**
I get an "Uncaught Exception" error on an individually activated site in a WordPress Multisite Network.

Here the full error:

```
Uncaught Exception: The admin note content_data prop must be an instance of stdClass. in /var/web/site/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php on line 810
error()
set_content_data()
read()
read()
__construct()
should_show_notice()
show_reminder()
apply_filters()
do_action()
do_action()
set_current_screen()
set_current_screen()
require_once()
```

**Isolating the problem (mark completed items with an [x]):**
- [ All individually activated ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
-  [] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WPMU 5.3.2

**Comment by lukaszj-salag** [comment]
I can reproduce same problem, website was cloned with Updraft to other location:
WP: 5.3.2
WooCommerce: 4.0.0

```Error Details
=============
An error of type E_ERROR was caused in line 810 of the file /home/hosting/public_html/example.com/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php. Error message: Uncaught WC_Data_Exception: The admin note content_data prop must be an instance of stdClass. in /home/hosting/public_html/example.com/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-data.php:810
Stack trace:
#0 /home/hosting/public_html/example.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Note.php(414): WC_Data->error('admin_note_inva...', 'The admin note ...')
#1 /home/hosting/public_html/example.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php(98): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->set_content_data(Array)
#2 /home/hosting/public_html/example.com/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#3 /home/hosting/public_html/example.com/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Note.php(83): WC_Data_Store->read(Object(Automattic\Wo

```
