### ISSUE TITLE
Fatal error: Uncaught RuntimeException

### ISSUE THREAD

**Issue by phil310** [woocommerce/woocommerce#25997]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Fatal error: Uncaught RuntimeException: Erreur lors de l'enregistrement de l'action : Erreur lors de l'enregistrement de l'action : Table 'dbs327831.wp_457901_actionscheduler_actions' doesn't exist in /homepages/5/d821404388/htdocs/clickandbuilds/Diaphaneditions/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /homepages/5/d821404388/htdocs/clickandbuilds/Diaphaneditions/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(225): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /homepages/5/d821404388/htdocs/clickandbuilds/Diaphaneditions/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /homepages/5/d821404388/htdocs/clickandbuilds/Diaphaneditions/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionSch in /homepages/5/d821404388/htdocs/clickandbuilds/Diaphaneditions/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
`
### WordPress Environment ###

WordPress address (URL): https://www.diaphane-editions.com
Site address (URL): https://www.diaphane-editions.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 640 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.15
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.28-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_457901_
Taille totale de la base de données: 14.38MB
Taille de la base de données: 11.94MB
Taille de l’index: 2.44MB
wp_457901_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_457901_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_457901_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_457901_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_457901_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_cf_forms: Données : 0.09MB + Index : 0.02MB + Moteur InnoDB
wp_457901_cf_form_entries: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_457901_cf_form_entry_meta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_cf_form_entry_values: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_457901_cf_pro_messages: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_457901_cf_queue_failures: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_457901_cf_queue_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_457901_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_457901_ewwwio_images: Données : 1.52MB + Index : 0.58MB + Moteur InnoDB
wp_457901_ewwwio_queue: Données : 0.05MB + Index : 0.02MB + Moteur InnoDB
wp_457901_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_options: Données : 2.52MB + Index : 0.08MB + Moteur InnoDB
wp_457901_postmeta: Données : 5.52MB + Index : 0.56MB + Moteur InnoDB
wp_457901_posts: Données : 1.52MB + Index : 0.13MB + Moteur InnoDB
wp_457901_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_tm_taskmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_tm_tasks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_457901_wcpdf_invoice_number: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_457901_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_457901_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_457901_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_457901_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 600
custom_css: 3
elementor_library: 7
nav_menu_item: 12
page: 9
post: 2
product: 61
revision: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Akismet Anti-Spam: par Automattic – 4.1.4
Better Search Replace: par Delicious Brains – 1.3.3
Caldera Forms: par Caldera Labs – 1.8.11
Classic Editor: par Contributeurs et contributrices WordPress – 1.5
Duplicate Post: par Enrico Battocchi – 3.2.4
Elementor Pro: par Elementor.com – 2.9.1
Elementor: par Elementor.com – 2.9.6
EWWW Image Optimizer: par Exactement WWW – 5.2.2
HT Mega - Absolute Addons for Elementor Page Builder: par HasThemes – 1.3.7
Ocean Extra: par OceanWP – 1.6.0
Ocean Sticky Header: par OceanWP – 1.1.12
Shariff Wrapper: par Jan-Peter Lambeck & 3UU – 4.6.4
TinyMCE Advanced: par Andrew Ozz – 5.3.0
UpdraftPlus - Sauvegarde/Restauration: par UpdraftPlus.Com
DavidAnderson – 1.16.22

VenoBox Lightbox: par <a href="https://wpbeaches.com">Neil Gowran</a>
<a href="http://veno.es">Nicola Franchini</a> – 2.0.1

WooCommerce PDF Invoices & Packing Slips: par Ewout Fernhout – 2.4.7
WooCommerce Services: par Automattic – 1.22.5
WooCommerce: par Automattic – 4.0.1
WP-Optimize - Clean, Compress, Cache: par David Anderson
Ruhani Rabin
équipe Updraft – 3.0.16

SEOPress PRO: par SEOPress – 3.8.4
SEOPress: par SEOPress – 3.8.4
WPS Hide Login: par WPServeur
NicolasKulka
tabrisrp – 1.5.6

WPS Limit Login: par WPServeur
NicolasKulka – 1.4.7

### Inactive Plugins (4) ###

Autoptimize: par Frank Goossens (futtta) – 2.6.2
WooCommerce Stripe Gateway: par WooCommerce – 4.3.2 – Non testé avec la version active de WooCommerce
WP Fastest Cache: par Emre Vona – 0.9.0.4
WP Statistics: par VeronaLabs – 12.6.12

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #28854 - /boutique/
Panier: #28855 - /panier/
Validation de la commande: #28856 - /commande/
Mon compte: #28857 - /mon-compte/
Conditions générales de vente et d’utilisation: #29330 - /cgv/

### Theme ###

Name: OceanWP
Version: 1.7.4 – 1.7.8 est disponible
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Action Scheduler ###

`

**Comment by juliaamosova** [comment]
Hi @phil310, thanks for reporting the issue! @rrennick would you please take a look?

**Comment by peterfabian** [comment]
This seems to be the same problem as https://github.com/woocommerce/woocommerce/issues/25895. But looks like it's happening also after 4.0.1...

**Comment by rrennick** [comment]
> WP-Optimize - Clean, Compress, Cache: par David Anderson
Ruhani Rabin

Based on other reports, WP Optimize recommends deleting the AS tables.

@phil310 Can you navigate to Tools -> Scheduled Actions in your dashboard to see if there is a noticing indicating that Action Scheduler attempted to recreate the tables.

**Comment by phil310** [comment]
I can't see anything except that the library's no longer accessible.

**Comment by marcusig** [comment]
@rrennick I'm one of the developers working on WP-Optimize. FYI, we have an update ready with updated plugins/db tables relationships. Though the person in charge of releasing is currently unavailable due to the current worldwide situation, and we unfortunatly have to wait until he's back.

I personally had the same problem on a my website, where I didn't delete the tables, but upgraded from WC3.9. 

Going to WooCommerce -> Status -> Scheduled Actions fixed the issue though.

**Comment by rrennick** [comment]
@marcusig Thanks for letting us know :)

**Comment by phil310** [comment]
I have this 
Scheduled Actions fixed the issue though.
The migration of the action planner is in progress. The list of planned actions may not be complete.

It appears one or more database tables were missing. Attempting to re-create the missing table(s).

**Comment by phil310** [comment]
I put back version 3.9.3
It's ok now.

**Comment by phil310** [comment]
Thank you for your feedback

**Comment by georgetasioulis** [comment]
> This seems to be the same problem as #25895. But looks like it's happening also after 4.0.1...

Yeah, we were seeing a huge increase in DB queries (https://share.getcloudapp.com/2NuB8XJj) after upgrading from 3.9.3 to 4.0.1 and were seeing ActionScheduler related errors all over the place. 
For now we've switched back to 3.9.3 but I've asked my customer to try 4.0.1 again but this time also install the Action Scheduler plugin: https://github.com/woocommerce/action-scheduler/archive/3.1.4.zip

So while 4.0.1 should address this (https://github.com/woocommerce/woocommerce/issues/25895#issuecomment-601640624) it probably didn't.

**Comment by rrennick** [comment]
> For now we've switched back to 3.9.3 but I've asked my customer to try 4.0.1 again but this time also install the Action Scheduler plugin:

@georgestephanis If the site is having performance issues it would be better to install AS 3.1.4 and allow the AS migration to complete before re-updating to WC 4.0.1. AS 3.1.4 is the version of AS in WC 4.0.1.

**Comment by georgestephanis** [comment]
Wrong George!

**Comment by rrennick** [comment]
Sorry @georgestephanis

**Comment by beesalsht** [comment]
**I am getting this error when I try to activate woocommerce plugin.** Any solution ??

An error of type E_ERROR was caused in line 44 of the file /home/u704112749/domains/example.com/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php. Error message: Uncaught RuntimeException: Error saving action: Error saving action: Table 'u704112749_y9Xv7.wp_actionscheduler_actions' doesn't exist in /home/u704112749/domains/example.com/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /home/u704112749/domains/beyondhimalayas.com/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /home/u704112749/domains/beyondhimalayas.com/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /home/u704112749/domains/example.com/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Objec

**Comment by zdenys** [comment]
Another report in 26883514-hc.

**Comment by Konamiman** [comment]
If WooCommerce is active, going to the scheduled actions list page (WooCommerce > Status > Scheduled Actions, `/wp-admin/admin.php?page=wc-status&tab=action-scheduler`) will display a _It appears one or more database tables were missing. Attempting to re-create the missing table(s)_ which will indeed recreate the table.

However if as @beesalsht points out WooCommerce isn't active, it will not be possible to activate it. Here's a workaround if that happens:

1. Add the following custom code using [the code snippets plugins](https://wordpress.org/plugins/code-snippets/) or any similar mechanism:

```php
add_filter( 'action_scheduler_migration_dependencies_met', function() {return false;} );
add_filter( 'action_scheduler_store_class', function() {return ActionScheduler_DBStore::class;} );
```

2. Activate WooCommerce and go to the Scheduled Actions page as pointed out above so the problem is fixed.

3. Remove the custom code.

I'll create an issue in the Action Scheduler repo to research a better solution.

**Comment by peterfabian** [comment]
Since it seems like the issue in the Action Scheduler repo has been addressed, I'm closing this one, too. Please open a new issue if you encounter this error. Thanks.
