### ISSUE TITLE
ActionScheduler tables missing in integration tests

### ISSUE THREAD

**Issue by dingo-d** [woocommerce/woocommerce#26070]
**Describe the bug**
I'm setting up integration tests using [wp-browser](https://wpbrowser.wptestkit.dev/) - which is a codeception based testing suite. I've set everything right but I'm getting errors when running integration tests. Upon running the tests I get

```bash
> codecept run wpunit
Codeception PHP Testing Framework v3.1.2
Powered by PHPUnit 7.5.20 by Sebastian Bergmann and contributors.
Running with seed:

WordPress database error Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
WordPress database error Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
WordPress database error Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
WordPress database error Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
WordPress database error Table 'wordpress-test.wp_actionscheduler_groups' doesn't exist for query SELECT group_id FROM wp_actionscheduler_groups WHERE slug='action-scheduler-migration' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id
WordPress database error Table 'wordpress-test.wp_actionscheduler_groups' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_groups` made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group
WordPress database error Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist for query INSERT INTO `wp_actionscheduler_actions` (`hook`, `status`, `scheduled_date_gmt`, `scheduled_date_local`, `schedule`, `group_id`, `args`) VALUES ('action_scheduler/migration_hook', 'pending', '2020-04-02 19:02:47', '2020-04-02 19:02:47', 'O:30:\"ActionScheduler_SimpleSchedule\":2:{s:22:\"\0*\0scheduled_timestamp\";i:1585854167;s:41:\"\0ActionScheduler_SimpleSchedule\0timestamp\";i:1585854167;}', '0', '[]') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action
PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist in /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(225): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler in /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

Wpunit Tests (2) ---------------------------------------------------------------
✔ ActivationTest: It works (0.01s)
✔ ActivationTest: Plugin can be activated (0.00s)
--------------------------------------------------------------------------------


Time: 1.22 seconds, Memory: 12.00 MB

OK (2 tests, 2 assertions)
```

Tests pass because they are not interacting with WooCommerce yet. There are a bunch of errors above which shouldn't happen.

I tried bootstraping the actions that would trigger the database seeds, but without any luck.

**To Reproduce**
1. Setup tests for a plugin using wp-browser
2. Add woocommerce as a plugin dependency in the `wpunit.suite.yml` file
3. Try to run the tests

**Expected behavior**
There should be no DB seeding errors.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by Annie4Star** [comment]
I had this issue yesterday and I lost my mind for a few hours trying to figure it out.  I had to contact my host to revert my site to last week.  I reverted back to 3.9.3 after I postponed going to 4.0.0 for the sake of some plugins.

**Comment by dingo-d** [comment]
There is definitely something wrong with the action scheduler. I can confirm that the tables are there during the test. I went to `ActionScheduler_DBStoreMigrator.php` class and checked values inside the `save_action` and for `$action_id`, `$action`, `$scheduled_date` and `$last_attempt_date` I get

```bash
6
ActionScheduler_Action Object
(
    [hook:protected] => action_scheduler/migration_hook
    [args:protected] => Array
        (
        )

    [schedule:protected] => ActionScheduler_SimpleSchedule Object
        (
            [timestamp:ActionScheduler_SimpleSchedule:private] => 1586110907
            [scheduled_date:ActionScheduler_Abstract_Schedule:private] => ActionScheduler_DateTime Object
                (
                    [utcOffset:protected] => 0
                    [date] => 2020-04-05 18:21:47.000000
                    [timezone_type] => 3
                    [timezone] => UTC
                )

            [scheduled_timestamp:protected] => 1586110907
        )

    [group:protected] => action-scheduler-migration
)
```

So things do execute in this hook, but for some reason, it falls to the `catch` part and errors out.

**Comment by tammullen** [comment]
Hi @dingo-d, thanks for reporting the issue! @rrennick would you be able to take a look at this?

**Comment by rrennick** [comment]
My suggestion would be to try to set up just [Action Scheduler](https://github.com/woocommerce/action-scheduler) in the testing environment and see if the same occurs. If the same occurs, create an issue in that repo and provide details on the bootstrap process, etc.

**Comment by dingo-d** [comment]
Will try to do that. I tried adding `\ActionScheduler::init(dirname(__FILE__, 3) . '/woocommerce/woocommerce.php');` inside my `bootstrap.php` file, but I still got the errors.

Is there any special way I should be setting it up with integration tests? Can you point me to any documentation about it? Thanks!

**Comment by dingo-d** [comment]
I've added the ActionScheduler to my test instance, and the acceptance test that checks that the action scheduler page exists works

```php
public function seeScheduledActionsPage(AcceptanceTester $I)
{
	$I->activatePlugin('action-scheduler');
	$I->amOnPage('/wp-admin/tools.php?page=action-scheduler');
	$I->see('Scheduled Actions');
}
```

I've added an integration test to check all the hooks loaded

```php
public function testActionSchedulerWorks()
{
	error_log( print_r( $GLOBALS['wp_actions'], true ) );
}
```

and I see 3 actions that are ActionScheduler related

```
[action_scheduler_pre_init] => 1
[action_scheduler/created_table] => 4
[add_option_action_scheduler_hybrid_store_demarkation] => 1
```

Running the integration test gives the same result (after wp database error), only this time the error is not in WooCommerce, but coming from the ActionScheduler plugin.

```bash
PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist in /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(225): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_ in /Users/denis.zoljom/vagrant-local/www/personal/wordpress-test/public_html/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44
```

**Comment by rrennick** [comment]
> Is there any special way I should be setting it up with integration tests?

@dingo-d The AS bootstrap is https://github.com/woocommerce/action-scheduler/blob/master/tests/bootstrap.php 

> `WordPress database error Table 'wordpress-test.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by shutdown_action_hook, do_action('shutdown'),`

What do you have for your database class?

**Comment by dingo-d** [comment]
> What do you have for your database class?

I'm using [wp-browser](https://github.com/lucatume/wp-browser) extension for test setup. It's based on Codeception, but integration tests are following the regular setup used by wpcli scaffold tests. I'm connecting to database on my VVV instance.

Not sure if I understood the question correctly.

**Comment by rrennick** [comment]
> Not sure if I understood the question correctly.

Are you using the default WordPress database class? If you have a different DB class it would be `wp-content/db.php`.

**Comment by lucatume** [comment]
> > Not sure if I understood the question correctly.
> 
> Are you using the default WordPress database class? If you have a different DB class it would be `wp-content/db.php`.

Hi,

wp-browser, in the context of integration tests where the WordPress installation is set up by the WPLoader module, uses the `wpdb` class, the default WordPress class.

**Comment by dingo-d** [comment]
Looks like this was fixed in the newest release of wp-browser. No errors anymore. Thanks!

**Comment by rrennick** [comment]
@dingo-d Thanks for letting us know :)
