### ISSUE TITLE
no se me ven las imagenes de la tienda

### ISSUE THREAD

**Issue by vanessazion** [woocommerce/woocommerce#26390]
Borré por accidente en la biblioteca de medios algún archivo png que parecía una imagen vacía y ahora mi pagina tienda aparece sin las imagenes de los productos y no sé como solucionarlo.  Ahora supongo que era un placeholder.png... pero no sé como recuperarlo
`
### WordPress Environment ###

WordPress address (URL): http://xn--lacoleccindezion-evb.es
Site address (URL): http://xn--lacoleccindezion-evb.es
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.16
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1d-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: nru_
Tamaño total de la base de datos: 6.77MB
Tamaño de los datos de la base de datos: 5.01MB
Tamaño del índice de la base de datos: 1.76MB
nru_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nru_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nru_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nru_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nru_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_actionscheduler_actions: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
nru_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
nru_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_options: Datos: 2.09MB + Índice: 0.08MB + Motor InnoDB
nru_postmeta: Datos: 1.47MB + Índice: 0.16MB + Motor InnoDB
nru_posts: Datos: 0.48MB + Índice: 0.06MB + Motor InnoDB
nru_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
nru_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nru_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nru_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
nru_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
nru_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
nru_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
nru_yoast_indexable: Datos: 0.05MB + Índice: 0.05MB + Motor InnoDB
nru_yoast_indexable_hierarchy: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
nru_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
nru_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
nru_yoast_seo_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 21
custom_css: 1
customize_changeset: 14
elementor_library: 2
nav_menu_item: 59
oembed_cache: 2
page: 11
post: 6
product: 20
revision: 76

### Security ###

Secure connection (HTTPS): ❌
					Tu tienda no está usando HTTPS. Aprende más sobre HTTPS y los certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (11) ###

Placeholder Image for Woocommerce: por Игорь iTRON Тронь – 1.1 – Versión instalada no está probada con la versión activa de WooCommerce 4.1.0
Elementor: por Elementor.com – 2.9.8
SG Optimizer: por SiteGround – 5.5.4
Tawk.to Live Chat: por Tawkto – 0.4.2
Orbit Fox Companion: por ThemeIsle – 2.9.8
WooCommerce: por Automattic – 4.1.0
WordPress Importer: por wordpressdotorg – 0.7
Yoast SEO: por Equipo Yoast – 14.0.4
WordPress Starter: por SiteGround – 1.1.1
Smush: por WPMU DEV – 3.6.1
WPForms Lite: por WPForms – 1.6.0.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #396 - /tienda/
Carrito: #54 - /cesta/
Finalizar compra: #55 - /checkout/
Mi cuenta: #56 - /mi-cuenta/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Astra
Version: 2.4.3
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 25
Oldest: 2020-05-04 13:31:08 +0000
Newest: 2020-05-06 00:00:06 +0000

Pendiente: 1
Oldest: 2020-05-07 00:00:06 +0000
Newest: 2020-05-07 00:00:06 +0000

`

**Comment by vanessazion** [comment]
y ahora ya no me deja entrar a la página y me da este mensaje:  había desactivado los pluggins y los volvía a activar. y no me dejó me salió esta pantalla. 

Fatal error: Uncaught Error: Class 'WC_Admin_Settings' not found in /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-content/plugins/default-product-image-for-woocommerce/default-product-image-for-woocommerce.php:71 Stack trace: #0 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-includes/class-wp-hook.php(287): wcdi_placeholder_replacing('') #1 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-settings.php(540): do_action('init') #4 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-config.php(78): require_once('/home/customer/...') #5 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-load.php(37): require_once('/home/customer/...') #6 /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-admin/admin.php(34 in /home/customer/www/xn--lacoleccindezion-evb.es/public_html/wp-content/plugins/default-product-image-for-woocommerce/default-product-image-for-woocommerce.php on line 71

**Comment by vanessazion** [comment]
Solucionado!
