### ISSUE TITLE
Fatal Error while clicking on Product Order or WooCommerce link on workpress dashboard

### ISSUE THREAD

**Issue by atifakbar** [woocommerce/woocommerce#26416]
Fatal Error while clicking on Product Order or WooCommerce link on workpress dashboard

**To Reproduce**
1. Go to Wordpress Dashboard '...'
2. Click on wooCommerce or under it Order or Under it Product '....'

Fatal error: Uncaught RuntimeException: Error saving action: Unable to save action. in /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:33 Stack trace: #0 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(109): ActionScheduler_wpPostStore->save_action(Object(ActionScheduler_Action)) #1 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(59): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #2 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/functions.php(18): ActionScheduler_ActionFactory->single('woocommerce_upd...', Array, 1588897506, '') #3 /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/queue/clas in /homepages/33/d488813334/htdocs/app488813350/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 33
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress.

**Comment by juliaamosova** [comment]
Hi @atifakbar,

Thank you for reporting the issue. It seems it is related to Action Scheduler which is being developed in another repository: https://github.com/woocommerce/action-scheduler. 

I am going to move your bug report there so that the right team could take a look further.
