### ISSUE TITLE
Table 'wpdb.wp_actionscheduler_actions' doesn't exist

### ISSUE THREAD

**Issue by kohldampfer** [woocommerce/woocommerce#26440]
**Describe the bug**
When I want to activate WooCommerce Plugin (downloaded from here https://de.wordpress.org/plugins/woocommerce/), I get the following error message

```
 Fatal error: Uncaught mysqli_sql_exception: Table 'wpdb.wp_actionscheduler_actions' doesn't exist in /var/www/html/wordpress/wp-includes/wp-db.php:2026 
 Stack trace: 
 #0 /var/www/html/wordpress/wp-includes/wp-db.php(2026): mysqli_query(Object(mysqli), 'DESCRIBE wp_act...') 
 #1 /var/www/html/wordpress/wp-includes/wp-db.php(1914): wpdb->_do_query('DESCRIBE wp_act...') 
 #2 /var/www/html/wordpress/wp-includes/wp-db.php(2643): wpdb->query('DESCRIBE wp_act...') 
 #3 /var/www/html/wordpress/wp-admin/includes/upgrade.php(2645): wpdb->get_results('DESCRIBE wp_act...') 
 #4 /var/www/html/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Abstract_Schema.php(117): dbDelta(Array) 
 #5 /var/www/html/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Abstract_Schema.php(45): ActionScheduler_Abstract_Schema->update_table('actionscheduler...') 
 #6 /var/www/html/wordpress/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/Act in /var/www/html/wordpress/wp-includes/wp-db.php on line 2026
```

**To Reproduce**
1. Setup a fresh Wordpress installation.
2. Download plugin from https://de.wordpress.org/plugins/woocommerce/
3. Upload plugin.
4. Activate plugin

**Screenshots**
![woocommerce-error](https://user-images.githubusercontent.com/20419801/81476322-b232e280-9211-11ea-838e-e258fad00a0b.png)

**Expected behavior**
Activated Woocommerce plugin.

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

See picture
![woocommerce-all-other-plugins-are-deactivated](https://user-images.githubusercontent.com/20419801/81476373-f920d800-9211-11ea-9730-994c21d581a5.png)

- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

Active theme was `Twenty Twenty`.

- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

- Wordpress and MySQL are running in two different docker container.
- Wordpress Version is 5.4.1
- MySQL Version is `Server version: 8.0.20 MySQL Community Server - GPL`
- Tried to install WooCommerce version 4.1.0 .

**Comment by peterfabian** [comment]
Hi @kohldampfer 

Thanks for reporting this problem. Can you please share which hosting are you using? It seems quite strange because we haven't seen this problem right at the activation before.

**Comment by juliaamosova** [comment]
Hi @kohldampfer,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
