### ISSUE TITLE
Error after deactivating and reactivating woocommerce why please?

### ISSUE THREAD

**Issue by jaygaga** [woocommerce/woocommerce#26622]
WordPress database error: [Table 'wp6973085.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1

WordPress database error: [Table 'wp6973085.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1

WordPress database error: [Table 'wp6973085.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1

WordPress database error: [Table 'wp6973085.wp_actionscheduler_actions' doesn't exist]
SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1

WordPress database error: [Table 'wp6973085.wp_actionscheduler_groups' doesn't exist]
SELECT group_id FROM wp_actionscheduler_groups WHERE slug='action-scheduler-migration'

WordPress database error: [Table 'wp6973085.wp_actionscheduler_groups' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_groups`

WordPress database error: [Table 'wp6973085.wp_actionscheduler_actions' doesn't exist]
SHOW FULL COLUMNS FROM `wp_actionscheduler_actions`

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table 'wp6973085.wp_actionscheduler_actions' doesn't exist in /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('action_schedule...', in /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

There has been a critical error on your website.

Learn more about debugging in WordPress.

**Comment by juliaamosova** [comment]
Hi @jaygaga,

Sorry to hear that you are experiencing the issue. Can you please specify what version of WooCommerce are you using?

**Comment by jaygaga** [comment]
Hi @juliaamosova its Version 4.1.1

**Comment by tammullen** [comment]
Hi @jaygaga 

Apologies for the delay in replying

Are you still experiencing this issue? Can you try with the current release of WooCommerce.

**Comment by juliaamosova** [comment]
Hi @jaygaga,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
