### ISSUE TITLE
Activation Woocommerce renders latest WP unusable

### ISSUE THREAD

**Issue by sean5446** [woocommerce/woocommerce#26759]
**Describe the bug**
Woocommerce plugin crashes fresh Wordpress 5.4.2 install with various themes including Store Front. Can't make it through the first page of the startup Wizard. Leaves entire Wordpress install unreachable without disabling plugins via File Manager. 

**To Reproduce**
Install Woocommerce, try to complete wizard or generally do anything with the plugin. 

**Screenshots**
```
[11-Jun-2020 23:18:14 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:18:14 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:18:15 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:18:15 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:18:15 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:19:23 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:19:23 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:19:23 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:19:23 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:19:53 UTC] PHP Warning:  array_merge(): Expected parameter 1 to be an array, null given in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Assets.php on line 157
[11-Jun-2020 23:19:57 UTC] PHP Fatal error:  Uncaught Error: Class 'ActionScheduler_wpPostStore' not found in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/Controller.php:111
Stack trace:
#0 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(43): Action_Scheduler\Migration\Controller->get_migration_config_object()
#1 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler_Store.php(341): ActionScheduler_HybridStore->__construct()
#2 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php(25): ActionScheduler_Store::instance()
#3 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php(145): ActionScheduler::store()
#4 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(44): in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/Controller.php on line 111
[11-Jun-2020 23:19:57 UTC] PHP Warning:  require_once(classes/abstracts/ActionScheduler.php): failed to open stream: No such file or directory in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php on line 43
[11-Jun-2020 23:19:57 UTC] PHP Fatal error:  require_once(): Failed opening required 'classes/abstracts/ActionScheduler.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php on line 43
[11-Jun-2020 23:19:57 UTC] PHP Warning:  require_once(/home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/automattic/jetpack-constants/src/class-constants.php): failed to open stream: No such file or directory in /home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 168
[11-Jun-2020 23:19:57 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/automattic/jetpack-constants/src/class-constants.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 168
[11-Jun-2020 23:19:57 UTC] PHP Warning:  require_once(/home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/automattic/jetpack-constants/src/class-constants.php): failed to open stream: No such file or directory in /home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 168
[11-Jun-2020 23:19:57 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/automattic/jetpack-constants/src/class-constants.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 168
[11-Jun-2020 23:19:57 UTC] PHP Fatal error:  Uncaught Error: Class 'Action_Scheduler\Migration\Controller' not found in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DataController.php:171
Stack trace:
#0 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php(143): ActionScheduler_DataController::init()
#1 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(44): ActionScheduler::init('/home/wikinves/...')
#2 /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_3_dot_1_dot_6()
#3 /home/wikinves/public_html/wp-includes/class-wp-hook.php(285): ActionScheduler_Versions::initialize_latest_version()
#4 /home/wikinves/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /home/wikinves/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array in /home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_DataController.php on line 171
[11-Jun-2020 23:19:58 UTC] PHP Warning:  require_once(/home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/automattic/jetpack-constants/src/class-constants.php): failed to open stream: No such file or directory in /home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 168
[11-Jun-2020 23:19:58 UTC] PHP Fatal error:  require_once(): Failed opening required '/home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/automattic/jetpack-constants/src/class-constants.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/wikinves/public_html/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 168
[12-Jun-2020 15:22:15 UTC] PHP Fatal error:  Uncaught Error: Class 'WC_Regenerate_Images_Request' not found in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php:49
Stack trace:
#0 /home/wikinves/public_html/wp-includes/class-wp-hook.php(287): WC_Regenerate_Images::init('')
#1 /home/wikinves/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /home/wikinves/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /home/wikinves/public_html/wp-settings.php(540): do_action('init')
#4 /home/wikinves/public_html/wp-config.php(77): require_once('/home/wikinves/...')
#5 /home/wikinves/public_html/wp-load.php(37): require_once('/home/wikinves/...')
#6 /home/wikinves/public_html/wp-login.php(12): require('/home/wikinves/...')
#7 {main}
  thrown in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-wc-regenerate-images.php on line 49
```

**Expected behavior**
Woocommerce works and does not leave WP in an unusable state. 

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Activating the plugin shows the Wizard page and navigating to any other page renders WP completely unusable. 
```
PHP 7.3.18
WP: 5.4.2
Theme: Storefront 2.5.7, TwentyTwenty 1.4
Woocommerce: 4.2.0
```

**Comment by tammullen** [comment]
Hi @sean5446 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 
​
From the error message it seem like some files have not installed, can you try installing and activating WooCommerce again?
​
Please provide us with any other details about the issue which may help us to evaluate it further such as the other items in the system status report from **WooCommerce > System Status** in WordPress admin.

**Comment by sean5446** [comment]
Thanks @tammullen

The files do exist and have 755 permissions. 

Could it be that the code is looking for a relative path, not an absolute path? 

Am I supposed to tinker with PHP settings? Are any Pearl modules required? I believe my setup reaches the settings listed here: https://silicondales.com/tutorials/woocommerce/minimum-requirements-woocommerce/#WooCommerce_Official_Minimum_Requirements

I cannot get to **System Status** because the entire website is rendered unusable after activating.

**Comment by peterfabian** [comment]
Hi @sean5446 

The errors seem to indicate you might be missing some files from the WooCommerce package or there is an incorrect class loading map present on your site. 

Can you please try to delete the WooCommerce folder and reinstall the plugin to see if the situation improves?

Just to confirm--this happens for you with just the WooCommerce plugin active as the only plugin on the site?

Thanks!

**Comment by sean5446** [comment]
Thanks @peterfabian 

Yes, the problem is reproducible with ever subsequent reinstall of the plugin. I recorded my screen this time upon activation but am getting a different error.

https://www.youtube.com/watch?v=1WkN2jzT6Ik

I probably should have shown in the video that the files do exist and have 755 permissions. 
[Screenshot of files](https://wikinvestigation.com/files.png)

```[18-Jun-2020 13:35:38 UTC] PHP Warning:  include_once(/home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php): failed to open stream: No such file or directory in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 451
[18-Jun-2020 13:35:38 UTC] PHP Warning:  include_once(): Failed opening '/home/wikinves/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php' for inclusion (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 451
[18-Jun-2020 13:35:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_is_wp_default_theme_active() in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php:481
Stack trace:
#0 /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(469): WooCommerce->theme_support_includes()
#1 /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(156): WooCommerce->includes()
#2 /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(115): WooCommerce->__construct()
#3 /home/wikinves/public_html/wp-content/plugins/woocommerce/woocommerce.php(42): WooCommerce::instance()
#4 /home/wikinves/public_html/wp-content/plugins/woocommerce/woocommerce.php(46): WC()
#5 /home/wikinves/public_html/wp-settings.php(371): include_once('/home/wikinves/...')
#6 /home/wikinves/public_html/wp-config.php(78): require_once('/home/wikinves/...')
#7 /home/wikinves/public_html/wp-load.php(37): require_once('/home/wikinves/...')
#8 /home/wi in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 481```

**Comment by sean5446** [comment]
Another video with https turned off at the domain level and Wordpress `Settings -> General` `WordPress Address (URL)` and `Site Address (URL)` set to non-https URL

https://www.youtube.com/watch?v=exaSuqPTeCU

**Comment by sean5446** [comment]
Just had these errors emailed to me:
```WordPress version 5.4.2
Current theme: Storefront (version 2.5.7)
Current plugin:  (version )
PHP version 7.3.18



Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 17 of the file /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/wc-widget-functions.php. Error message: require_once(): Failed opening required '/home/wikinves/public_html/wp-content/plugins/woocommerce/includes/widgets/class-wc-widget-cart.php' (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear')```

```WordPress version 5.4.2
Current theme: Storefront (version 2.5.7)
Current plugin:  (version )
PHP version 7.3.18



Error Details
=============
An error of type E_ERROR was caused in line 110 of the file /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php. Error message: Uncaught Error: Class 'WC_Admin_Report' not found in /home/wikinves/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-dashboard.php:110
Stack trace:
#0 /home/wikinves/public_html/wp-admin/includes/template.php(1345): WC_Admin_Dashboard->status_widget('', Array)
#1 /home/wikinves/public_html/wp-admin/includes/dashboard.php(246): do_meta_boxes(Object(WP_Screen), 'normal', '')
#2 /home/wikinves/public_html/wp-admin/index.php(148): wp_dashboard()
#3 {main}
  thrown```

**Comment by peterfabian** [comment]
Sorry for the delay. Can you please share which hosting do you use? We haven't seen a lot of similar errors reported and it seems like a failure to read the files from the filesystem? We have accounts on larger hosting platforms, so might try to reproduce if we know more about the environment.

**Comment by peterfabian** [comment]
Apologies, I can see from the videos you're hosting with vpshared, I'll try to dig around to see what I can find...

**Comment by peterfabian** [comment]
Have you tried restarting the web server after you update the plugin? It seems to me there are basically two options, either the files are missing (which you confirmed they aren't) or webserver/PHP can't load them, so I would assume it's related to config of those components.

**Comment by sean5446** [comment]
I'm using VPShared on a the cheapest plan. You are probably correct that this is a host related issue since no one else is experiencing this/can't reproduce the bug. You can close this ticket. Thank you guys for your insights!!
