### ISSUE TITLE
Updated woocommerce => "There has been a critical error on your website."

### ISSUE THREAD

**Issue by angular12** [woocommerce/woocommerce#26756]
Upgraded woocommerce today because there was 5gigs of error messages generated by woocommerce in a week.  The upgrade disabled the entire website. "There has been a critical error on your website." Can't even access the dashboard.  

Searching I found the same errors reported from 3 months ago?!? and yet the current woocommerce update is still nuking websites? Wow. 

Is it still the solution to install an entire new wordpress installation and install woocommerce there and then find and copy over "4 tables" (name of each please)  Is that still the solution today (months later)? 

Also am i supposed to do this on a different domain or fine to just start from scratch on live domain. I have a backup but I can't do a restore because your update crippled the wordpress installation.

Company site is down in the meantime. 

_"You will have to create in all versions 4.0+ to create the 4 tables of ActionScheduler if they do not exist. Probably 90% of v.3+ users are having a problem they can't do anything about unless the tables do exist if they copy from newly installed 4.0+ on a new raw Wordpress installation."_

Fatal error: Uncaught RuntimeException: Error saving action: Error saving action: Table '[user]_mywpdb.wp_actionscheduler_actions' doesn't exist in /home/[user]/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44 Stack trace: #0 /home/[user]/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL) #1 /home/[user]/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action)) #2 /home/[user]/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action)) #3 /home/[user]/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/f in /home/[user]/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by tammullen** [comment]
Hi @angular12 

Thank you for reporting the issue. Action Scheduler is being developed in another repository: https://github.com/woocommerce/action-scheduler.
I am going to move your bug report there so that the right team could take a look further.
