### ISSUE TITLE
Fatal Error on Latest beta build

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#26831]
I just updated to the latest beta and got a fatal. I had to revert to 4.2. please advice.

Uncaught Error: Call to undefined method Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Deactivate_Plugin::possibly_add_note() in /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php:56 Stack trace: #0 [internal function]: Automattic\WooCommerce\Admin\Composer\Package::init() #1 /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/src/Packages.php(72): call_user_func() #2 /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/src/Packages.php(48): Automattic\WooCommerce\Packages::load_packages() #3 /var/docs/wptheme.tst/public/wp-includes/class-wp-hook.php(287): Automattic\WooCommerce\Packages::on_init() #4 /var/docs/wptheme.tst/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() #5 /var/docs/wptheme.tst/public/wp-includes/plugin.php(478): WP_Hook->do_action() #6 /var/docs/wptheme.tst/public/wp-settings.php(411): do_action() #7 /var/docs/wptheme.tst/public/wp-config.php(90): require_once('/var/docs/wpthe...') #8 /var/docs/wptheme in /var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php on line 56

**Comment by juliaamosova** [comment]
Hi @BackuPs,

Thank you for reporting the issue. It seems that the error is being caused by the WooCommerce Admin which is being developed in another repository: https://github.com/woocommerce/woocommerce-admin. 

I am going to move your bug report there so that the right team could take a look further.
