### ISSUE TITLE
Unhandled fatal error on capturing funds when PayPal returns an error response.

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#26960]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
There's a problem with error response handling for payment capture requests with PayPal.

**Expected behavior**
If I change order status to capture funds and there's an error response sent from PayPal, a proper error message is saved in PayPal logs and order notes without a crash. Order status gets reverted as it wasn't possible to capture the payment. 

**Actual behavior**
When I change the order status the whole screen goes blank with the fatal error message:

```
2020-07-06T07:36:26+00:00 CRITICAL Uncaught Error: Cannot use object of type WP_Error as array in /var/sites/t/siteaddressremoved/public_html/wp/wp-content/plugins/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-api-handler.php:118
Stack trace:
#0 /var/sites/t/siteaddressremoved/public_html/wp/wp-content/plugins/woocommerce/includes/gateways/paypal/class-wc-gateway-paypal.php(412): WC_Gateway_Paypal_API_Handler::do_capture(Object(Automattic\WooCommerce\Admin\Overrides\Order))
#1 /var/sites/t/siteaddressremoved/public_html/wp/wp-includes/class-wp-hook.php(289): WC_Gateway_Paypal->capture_payment(7796)
#2 /var/sites/t/siteaddressremoved/public_html/wp/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#3 /var/sites/t/siteaddressremoved/public_html/wp/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#4 /var/sites/t/siteaddressremoved/public_html/wp/wp-content/plugins/woocommerce/includes/class-wc-order.php(363): do_action('woocommerce_ord...', 7796, Object(Automattic\WooCommerce\Admin\Overrides\Ord in /var/sites/t/siteaddressremoved/public_html/wp/wp-content/plugins/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-api-handler.php on line 118
```

The order status remains Processing or Completed even though no funds were actually captured, there are also no order notes indicating the failure.

The error gets triggered in this line: https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/gateways/paypal/includes/class-wc-gateway-paypal-api-handler.php#L118:L122

Reversing the `if` and `else if` conditions here should prevent us from trying to get the body property of an error response and solve the problem. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

This is only reproducible on sites with cURL problems, firewall, or other issues preventing the server from communicating with PayPal. Still, even in cases like this the error should ideally be properly handled.

1. In **WooCommerce > Settings > Payments > PayPal**, set payment method to Authorize;
2. Place an order via PayPal, observe order status is On-Hold;
3. Change order status to Processing or Completed to capture the payment.
4. Observe the fatal error message when PayPal sends an error response such as this one:

```
2020-07-06T07:36:26+00:00 INFO DoCapture Response: WP_Error Object
(
    [errors] => Array
        (
            [http_request_failed] => Array
                (
                    [0] => cURL error 28: Connection timed out after 10001 milliseconds
                )

        )

    [error_data] => Array
        (
        )

)
``` 

**Screenshots**

![Screenshot](https://d.pr/i/65dhst+)
Screenshot: https://d.pr/i/65dhst

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

```
### WordPress Environment ###

WordPress address (URL): https://siteaddressremoved.com
Site address (URL): https://siteaddressremoved.com
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.3
PHP Post Max Size: 100 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.61.0
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.6.21
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: l7l8_
Total Database Size: 175.03MB
Database Data Size: 165.63MB
Database Index Size: 9.40MB
l7l8_woocommerce_sessions: Data: 135.16MB + Index: 2.50MB + Engine InnoDB
l7l8_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
l7l8_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
l7l8_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.58MB + Engine InnoDB
l7l8_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
l7l8_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
l7l8_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_woocommerce_shipping_zone_locations: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
l7l8_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_actionscheduler_actions: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
l7l8_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_actionscheduler_logs: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
l7l8_aiowps_events: Data: 2.02MB + Index: 0.00MB + Engine InnoDB
l7l8_aiowps_failed_logins: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
l7l8_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_aiowps_login_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_aiowps_login_lockdown: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
l7l8_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_blc_instances: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
l7l8_blc_links: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
l7l8_blc_synch: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_bwg_album: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_album_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_gallery: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_image: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_image_comment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_image_rate: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_image_tag: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_bwg_theme: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
l7l8_commentmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
l7l8_comments: Data: 0.40MB + Index: 0.19MB + Engine MyISAM
l7l8_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_gallery_bank: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_gallery_bank_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
l7l8_gallery_galleries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
l7l8_gallery_galleriesslides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
l7l8_gallery_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
l7l8_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
l7l8_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_ngg_pictures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_options: Data: 4.83MB + Index: 0.66MB + Engine MyISAM
l7l8_postmeta: Data: 10.82MB + Index: 2.85MB + Engine MyISAM
l7l8_posts: Data: 4.79MB + Index: 0.62MB + Engine MyISAM
l7l8_qsot_event_zone_to_order: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
l7l8_qsot_ticket_codes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
l7l8_term_relationships: Data: 0.06MB + Index: 0.15MB + Engine MyISAM
l7l8_term_taxonomy: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
l7l8_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_usermeta: Data: 0.36MB + Index: 0.28MB + Engine MyISAM
l7l8_users: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
l7l8_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
l7l8_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
l7l8_wc_order_product_lookup: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
l7l8_wc_order_stats: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
l7l8_wc_order_tax_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
l7l8_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
l7l8_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
l7l8_wd_fb_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wd_fb_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wd_fb_option: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wd_fb_theme: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
l7l8_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 546
bwg_gallery: 2
flamingo_contact: 830
flamingo_inbound: 1836
foogallery: 3
nav_menu_item: 26
ngg_gallery: 2
ngg_pictures: 28
o-discount: 2
o-list: 1
page: 30
post: 62
product: 112
product_variation: 57
pt_view: 7
qsot-event: 2
qsot-event-area: 1
qsot-venue: 1
rttpg: 1
shop_coupon: 8
shop_order: 507
shop_order_refund: 12
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
vtprd-rule: 1
wcs_ruleset: 17
woo_discount: 1
woo_discount_cart: 1
wpcf7_contact_form: 3
ywdpd_discount: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

All In One SEO Pack: by All in One SEO Team – 3.5.2
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.4

Broken Link Checker: by WPMU DEV – 1.11.13
Conditional Shipping for WooCommerce: by Lauri Karisola / WooElements.com – 2.0.4 – Installed version not tested with active version of WooCommerce 4.2.2
Honeypot for Contact Form 7: by Nocean – 1.14.1
Contact Form 7 Extension For Mailchimp: by Renzo Johnson – 0.5.20
Contact Form 7: by Takayuki Miyoshi – 5.1.9
Content Views: by Content Views – 2.3.2
Duplicate Post: by Enrico Battocchi – 3.2.4
Easy Image Collage: by Bootstrapped Ventures – 1.13.1
Enable Media Replace: by ShortPixel – 3.4.1
Enhanced Media Library: by wpUXsolutions – 2.7.2
Widget for Social Page Feeds: by Milap Patel – 6.1
Flamingo: by Takayuki Miyoshi – 2.1.1
FooBox Image Lightbox: by FooPlugins – 2.7.11
FooGallery: by FooPlugins – 1.9.25
Mailchimp for WooCommerce: by Mailchimp – 2.4.1 – Installed version not tested with active version of WooCommerce 4.2.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.8
Media File Renamer (Auto Rename): by Jordy Meow – 4.6.9
Show-Hide/Collapse-Expand: by Bunte Giraffe – 1.2.3
Page Builder by SiteOrigin: by SiteOrigin – 2.11.0
SiteOrigin CSS: by SiteOrigin – 1.2.8
SiteOrigin Widgets Bundle: by SiteOrigin – 1.17.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.25

Woo Discount Rules: by Flycart Technologies LLP – 1.9.12
WooCommerce Locations Pack: by dangoodman – 1.4.8.4
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.2 (update to version 2.0.3 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Max Quantity: by Isabel Castillo – 1.5.2 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Xero Integration: by WooCommerce – 1.7.30 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce: by Automattic – 4.2.2
WP Mail Logging: by MailPoet – 1.9.6
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

Smush: by WPMU DEV – 3.6.3
WP Super Cache: by Automattic – 1.7.1
Clef: by Clef – 2.6.4

### Inactive Plugins (14) ###

10Web Social Feed: by 10Web – 1.1.23
Akismet Anti-Spam: by Automattic – 4.1.6
BJ Lazy Load: by Bjørn Johansen
Aron Tornberg
angrycreative – 1.0.9

Booster for WooCommerce: by Pluggabl LLC – 5.0.0 – Installed version not tested with active version of WooCommerce 4.2.2
Bulk Edit Products, Prices & Attributes for Woocommerce (Basic): by XAdapter – 2.3.7 – Installed version not tested with active version of WooCommerce 4.2.2
Excel Like Price Change for WooCommerce and WP E-commerce - Light: by Holest Engineering – 2.2.15 – Installed version not tested with active version of WooCommerce 4.2.2
Hammy: by Noel Tock – 1.5.1
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
OpenTickets Community Edition: by Quadshot Software LLC – 2.10.0
Product Sort and Display for WooCommerce: by a3rev Software – 2.0.2 – Installed version not tested with active version of WooCommerce 4.2.2
Smart Manager For WooCommerce – Stock Management, Bulk Edit & more...: by StoreApps – 4.3.16
WooCommerce Blocks: by Automattic – 2.8.0
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5 – Installed version not tested with active version of WooCommerce 4.2.2
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #712 - /shop/
Basket: #170 - /cart/
Checkout: #172 - /checkout/
My account: #174 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: NorthChildTheme
Version: 0.1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: SiteOrigin North
Parent Theme Version: 1.7.11
Parent Theme Author URL: https://siteorigin.com/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: siteorigin-north/woocommerce/cart/cart.php
siteorigin-north/woocommerce/checkout/form-checkout.php
NorthChildTheme/woocommerce/emails/admin-new-order.php
NorthChildTheme/woocommerce/emails/customer-on-hold-order.php
siteorigin-north/woocommerce/loop/add-to-cart.php
siteorigin-north/woocommerce/loop/pagination.php
siteorigin-north/woocommerce/product-searchform.php
siteorigin-north/woocommerce/single-product/add-to-cart/simple.php
siteorigin-north/woocommerce/single-product/meta.php


### Action Scheduler ###

Complete: 404
Oldest: 2020-06-05 12:03:42 +0000
Newest: 2020-07-04 20:58:39 +0000

Pending: 4
Oldest: 2020-07-06 07:39:13 +0000
Newest: 2020-07-08 11:51:55 +0000

```
</details>

**Comment by juliaamosova** [comment]
Hi @madeincosmos,

Thanks for reporting this issue. I couldn't reproduce just yet - an issue on the PayPal side of things:

![Screen Shot 2020-07-07 at 1 36 50 PM](https://user-images.githubusercontent.com/19143190/86820431-0bbf5e00-c057-11ea-9b50-4bb75d5341b0.png)

I will get back to it again in a bit. However, it seems high priority so I am marking this issue as such.
