### ISSUE TITLE
After update to version 4.3.0, my site broken

### ISSUE THREAD

**Issue by cartoonistarif** [woocommerce/woocommerce#26985]
After update to version 4.3.0, my site http://www.toonsmag.com broken. Not working, white screen. In the admin dashboard, it says, “There has been a critical error on your website. Please check your site admin email inbox for instructions”. In frontend “There has been a critical error on your website”.
Is there anyone who has an idea of how to fix the issue?

Site send me an email with the following message:

WordPress version 5.4.2
Current plugin: WooCommerce (version 4.3.0)
PHP version 7.2.31

Error Details
=============
An error of type E_ERROR was caused in line 127 of the file /home/toonsmag/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php. Error message: Uncaught Exception: Invalid data store for admin note. in /home/toonsmag/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php:127
Stack trace:
#0 /home/toonsmag/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#1 /home/toonsmag/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note))
#2 /home/toonsmag/public_html/wp-content/plugins/woocommerce/includes/admin/notes/class-wc-notes-run-db-update.php(273): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct(‘1’)
#3 /home/toonsmag/public_html/wp-includes/class-wp-hook.php(287): WC_Notes_Run_Db_Update::show_reminder(Object(WP_Screen))
#4 /home/toonsmag/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#5 /home/toonsmag/p

**Comment by juliaamosova** [comment]
Hi @cartoonistarif,

Thank you for taking the time to report this issue, we really appreciate your help. We are looking at it as we speak. Thanks for your patience while we figure out the fix! We might have a few follow-up questions in a bit.

**Comment by kishandhanak** [comment]
Hello, I'm getting the same issue. Error message below:

WordPress database error: [Unknown column 'layout' in 'field list']
SELECT name, type, locale, title, content, content_data, status, source, date_created, date_reminder, is_snoozable, layout, image FROM wp_wc_admin_notes WHERE note_id = 19 LIMIT 1

Fatal error: Uncaught Exception: Invalid data store for admin note. in /public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php:127 Stack trace: #0 /public/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #1 /public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #2 /public/wp-content/plugins/woocommerce-wholesale-prices/includes/wc-admin-notes/class-wwp-install-acfw.php(107): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct('19') #3 /public/wp-includes/class-wp-hook.php(287): WWP_Install_ACFW->dismiss_install_acfwf_note('') #4 /home/sites/website in /public/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Notes/DataStore.php on line 127

There has been a critical error on your website. Please check your site admin email inbox for instructions.

**Comment by StefanPeev** [comment]
@juliaamosova I confirm the same error message.

**Comment by hxdev** [comment]
Same here! 

`
WordPress database error: [Unknown column 'layout' in 'field list']
SELECT name, type, locale, title, content, content_data, status, source, date_created, date_reminder, is_snoozable, layout, image FROM wp_wc_admin_notes WHERE note_id = 24 LIMIT 1

Fatal error: Uncaught Exception: Invalid data store for admin note. in /var/www/thewebsite/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php:127 Stack trace: #0 /var/www/thewebsite/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #1 /var/www/thewebsite/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #2 /var/www/thewebsite/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(109): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct('24') #3 /var/www/thewebsite/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name(Array) #4 /var/www/thewebsite/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Package.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes_Deactivate_Plugin in /var/www/thewebsite/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php on line 127
There has been a critical error on your website. Please check your site admin email inbox for instructions.
`

**Comment by JacobSussan** [comment]
I was able to fix this issue by manually adding a `layout` and `image` column to `wp_wc_admin_notes`.

After I finished the update and refreshed my database some of those rows were populated with text.

As far as I can tell this fixed the issue for me with no side effects, everything works now.

**Comment by kishandhanak** [comment]
@JacobSussan Thank for this, can you confirm what `type` the columns should be when adding `layout` and `image`? e.g. longtext, text, etc

**Comment by mensmaximus** [comment]
@kishandhanak 
layout | varchar(20)
image | varchar(200)

**Comment by claudiosanches** [comment]
cc @woocommerce/isotope

**Comment by damiannep** [comment]
Other reports of this issue in the forums:

- https://wordpress.org/support/topic/fatal-error-3558/#post-13129249
- https://wordpress.org/support/topic/woocommerce-error-after-update-to-4-3-0/
