### ISSUE TITLE
Woocommerce/Action Scheduler not working after upgrade

### ISSUE THREAD

**Issue by jonasrafael** [woocommerce/woocommerce#27117]
I try to upgrade to the latest woocommerce and not working more. Here in the github i see the action scheduler maybe can fix the wordpress but not:

```
#0 /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#3 /home/plantando/public_html/wp-content/plugins/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('action_schedule...', Array, 1595596942, 'action-schedule...')
#4 /home/plantando/public_html/wp-co in /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44
[24-Jul-2020 13:21:23 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Database error. in /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#3 /home/plantando/public_html/wp-content/plugins/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('action_schedule...', Array, 1595596943, 'action-schedule...')
#4 /home/plantando/public_html/wp-co in /home/plantando/public_html/wp-content/plugins/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44

```

**Comment by rrennick** [comment]
@jonasrafael Please see https://github.com/woocommerce/action-scheduler/issues/587#issuecomment-658168773. Closing this issue as a duplicate.
