### ISSUE TITLE
Fatal Error ActionScheduler_DBStore in 4.2x Woocommerce

### ISSUE THREAD

**Issue by justinahsnyder** [woocommerce/woocommerce#27141]
2020-07-27T02:31:04+00:00 CRITICAL Uncaught InvalidArgumentException: Unidentified action 51586 in /home/forestsuperfoods/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:458
Stack trace:
#0 /home/forestsuperfoods/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(117): ActionScheduler_DBStore->cancel_action('51586')
#1 /home/forestsuperfoods/public_html/wp-content/plugins/mailchimp-for-woocommerce/bootstrap.php(134): as_unschedule_action('MailChimp_WooCo...', Array, 'mc-woocommerce')
#2 /home/forestsuperfoods/public_html/wp-content/plugins/mailchimp-for-woocommerce/bootstrap.php(197): mailchimp_as_push(Object(MailChimp_WooCommerce_Cart_Update), 0)
#3 /home/forestsuperfoods/public_html/wp-content/plugins/mailchimp-for-woocommerce/includes/class-mailchimp-woocommerce-service.php(243): mailchimp_handle_or_queue(Object(MailChimp_WooCommerce_Cart_Update))
#4 /home/forestsuperfoods/public_html/wp-content/plugins/mailchimp-for-woocommerce/includes/cla in /home/forestsuperfoods/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 458

**Comment by tammullen** [comment]
Hi @justinahsnyder 

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.
​
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
​
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
​
**Screenshots**
If applicable, add screenshots to help explain your problem.
​
**Expected behavior**
A clear and concise description of what you expected to happen.
​
**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.
​
**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
​

**Comment by juliaamosova** [comment]
Hi @justinahsnyder,

Would you please confirm if you are still experiencing the issue with the latest version of WooCommerce 4.3.1?

**Comment by juliaamosova** [comment]
Hi @justinahsnyder,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
