### ISSUE TITLE
Running into this error in the fatal error logs for the site

### ISSUE THREAD

**Issue by lukecav** [woocommerce/woocommerce#27313]
```
2020-08-12T13:56:16+00:00 CRITICAL Uncaught Error: Call to a member function get_applied_coupons() on null in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php:452
Stack trace:
#0 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/CartCoupons.php(64): Automattic\WooCommerce\Blocks\StoreApi\Utilities\CartController->get_cart_coupons()
#1 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/AbstractRoute.php(77): Automattic\WooCommerce\Blocks\StoreApi\Routes\CartCoupons->get_route_response(Object(WP_REST_Request))
#2 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(1050): Automattic\WooCommerce\Blocks\StoreApi\Routes\AbstractRoute->get_response(Object(WP_REST_Request))
#3 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(376): WP_REST_Server-> in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php on line 452

2020-08-12T13:56:20+00:00 CRITICAL Uncaught Error: Call to a member function get_cart() on null in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php:410
Stack trace:
#0 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/CartItems.php(64): Automattic\WooCommerce\Blocks\StoreApi\Utilities\CartController->get_cart_items()
#1 /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Routes/AbstractRoute.php(77): Automattic\WooCommerce\Blocks\StoreApi\Routes\CartItems->get_route_response(Object(WP_REST_Request))
#2 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(1050): Automattic\WooCommerce\Blocks\StoreApi\Routes\AbstractRoute->get_response(Object(WP_REST_Request))
#3 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/rest-api/class-wp-rest-server.php(376): WP_REST_Server->dispatch(Object(W in /chroot/home/ae32bbea/iheartdogs.com/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/StoreApi/Utilities/CartController.php on line 410

2020-08-12T16:13:29+00:00 CRITICAL Uncaught Error: Call to undefined function register_block_type_from_metadata() in /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/blocks/index.php:62
Stack trace:
#0 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/class-wp-hook.php(287): register_core_block_types_from_metadata('')
#1 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#2 /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /chroot/home/ae32bbea/iheartdogs.com/html/wp-settings.php(546): do_action('init')
#4 /chroot/home/ae32bbea/iheartdogs.com/html/wp-config.php(88): require_once('/chroot/home/ae...')
#5 /chroot/home/ae32bbea/iheartdogs.com/html/wp-load.php(37): require_once('/chroot/home/ae...')
#6 /chroot/home/ae32bbea/iheartdogs.com/html/wp-blog-header.php(13): require_once('/chroot/home/ae...')
#7 /chroot/home/ae32bbea/iheartdogs.com/html/index.php(17): require('/chroot/home/ae...')
#8 {main}
  thrown in /chroot/home/ae32bbea/iheartdogs.com/html/wp-includes/blocks/index.php on line 62
```

**Comment by lukecav** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://iheartdogs.com
Site address (URL): https://iheartdogs.com
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ❌ Inactive 1.3.1
Log Directory Writable: ✔
WP Version: ❌ 5.4.2 - There is a newer version of WordPress available (5.5)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.17
PHP Post Max Size: 2 GB
PHP Time Limit: 600
PHP Max Input Vars: 16384
cURL Version: 7.29.0
NSS/3.44

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.31-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.2
WC Database Prefix: wp_
Total Database Size: 49975.71MB
Database Data Size: 20010.63MB
Database Index Size: 29965.08MB
wp_woocommerce_sessions: Data: 187.02MB + Index: 13.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 1.52MB + Index: 2.59MB + Engine InnoDB
wp_woocommerce_order_items: Data: 448.00MB + Index: 163.83MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 3090.00MB + Index: 3223.98MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 3.52MB + Index: 6.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 4.52MB + Index: 9.55MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 6.52MB + Index: 6.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hlm_customcat_products_archive: Data: 20.55MB + Index: 0.00MB + Engine InnoDB
hlm_customcat_product_meta_archive: Data: 154.66MB + Index: 0.00MB + Engine InnoDB
hlm_customcat_product_term_relationship_archive: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
hlm_products_archive: Data: 59.59MB + Index: 16.03MB + Engine InnoDB
hlm_product_meta_archive: Data: 833.00MB + Index: 589.78MB + Engine InnoDB
hlm_product_term_relationship_archive: Data: 5.52MB + Index: 7.03MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tblLocalZipCodes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tempTableCBDAutoshipScheduleItems: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tempTableCBDAutoshipSchedules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tempTableCBDPaymentTokens: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
tempTableToppersPurchasesAfterXDays: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tempTableUpdateCOGSProducts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tempTableUpdateCOGSProductVariations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
tmpAutoshipCBDOilCustomers20190322: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
tmpBDayClubCANCampaignUsers: Data: 27.56MB + Index: 43.70MB + Engine InnoDB
tmpBDayClubCANSMSCampaignUsers: Data: 1.52MB + Index: 2.45MB + Engine InnoDB
tmpBdaySubscriberOrders: Data: 1.52MB + Index: 0.45MB + Engine InnoDB
tmpBdaySubscribers: Data: 1.52MB + Index: 0.95MB + Engine InnoDB
tmpCANPastBuyers: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
tmpJune2020ShippedOrders: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
tmpMayNotCompleteOrders: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
tmpMonthEndShipStationOrders: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
tmpRemoveCCItems: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
tmpRemoveCCVariations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
tmp_multi_item_order_combinations: Data: 0.27MB + Index: 0.33MB + Engine InnoDB
wp_actionscheduler_actions: Data: 2.14MB + Index: 1.06MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 2.03MB + Index: 1.61MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ap_csv_export_data: Data: 621.00MB + Index: 245.66MB + Engine InnoDB
wp_ap_order_transporter_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ap_petition: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ap_petition_signup: Data: 14.52MB + Index: 0.00MB + Engine InnoDB
wp_ap_surveys: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_ap_survey_answers: Data: 54.59MB + Index: 0.00MB + Engine InnoDB
wp_ap_survey_participants: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_ap_survey_questions: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_ap_survey_response: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_bs_donation_purpose: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_bs_donation_report: Data: 140.69MB + Index: 46.61MB + Engine InnoDB
wp_bs_dropshipping_clarification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_feed_shelterdogs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_feed_shelterdogs_report: Data: 80.63MB + Index: 0.00MB + Engine InnoDB
wp_bs_other_donation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bs_other_donation_report: Data: 26.56MB + Index: 0.00MB + Engine InnoDB
wp_bs_product_size_chart: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 144.69MB + Index: 220.05MB + Engine InnoDB
wp_comments: Data: 2213.00MB + Index: 2215.94MB + Engine InnoDB
wp_cpf_custom_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cp_feeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_breed_info: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_dropshipper_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_emails: Data: 62.59MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_email_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_order_feedback_product_ratings: Data: 11.52MB + Index: 2.52MB + Engine InnoDB
wp_cy_popup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_pupart: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_pupart_orders: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_cy_scalablepress_api: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cy_scalablepress_api_request: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_cy_secret_store_passwords: Data: 69.61MB + Index: 17.58MB + Engine InnoDB
wp_cy_secret_store_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ewwwio_images: Data: 255.78MB + Index: 347.59MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hlm_birthday_automation_logs: Data: 138.69MB + Index: 0.00MB + Engine InnoDB
wp_hlm_birthday_club_automation: Data: 0.38MB + Index: 0.00MB + Engine InnoDB
wp_hlm_birthday_club_email_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_hlm_birthday_club_signups: Data: 115.67MB + Index: 132.56MB + Engine InnoDB
wp_hlm_discover_feed_sections: Data: 1.47MB + Index: 0.00MB + Engine InnoDB
wp_hlm_discover_feed_section_items: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_hlm_email_unsubscribe: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_hlm_hero_report_log: Data: 132.67MB + Index: 142.00MB + Engine InnoDB
wp_hlm_personalized_orders: Data: 3.52MB + Index: 0.52MB + Engine InnoDB
wp_hook_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ir_wc_tracking_emails: Data: 80.63MB + Index: 116.28MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_optimizer: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.14MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.31MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.39MB + Index: 0.11MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ngg_pictures: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wp_options: Data: 16.45MB + Index: 3.06MB + Engine InnoDB
wp_pmxe_exports: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 7218.91MB + Index: 19995.16MB + Engine InnoDB
wp_posts: Data: 1017.80MB + Index: 1139.64MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 41.06MB + Index: 31.22MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_seo_title_tag_category: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_seo_title_tag_tag: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_taxjar_record_queue: Data: 30.56MB + Index: 12.55MB + Engine InnoDB
wp_termmeta: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_terms: Data: 4.31MB + Index: 10.30MB + Engine InnoDB
wp_term_relationships: Data: 17.34MB + Index: 18.84MB + Engine InnoDB
wp_term_taxonomy: Data: 4.28MB + Index: 11.95MB + Engine InnoDB
wp_usermeta: Data: 933.45MB + Index: 812.86MB + Engine InnoDB
wp_users: Data: 46.23MB + Index: 42.72MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_autoship_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_autoship_log: Data: 17.55MB + Index: 0.00MB + Engine InnoDB
wp_wc_autoship_schedules: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_wc_autoship_schedule_items: Data: 0.34MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 41.56MB + Index: 48.05MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_google_experiments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_google_experiments_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_orders: Data: 1422.00MB + Index: 189.08MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wsluserscontacts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wslusersprofiles: Data: 12.52MB + Index: 5.55MB + Engine InnoDB
wp_yoast_indexable: Data: 109.66MB + Index: 54.95MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.06MB + Index: 0.28MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.41MB + Index: 0.41MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_links: Data: 7.52MB + Index: 2.39MB + Engine InnoDB
wp_yoast_seo_meta: Data: 10.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

affiliate_products: 1
attachment: 127895
displayed_gallery: 64
display_type: 15
forum: 362
gal_display_source: 5
ign_voucher: 1
lightbox_library: 8
nav_menu_item: 403
nf_sub: 561
ngg_gallery: 47
ngg_pictures: 458
oembed_cache: 1761
omapi: 4
page: 335
popups: 1
post: 11364
product: 6149
product-reviews: 1
product_variation: 289981
reply: 5034
revision: 15736
shop_coupon: 4820
shop_order: 1777092
shop_order_refund: 18759
smart_offers: 109
topic: 36780
ufaq: 50
user_request: 5
vc4_templates: 1
vc_grid_item: 2
wp_stream_alerts: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (64) ###

WooCommerce Blacklister: by Aelia – 1.0.5.200727
AP CSV Exporter: by Ananta Pattanayak – 0.1.0
AP Gift Message: by Ananta Pattanayak – 0.1.0
Autoship Cloud powered by QPilot: by Patterns In the Cloud LLC – 2.0.9
Autoship Cloud Solutions - Dynamic Pricing Extension: by Patterns In the Cloud LLC – 1.2.2 – Installed version not tested with active version of WooCommerce 4.3.1
Autoship Cloud Solutions - Utilities Extension: by Patterns In the Cloud LLC – 1.0.0 – Installed version not tested with active version of WooCommerce 4.3.1
Dropshipping Clarification: by Bibhakar Sarkar (Bibhu) – 1.1
BS Feed Shelter Dogs: by Bibhakar Sarkar (Bibhu) – 1.0
Product Instruction: by Bibhakar Sarkar (Bibhu) – 1.5
Cache Enabler: by KeyCDN – 1.3.5
Classic Editor: by WordPress Contributors – 1.5
Custom Post Type UI: by WebDevStudios – 1.7.4
iHeartDogs Birthday Club: by Sumit Paul – 1.0
CY Breed Info: by Ananta Pattanayak – 1.0
CY Order Feedback Email: by Ananta Pattanayak – 1.0
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 3.2.5
GP Premium: by Tom Usborne – 1.11.2
Discover Feed: by Sumit Paul – 1.0
WooCommerce Gift Certificates Pro: by IgniteWoo.com – 3.5.36 – Installed version not tested with active version of WooCommerce 4.3.1
HLM Custom Modifications: by Ivan Rodriguez – 0.1
Woocommerce Item Add To Cart Plugin: by Ivan Rodriguez – 4.0 – Installed version not tested with active version of WooCommerce 4.3.1
HLM Woocommerce Conversion Tags: by Ivan Rodriguez – 2.2 – Installed version not tested with active version of WooCommerce 4.3.1
Woocommerce Customer Service Lookup: by Ivan Rodriguez – 1.1 – Installed version not tested with active version of WooCommerce 4.3.1
Woocommerce Free Shipping Offer: by Ivan Rodriguez – 1.0 – Installed version not tested with active version of WooCommerce 4.3.1
Woocommerce Reports for HLM: by Ivan Rodriguez – 1.0 – Installed version not tested with active version of WooCommerce 4.3.1
Woocommerce Tracking Number Email Plugin: by Ivan Rodriguez – 1.3 – Installed version not tested with active version of WooCommerce 4.3.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.2.0
Klaviyo: by Klaviyo
Inc. – 2.2.3 – Installed version not tested with active version of WooCommerce 4.3.1

Max Mega Menu: by megamenu.com – 2.8
Members: by MemberPress – 3.0.10
Metorik Helper: by Metorik – 1.4.0 – Installed version not tested with active version of WooCommerce 4.3.1
Smart Slider 3 Pro: by Nextend – 3.4.1.8
OptinMonster API: by OptinMonster Team – 1.9.11 – Installed version not tested with active version of WooCommerce 4.3.1
Perfmatters: by forgemedia – 1.5.8
Redirection: by John Godley – 4.8
Scripts-To-Footer: by Joshua David Nelson – 0.6.4.1
SendGrid: by SendGrid – 1.11.8
Shared Counts: by Bill Erickson & Jared Atchison – 1.3.0
Smart Offers: by StoreApps – 3.10.3 – Installed version not tested with active version of WooCommerce 4.3.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.24
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.2.1
Compress JPEG & PNG images: by TinyPNG – 3.2.1
Two Factor: by Plugin Contributors – 0.6.0
Ultimate FAQs - WordPress FAQ Plugin: by Etoile Web Design – 1.9.5 – Installed version not tested with active version of WooCommerce 4.3.1
User Switching: by John Blackbourn & contributors – 1.5.5
Aelia Foundation Classes for WooCommerce: by Aelia – 2.0.21.200629
WooCommerce Cost of Goods: by SkyVerge – 2.9.8 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce - Custom Orders Table: by Liquid Web – 1.0.0-rc3 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Custom Popularity Orderby: by HomeLife Media – 2.0.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.19 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.2.7 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.27 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.36 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.37 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Square: by WooCommerce – 2.1.6
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.28 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Waitlist: by Neil Pie – 2.1.24
WooCommerce: by Automattic – 4.3.1 (update to version 4.3.2 is available)
Yoast SEO Premium: by Team Yoast – 14.7
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
New Relic Reporting for WordPress: by 10up – 1.3.1
WP Redis: by Pantheon
Josh Koenig
Matthew Boynes
Daniel Bachhuber
Alley Interactive – 1.1.0

Widget Disable: by required – 2.0.0

### Inactive Plugins (2) ###

CY Hello Popup: by Ananta Pattanayak – 1.2
WP Maintenance Mode: by Designmodo – 2.2.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: object-cache.php

### Must Use Plugins (1) ###

Nexcess Managed Apps: by Nexcess – 1.11.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1260 - /shop/
Cart: #1261 - /cart/
Checkout: #1262 - /checkout/
My account: #1263 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: GeneratePress Child
Version: 0.1
Author URL: https://tomusborne.com
Child Theme: ✔
Parent Theme Name: GeneratePress
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://tomusborne.com
WooCommerce Support: ✔

### Templates ###

Overrides: generatepress_child/woocommerce/cart/cart.php
generatepress_child/woocommerce/checkout/form-shipping.php
generatepress_child/woocommerce/checkout/review-order.php
generatepress_child/woocommerce/checkout/thankyou.php
generatepress_child/woocommerce/content-widget-product.php
generatepress_child/woocommerce/emails/customer-note.php
generatepress_child/woocommerce/emails/customer-processing-order.php
generatepress_child/woocommerce/emails/email-footer.php
generatepress_child/woocommerce/loop/add-to-cart.php
generatepress_child/woocommerce/loop/loop-end.php
generatepress_child/woocommerce/loop/loop-start.php
generatepress_child/woocommerce/loop/no-products-found.php
generatepress_child/woocommerce/loop/orderby.php
generatepress_child/woocommerce/loop/pagination.php
generatepress_child/woocommerce/loop/price.php
generatepress_child/woocommerce/loop/result-count.php
generatepress_child/woocommerce/loop/sale-flash.php
generatepress_child/woocommerce/order/order-details.php
generatepress_child/woocommerce/single-product/meta.php
generatepress_child/woocommerce/single-product/related.php


### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off
Webhooks Enabled: ✔

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Canceled: 2
Oldest: 2020-08-12 08:52:05 -0700
Newest: 2020-08-12 09:01:06 -0700

Complete: 3,829
Oldest: 2020-07-12 14:41:04 -0700
Newest: 2020-08-12 14:19:01 -0700

Failed: 4
Oldest: 2019-12-04 13:17:03 -0800
Newest: 2020-03-01 12:03:03 -0800

Pending: 2
Oldest: 2020-08-12 14:39:01 -0700
Newest: 2020-08-14 15:06:01 -0700

`

**Comment by juliaamosova** [comment]
Hi @lukecav,

Thank you for reporting the issue. It seems to be caused by the WooCommerce Product Blocks functionality which is being developed in another repository: https://github.com/woocommerce/woocommerce-gutenberg-products-block. 

I am going to move your bug report there so that the right team could take a look further.
