### ISSUE TITLE
CRITICAL Uncaught RuntimeException: Error saving action: Unable to save action.

### ISSUE THREAD

**Issue by aseelashraf** [woocommerce/woocommerce#27595]
im trying to access woocommerce in my Wordpress admin but I get this error
.. i tried several ways to solve this but no luck ..
PLEASE HELP ME
I tried to install action scheduler didn't work
I tried to downgrade/update woocommerce didn't work..

```
2020-09-04T23:08:40+00:00 CRITICAL Uncaught RuntimeException: Error saving action: Unable to save action. in /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php:33
Stack trace:
#0 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(109): ActionScheduler_wpPostStore->save_action()
#1 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_ActionFactory.php(59): ActionScheduler_ActionFactory->store()
#2 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/functions.php(18): ActionScheduler_ActionFactory->single()
#3 /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/queue/class-wc-action-queue.php(44): as_schedule_single_action()
#4 /var/www/vhosts/jopa in /var/www/vhosts/jopanda-market.com/httpdocs/wp-content/plugins/woocommerce-3.9.3/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 33
```

**Comment by lukecav** [comment]
Does the same issue happen if using WooCommerce 4.4.1 on the site?

**Comment by omidhajivali** [comment]
I have the same problem

**Comment by aseelashraf** [comment]
i solved the problem by installing fresh wordpress on a subdomain and then migrated 4 tables for action scheduler to the old website but make sure you delete the tables before

**Comment by juliaamosova** [comment]
Hi @aseelashraf,

Apologies for the delayed response here. Glad to hear you solved the issue.

I will move it to the Action Scheduler repository to see if there is anything for us to address further on it: https://github.com/woocommerce/action-scheduler.
