### ISSUE TITLE
WordPress database error: [Table 'user_domain.wp_actionscheduler_actions' doesn't exist]

### ISSUE THREAD

**Issue by savrip** [woocommerce/woocommerce#27603]
I'm having some issues, which I have researched in other threads, but I'm not coming up with a solution.  I have seen the plugin that is suppose to add the tables back, but that also is running into an error.  I thought I would start back at WooCommerce and see if there was a way to manually add the tables back.  Here is the errors generated by debug.log.  The table was undoubtedly removed by WP-Optimize before it was known what the table was for.

Wordpress 5.5.1
PHP Version 7.3.18
WooCommerce 4.4.1

`[07-Sep-2020 09:40:05 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (0) in /usr/home/jartigas59/public_html/2021acaconvention.com/wp-includes/functions.php on line 4669
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_groups' doesn't exist for query SELECT group_id FROM wp_actionscheduler_groups WHERE slug='action-scheduler-migration' made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_groups' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_groups` made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group
[07-Sep-2020 09:40:05 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_actions` made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action
[07-Sep-2020 09:40:05 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist in /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Objec in /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44
[07-Sep-2020 09:40:14 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT COUNT(DISTINCT claim_id) FROM wp_actionscheduler_actions WHERE claim_id != 0 AND status IN ( 'pending', 'in-progress') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_HybridStore->get_claim_count, ActionScheduler_DBStore->get_claim_count
[07-Sep-2020 09:40:14 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status='pending' AND a.scheduled_date_gmt <= '2020-09-07 09:40:14' ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='in-progress' ORDER BY scheduled_date_gmt DESC LIMIT 1 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE a.hook='action_scheduler/migration_hook' AND a.status='pending' ORDER BY scheduled_date_gmt ASC LIMIT 1 made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_next_scheduled_action, ActionScheduler_HybridStore->find_action, ActionScheduler_DBStore->find_action
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_groups' doesn't exist for query SELECT group_id FROM wp_actionscheduler_groups WHERE slug='action-scheduler-migration' made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_groups' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_groups` made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group
[07-Sep-2020 09:40:15 UTC] WordPress database error Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_actions` made by require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->schedule_migration, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action
[07-Sep-2020 09:40:15 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Error saving action: Table 'jartigas59_acaconvention.wp_actionscheduler_actions' doesn't exist in /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php:44
Stack trace:
#0 /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(242): ActionScheduler_DBStoreMigrator->save_action(Object(ActionScheduler_Action), NULL)
#1 /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_HybridStore->save_action(Object(ActionScheduler_Action))
#2 /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Objec in /usr/home/jartigas59/public_html/2021acaconvention.com/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/ActionScheduler_DBStoreMigrator.php on line 44
[07-Sep-2020 09:40:17 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (0) in /usr/home/jartigas59/public_html/2021acaconvention.com/wp-includes/functions.php on line 4669
`

**Comment by savrip** [comment]
Another quick addition I just discovered that might save some headache.  I do have Updraft backups.  Would you recommend I restore changes from newest to oldest and this would solve my problem?

**Comment by omidhajivali** [comment]
I have the same problem in my site
I created the table through a backup
and after this
received a new error:
"Error saving action: Unable to save action." in checkout page

**Comment by omidhajivali** [comment]
I also installed wordpress and woocommerce in a subdomain with new database
next from phpmyadmin move wp_actionscheduler tables to my mrimary database
problem solved
before change in db, Make a backup

**Comment by juliaamosova** [comment]
Hi @savrip,

Thank you for reporting the issue. It seems that it needs to be fixed in the Action Scheduler which is being developed in another repository: https://github.com/woocommerce/action-scheduler. 

I am going to move your bug report there so that we could take a look further at the right place.
