### ISSUE TITLE
Cannot add plugin to wordpress website on Hostinger platform

### ISSUE THREAD

**Issue by Pmeet** [woocommerce/woocommerce#27936]
Hello, 

I am facing the below issue while activating Woocommerce plugin on wordpress.
`
Warning: include_once(/home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php): failed to open stream: No such file or directory in /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/woocommerce.php on line 34

Warning: include_once(): Failed opening '/home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') in /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/woocommerce.php on line 34

Fatal error: Uncaught Error: Class 'WooCommerce' not found in /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/woocommerce.php:47 Stack trace: #0 /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/woocommerce.php(61): WC() #1 /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-admin/includes/plugin.php(2297): include('/home/u31543303...') #2 /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-admin/plugins.php(191): plugin_sandbox_scrape('woocommerce/woo...') #3 {main} thrown in /home/u315433039/domains/holyskincosmetics-com.preview-domain.com/public_html/wp-content/plugins/woocommerce/woocommerce.php on line 47
`

Please help me out with this.

Thank you.

**Comment by juliaamosova** [comment]
Hi @Pmeet,

Apologies for the delayed response here. Are you still experiencing these issues? If so, can you please confirm which version of WooCommerce are you trying to use?

**Comment by juliaamosova** [comment]
Hi @Pmeet,

As a part of this repository’s maintenance, I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
