### ISSUE TITLE
Woo 4.6: With Gutenberg plugin: Admin UI/ Analytics shows empty screen/react error

### ISSUE THREAD

**Issue by broksonic21** [woocommerce/woocommerce#27974]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If you have both WooCommerce 4.6 and Gutenberg plugin installed (we have 9.1.1, the latest), the Analytics UIs are all empty - and report a React Error:

`
Uncaught Error: An error occurred while running 'mapSelect': Cannot read property 'rows' of undefined
The error may be correlated with this previous error:
TypeError: Cannot read property 'rows' of undefined
    at tn (/wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/data/index.js?ver=1.6.1:1:714017)
    at /wp-content/plugins/woocommerce/packages/woocommerce-admin/dist/chunks/36.22aea36f504a5d4259ea.js:1:5313
    at Object.current (/wp-content/plugins/gutenberg/build/data/index.js?ver=947ad095cf534a8304fef92f3a4d3255:1:27739)
    at e (/wp-content/plugins/gutenberg/build/data/index.js?ver=947ad095cf534a8304fef92f3a4d3255:1:27366)
    at /wp-content/plugins/gutenberg/build/data/index.js?ver=947ad095cf534a8304fef92f3a4d3255:1:27475
    at Bh (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:9:8128)
    at oj (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:9:8221)
    at Aj (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:12:2488)
    at unstable_runWithPriority (/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:3:3396)
    at Da (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:7:824)

Original stack trace:
    at Ve (/wp-content/plugins/gutenberg/build/data/index.js?ver=947ad095cf534a8304fef92f3a4d3255:1:27158)
    at /wp-content/plugins/gutenberg/build/data/index.js?ver=947ad095cf534a8304fef92f3a4d3255:1:27714
    at we (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:8:293)
    at He (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:8:7055)
    at zj (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:14:22201)
    at Th (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:11:728)
    at tj (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:11:657)
    at Te (/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:10:7241)
    at /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:7:1114
    at unstable_runWithPriority (/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:3:3396)
`

**Expected behavior**
Analytics UI shows, no errors, with major plugins like Gutenberg.

**Actual behavior**
React Error, screen flashes then disappears

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. install WooCommerce 4.6.
2. Install Gutenberg 9.1.1
3. Go to Analytics/Overview

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### Active Plugins (12) ###
Gutenberg: by Gutenberg Team – 9.1.1
WooCommerce: by Automattic – 4.6.0

### Theme ###

Name: Storefront
Version: 2.8.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔
</details>

**Comment by juliaamosova** [comment]
Hi @broksonic21,

Thank you for reporting the issue. However, this issue had been indeed reported previously here https://github.com/woocommerce/woocommerce-admin/issues/5385. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
