### ISSUE TITLE
Critical ERROR_Woocommerce and Wordpress 4.6.1

### ISSUE THREAD

**Issue by kamadoandino** [woocommerce/woocommerce#28098]
Hi everyone.

I have a problem in my wordpress page, with woocommerce plugin.

Show this when i enter to wordpress:

Se ha producido un error del tipo E_ERROR en la línea 143 del archivo /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php. Mensaje de error: Uncaught Error: Class 'ActionScheduler_DataController' not found in /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/abstracts/ActionScheduler.php:143 Stack trace: #0 /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php(44): ActionScheduler::init('/var/www/wp-con...') #1 /var/www/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_Versions.php(59): action_scheduler_initialize_3_dot_1_dot_6() #2 /var/www/wp-includes/class-wp-hook.php(285): ActionScheduler_Versions::initialize_latest_version() #3 /var/www/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(Object(GEM_Official), Array) #4 /var/www/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #5 /var/www/wp-settings.php(409): do_action('plugins_loaded') #6 /var/www/wp-config.php(97): require_once('/var/www/wp-set...') #7 /var/www/wp-load.php(37): require_once('/var/www/wp-con...') #8 /var/www/wp-login.php(12): require('/var/www/wp-loa...') #9 {main} thrown
![critial error woocommerce](https://user-images.githubusercontent.com/73486688/97195651-97c9d280-1779-11eb-824c-fa233254dd59.jpg)

please help me

i dont know what i have to do

best regards

thanks

**Comment by juliaamosova** [comment]
Hi @kamadoandino,

Thank you for reporting the issue. It seems to be caused by the Action Scheduler package which is being developed in another repository: https://github.com/woocommerce/action-scheduler. 

I am going to move your bug report there so that we could take a look further there.
