### ISSUE TITLE
[GlobalStep - WooCommerce 4.7 + WordPress 5.6] "Fatal error" page is displayed upon visiting to "Installed plugins" page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28245]
## Bug Description:
"Fatal error" page is displayed upon visiting to "Installed plugins" page.

## Environment:
Windows 10, macOS Mojave:10.14.6 (18G103)
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari(Version 13.1.1 (14609.2.9.1.3))

## Steps To Reproduce:
1. Go to test site https://ephemeral-jamosova-20201110.atomicsites.blog/wp-admin/
1. Login with valid credentials.
1. Go to Plugins->Installed Plugins
1. Observe that fatal error is displayed upon visiting Installed plugins page.

## Actual Result:
"Fatal error" page is displayed upon visiting to "Installed plugins" page.

## Expected Result:
All installed plugins should be displayed upon visiting to "Installed plugins" page.

## Artifacts:

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://ephemeral-jamosova-20201110.atomicsites.blog
Site address (URL): https://ephemeral-jamosova-20201110.atomicsites.blog
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.6-beta3-49552
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 8.0.0RC3
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.72.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 2.91MB
Database Data Size: 1.39MB
Database Index Size: 1.52MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 0.30MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
customize_changeset: 1
page: 6
post: 3
product: 24
product_variation: 45
shop_coupon: 1
shop_order: 5
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Query Monitor: by John Blackbourn – 3.6.4
Akismet Anti-Spam: by Automattic – 4.1.7
Facebook for WooCommerce: by Facebook – 2.1.4 – Installed version not tested with active version of WooCommerce 4.7.0
Jetpack by WordPress.com: by Automattic – 9.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.6 – Installed version not tested with active version of WooCommerce 4.7.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Payments: by Automattic – 1.6.0 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Shipping & Tax: by Automattic – 1.25.2 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce: by Automattic – 4.7.0

### Inactive Plugins (0) ###


### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 21
Oldest: 2020-11-10 19:54:24 +0000
Newest: 2020-11-11 13:55:24 +0000

`
```
</details>

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for reporting the issue! 

Noting here that the error that is being experienced on https://ephemeral-jamosova-20201110.atomicsites.blog is as follows:

```
 Fatal error: Uncaught Error: call_user_func_array(): Argument woocommerce/woocommerce#1 ($function) must be a valid callback, function "auto_update_woocommerce" not found or invalid function name
in /srv/htdocs/__wp__/wp-includes/class-wp-hook.php on line 287

Call stack:

WP_Hook::apply_filters()
wp-includes/plugin.php:212
apply_filters()
wp-admin/includes/update.php:1061
wp_is_auto_update_forced_for_item()
wp-admin/includes/class-wp-plugins-list-table.php:235
WP_Plugins_List_Table::prepare_items()
wp-admin/plugins.php:533
```

Screenshot:

![fatal](https://user-images.githubusercontent.com/19143190/99000569-7c93ec80-2507-11eb-9bae-095d147a66ab.jpg)

This site has the following installed:
- Atomic ephemeral 
- WP: 5.6-beta3-49552
- WC: 4.7.0 RC1
- PHP: 8.0.0RC3

I am going to spin up another site to see if I can replicate it again.

**Comment by juliaamosova** [comment]
I ssh'ed to the site https://ephemeral-jamosova-20201110.atomicsites.blog to confirm the list of plugins installed on it and it is as follows:

```
149508745@ephemeral-jamosova-20201110.atomicsites.blog:~/wp-content/plugins$ ls
akismet                   index.php  kliken-marketing-for-google  query-monitor  woocommerce-beta-tester  woocommerce-services
facebook-for-woocommerce  jetpack    mailchimp-for-woocommerce    woocommerce    woocommerce-payments
```

I created another instance to see if I can replicate this error but I couldn't. I can successfully access the `Installed plugins` section. 

The new site has the following:

- Atomic ephemeral
- WP: 5.6-beta3-49552
- WC: 4.7.0
- PHP: 8.0.0RC3

I am keeping this issue open nonetheless to see if there will be other reports.

**Comment by ldr2273** [comment]
I'm able to replicate this as well in the following environment:

- Atomic ephemeral
- WP: 5.6-beta4-49590
- WC: 4.7.0
- PHP: 8.0.0RC3

Here is the error from the log:

```
2020-11-13T02:30:19+00:00 CRITICAL Uncaught TypeError: call_user_func_array(): Argument woocommerce/woocommerce#1 ($function) must be a valid callback, function "auto_update_woocommerce" not found or invalid function name in /srv/htdocs/__wp__/wp-includes/class-wp-hook.php:287
Stack trace:
#0 /srv/htdocs/__wp__/wp-includes/plugin.php(212): WP_Hook->apply_filters(NULL, Array)
woocommerce/woocommerce#1 /srv/htdocs/__wp__/wp-admin/includes/update.php(1061): apply_filters('auto_update_plu...', NULL, Object(stdClass))
woocommerce/woocommerce#2 /srv/htdocs/__wp__/wp-admin/includes/class-wp-plugins-list-table.php(235): wp_is_auto_update_forced_for_item('plugin', NULL, Object(stdClass))
woocommerce/woocommerce#3 /srv/htdocs/__wp__/wp-admin/plugins.php(533): WP_Plugins_List_Table->prepare_items()
woocommerce/woocommerce#4 {main}
thrown in /srv/htdocs/__wp__/wp-includes/class-wp-hook.php on line 287
```

The error was triggered when I installed the [WooCommerce Beta Tester plugin](https://wordpress.org/plugins/woocommerce-beta-tester/). Once installed, it threw the critical error and I could not access the Plugins page. Upon deactivating this, it resolved the issue for me.

**Comment by rodrigoprimo** [comment]
This is a duplicate of woocommerce/woocommerce#27530 which seems to have been fixed by https://github.com/woocommerce/woocommerce-beta-tester/pull/74. @rrennick, maybe we just need to release a new version of WooCommerce Beta Tester?

For now, I will just transfer this issue to the WooCommerce Beta Tester repository.
