### ISSUE TITLE
Unexpected error in E2E test run

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#28647]
When I run E2E tests locally, the following is logged to the console

```
Unhandled error

      at process.uncaught (node_modules/jest/node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)
      at Page.handleError (../../../node_modules/jest-environment-puppeteer/lib/PuppeteerEnvironment.js:17:11)
      at Page._handleException (../../../node_modules/puppeteer/lib/Page.js:523:10)
      at CDPSession.Page.client.on.exception (../../../node_modules/puppeteer/lib/Page.js:121:60)
```

The error doesn't cause the test run to fail so it isn't urgent that it be fixed. However, when one or more tests fail, this might be a red herring for the person trying to determine the cause of the failed test.

**Comment by rrennick** [comment]
I'm not seeing this in most test runs so I'll close it. If it starts happening again we can reopen.
