### ISSUE TITLE
Onboarding::has_woocommerce_support($theme) errors if theme contains files or directories without read permission.

### ISSUE THREAD

**Issue by neneboe** [woocommerce/woocommerce#28978]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Fatal PHP error occurs on all Woocommerce admin pages if:

  1. Woocommerce theme support is not declared in any of a theme's files and
  2. There is a subdirectory in the theme that doesn't have read permissions

The error originates from Onboarding::has_woocommerce_support($theme).

Full error from log:

```
PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(THE PRIVATE DIRECTORY): failed to open dir: Permission denied in /home/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php:585\nStack trace:\n#0 [internal function]: RecursiveDirectoryIterator->__construct()\n#1 [internal function]: RecursiveDirectoryIterator->getChildren()\n#2 /home/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php(585): FilterIterator->next()\n#3 /home/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php(542): Automattic\\WooCommerce\\Admin\\Features\\Onboarding::has_woocommerce_support()\n#4 /home/public_html/wp-content/plugins/woocommerce/packages/woocommerce- in /home/public_html/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/Features/Onboarding.php on line 585, referer: /wp-admin/edit.php?post_type=post
```

**Expected behavior**
The iterator should skip files and directories that don't have any read permissions.

**Actual behavior**
Varies depending on which dashboard page you're trying to load, but always results in a 500 error.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

  1. Set active theme to one that doesn't have `add_theme_support('woocommerce');` in it.
  2. Create a subdirectory in the theme and set it's permissions to 000.
  3. Go to a woocommerce dashboard page and check the Network tab in the browser's dev tools. There should be a 500 error there.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [no] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>
```
`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 4.9.2
REST API Version: ✔ 4.9.2
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1i
PHP Version: 7.4.13
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.7.32-0ubuntu0.18.04.1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.2
WC Database Prefix: wp_
Total Database Size: 10.69MB
Database Data Size: 5.61MB
Database Index Size: 5.08MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB + Engine
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_customermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_customers: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referralmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_sales: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_affiliate_wp_visits: Data: 0.30MB + Index: 0.08MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.23MB + Index: 0.28MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 18
nav_menu_item: 1
page: 9
post: 2
product: 8
product_variation: 60
revision: 3
shop_coupon: 2
shop_order: 674
shop_order_refund: 97

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

AffiliateWP: by Sandhills Development
LLC – 2.5.2

Antispam Bee: by pluginkollektiv – 2.9.3
Classic Editor: by WordPress Contributors – 1.6
Jetpack by WordPress.com: by Automattic – 9.3.1
WooCommerce Stripe Gateway: by WooCommerce – 4.7.0
WooCommerce Shipping & Tax: by Automattic – 1.25.6
WooCommerce Shipment Tracking: by WooCommerce – 1.6.26
WooCommerce: by Automattic – 4.9.2
WP Mail SMTP: by WPForms – 2.5.1

### Inactive Plugins (0) ###


### Must Use Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Custom Theme
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.4.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 36
Oldest: 2021-01-28 08:43:33 -0800
Newest: 2021-01-25 19:30:41 -0800

`
```
</details>

**Comment by neneboe** [comment]
Why choose to look for theme support by iterating through every file in every subdirectory instead of using the [`current_theme_supports`](https://developer.wordpress.org/reference/functions/current_theme_supports/) function? If there is a reason, maybe it deserves a code comment.

**Comment by juliaamosova** [comment]
Hi @neneboe,

Thank you for reporting the issue. It seems to be caused by the WooCommerce Admin which is being developed in another repository: https://github.com/woocommerce/woocommerce-admin. 

I am going to move your bug report there so that the right team could take a look further.
