### ISSUE TITLE
$post->ID returns wrong value

### ISSUE THREAD

**Issue by radoslavius** [woocommerce/woocommerce#29876]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
$post->ID contains wrong value and then wc_get_product returns false instead product object
User can`t edit product details

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
I am only server admin and user don`t give me more informations.

```
Na řádku č. 20 v souboru .../wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php došlo k chybě typu E_ERROR. Chybová zpráva: Uncaught Error: Call to a member function get_type() on bool in .../wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php:20
Stack trace:
#0 .../wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(33): include()
#1 .../wp-admin/includes/template.php(1389): WC_Meta_Box_Product_Data::output(Object(WP_Post), Array)
#2 .../wp-admin/edit-form-advanced.php(711): do_meta_boxes(Object(WP_Screen), 'advanced', Object(WP_Post))
#3 .../wp-admin/post.php(206): require('/www/hosting/st...')
#4 {main}
  thrown
```

![image](https://user-images.githubusercontent.com/3509024/117790809-fe13cf80-b249-11eb-8595-7736404e924a.png)

**Temporary fix**
Add if around quering product in `class-wc-meta-box-product-data.php`
```
                if(empty($thepostid)) {
                        $thepostid      = $post->ID;
                        $product_object = $thepostid ? wc_get_product( $thepostid ) : new WC_Product();
                }
```

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://...
Site address (URL): http://...
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 4.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.28-1+0~20210503.84+debian10~1.gbp6819da
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB-0+deb10u1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: wp_
Celková velikost databáze: 20.29MB
Velikost dat databáze: 13.46MB
Velikost indexu databáze: 6.83MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.28MB + Index: 0.36MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.03MB + Index: 0.22MB + Engine InnoDB
wp_postmeta: Data: 4.45MB + Index: 3.89MB + Engine InnoDB
wp_posts: Data: 3.36MB + Index: 0.66MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.20MB + Index: 0.39MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 300
customize_changeset: 1352
nav_menu_item: 12
page: 17
post: 1
product: 147
product_variation: 1472
revision: 204

### Security ###

Secure connection (HTTPS): ❌
					Váš obchod nepoužívá HTTPS. Zjistěte více o HTTPS a SSL certifikátech.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Jetpack by WordPress.com: o Automattic – 9.7
Pen: o htmlpie – 1.0.6
WooCommerce Shipping & Tax: o WooCommerce – 1.25.12
WooCommerce: o Automattic – 5.2.2
YITH WooCommerce Catalog Mode: o YITH – 2.0.13

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Obchod: ❌ Viditelnost stránky by měla být veřejná
Košík: #44 - /index.php/kosik/
Pokladna: #45 - /index.php/pokladna/
Můj účet: ❌ Viditelnost stránky by měla být veřejná
Obchodní podmínky: ❌ Stránka není zvolena

### Theme ###

Name: Pen
Version: 1.4.3
Author URL: https://www.htmlpie.com/about
Child Theme: ❌ – Pokud upravujete WooCommerce šablonu
kterou jste nevytvořili
doporučujeme použít odvozenou šablonu. Viz Jak vytvořit odvozenou šablonu (anglicky)

WooCommerce Support: ✔

### Templates ###

Archive Template: Vaše šablona obsahuje soubor woocommerce.php. Nebudete schopni přepsat vlastní šablonu woocommerce/archive-product.php
protože woocommerce.php má vyšší prioritu než archive-product.php. Je to z důvodu předcházení problémům se zobrazením.

Overrides: –

### Action Scheduler ###

Dokončeno: 963
Oldest: 2021-04-12 12:52:00 +0200
Newest: 2021-05-10 13:24:31 +0200


### Status report information ###

Generated at: 2021-05-11 11:14:39 +02:00
`
```
</details>

**Comment by barryhughes** [comment]
I agree we could be a little more defensive in this area:

[`$product_object = $thepostid ? wc_get_product( $thepostid ) : new WC_Product();`](https://github.com/woocommerce/woocommerce/blob/5.4.0/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L29)

This basically assumes that `$thepostid` is either going to be empty (such as if a new product is being created) or set to the ID of a product type (such as if an existing product is being edited). If I'm following your report correctly, in your case it is probably neither of those things: it's instead the ID of some other post type, which is why `wc_get_product()` is returning `false`.

Looking at the screenshot you shared, you can probably check this out by figuring out what post ID 3 relates to. Is it a page or a blog post, perhaps? Try navigating to `.../wp-admin/post.php?post=3&action=edit` and see what you see.

@radoslavius — this makes me wonder if the problem in your case (or your client's case) is the result of a conflict of some kind, so it may also be worth running [through these steps](https://docs.woocommerce.com/document/how-to-test-for-conflicts/), as you may be able to solve things locally ahead of any fix that we make. Let us know what you discover!

**Comment by alexis-coulombe** [comment]
For anyone having this issue, it's not a woocommerce bug. It's probably coming from the code in the theme you're using. In my case, it was a typo in an if condition. Instead of checking for equality ($_GET['post_type'] == 'some-post-type'), I was changing the parameter $_GET['post_type'] ($_GET['post_type'] = 'some-post -type').
