### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: string * int

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#30168]
A user reported a similar issue to #29768:

```
2021-06-24T04:06:58+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string * int in /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-discounts.php:87
Stack trace:
#0 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(47): WC_Discounts->set_items_from_cart(Object(WC_Cart))
#1 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(842): WC_Discounts->__construct(Object(WC_Cart))
#2 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1731): WC_Coupon->is_valid()
#3 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-cart.php(306): WC_Cart->apply_coupon('doghealthsoluti...')
#4 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(213): WC_Legacy_Cart->add_discount('doghealthsoluti...')
#5 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(292): WC_AJAX::apply_coupon('')
#6 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#7 /home/dh_aipfwr/xxx/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#8 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_apply_c...')
#9 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(292): WC_AJAX::do_wc_ajax('')
#10 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(false, Array)
#11 /home/dh_aipfwr/xxx/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#12 /home/dh_aipfwr/xxx/wp-includes/template-loader.php(13): do_action('template_redire...')
#13 /home/dh_aipfwr/xxx/wp-blog-header.php(19): require_once('/home/dh_aipfwr...')
#14 /home/dh_aipfwr/xxx/index.php(17): require('/home/dh_aipfwr...')
#15 {main}
  thrown in /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-discounts.php on line 87
```

They are on PHP 8.0.1 and WC 5.4.1. The error is recorded when trying to add a coupon to the checkout page.

**Comment by tammullen** [comment]
Hi @SiR-DanieL 

I tried reproducing this with WC 5.4.1 and PHP 8.0.7 and PHP 8.0.0
- Created a fixed cart discount coupon
- Created a fixed product discount coupon
- Created a percentage discount coupon
- Added products to cart and proceeded to checkout
- Added the above coupons on checkout page
- No errors logged and coupons applied as expect

I am adding the `needs developer feedback` label to this issue so that the Core team could take a look in case there is anything I'm missing similar to the resolved linked issue.

**Comment by roykho** [comment]
Thanks for reporting @SiR-DanieL - we will put in a cast to guard against this type of issue.
