### ISSUE TITLE
Breaks WordPress Network functionality

### ISSUE THREAD

**Issue by bugnumber9** [woocommerce/woocommerce#30417]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When WordPress Network is enabled (subdomains mode in my case) and WooCommerce is active on the main site, a number of critical errors happen when attempting to delete a sub-site.
Everything is back to normal when WooCommerce is deactivated on the main site.

**Expected behavior**
A sub-site can be deleted in Network Admin even when WooCommerce is active on the main site.

**Actual behavior**
When attempting to delete a sub-site in Network Admin and WooCommerce is active on the main site, "There has been a critical error on this website." happens.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Enable WordPress Network, subdomains mode.
2. Create and delete some sub-sites (so far so good).
3. Install WooCommerce, activate it on the main site.
4. Try to delete a sub-site in Network Admin and you'll get a critical error.

Here are the actual errors logged in PHP error log:
`
[04-Aug-2021 08:48:00 UTC] WordPress database error Table 'dbname_db.wp_3_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_3_actionscheduler_actions a LEFT JOIN wp_3_actionscheduler_groups g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='wc-admin-data' AND a.hook='wc-admin_delete_user_customers' AND a.status='pending' AND a.claim_id = 0 AND (a.hook LIKE '%[1]%' OR (a.extended_args IS NULL AND a.args LIKE '%[1]%') OR a.extended_args LIKE '%[1]%') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by wpmu_delete_blog, wp_delete_site, do_action('wp_uninitialize_site'), WP_Hook->do_action, WP_Hook->apply_filters, wp_uninitialize_site, remove_user_from_blog, do_action('remove_user_from_blog'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Schedulers\CustomersScheduler::schedule_user_delete, Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::schedule_action, Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::has_existing_jobs, WC_Action_Queue->search, as_get_scheduled_actions, ActionScheduler_DBStore->query_actions

[04-Aug-2021 08:48:00 UTC] WordPress database error Table 'dbname_db.wp_3_actionscheduler_groups' doesn't exist for query SELECT group_id FROM wp_3_actionscheduler_groups WHERE slug='wc-admin-data' made by wpmu_delete_blog, wp_delete_site, do_action('wp_uninitialize_site'), WP_Hook->do_action, WP_Hook->apply_filters, wp_uninitialize_site, remove_user_from_blog, do_action('remove_user_from_blog'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Schedulers\CustomersScheduler::schedule_user_delete, Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::schedule_action, WC_Action_Queue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id

[04-Aug-2021 08:48:00 UTC] WordPress database error Table 'dbname_db.wp_3_actionscheduler_groups' doesn't exist for query SHOW FULL COLUMNS FROM `wp_3_actionscheduler_groups` made by wpmu_delete_blog, wp_delete_site, do_action('wp_uninitialize_site'), WP_Hook->do_action, WP_Hook->apply_filters, wp_uninitialize_site, remove_user_from_blog, do_action('remove_user_from_blog'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Schedulers\CustomersScheduler::schedule_user_delete, Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::schedule_action, WC_Action_Queue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->get_group_id, ActionScheduler_DBStore->create_group

[04-Aug-2021 08:48:00 UTC] WordPress database error Table 'dbname_db.wp_3_actionscheduler_actions' doesn't exist for query SHOW FULL COLUMNS FROM `wp_3_actionscheduler_actions` made by wpmu_delete_blog, wp_delete_site, do_action('wp_uninitialize_site'), WP_Hook->do_action, WP_Hook->apply_filters, wp_uninitialize_site, remove_user_from_blog, do_action('remove_user_from_blog'), WP_Hook->do_action, WP_Hook->apply_filters, Automattic\WooCommerce\Admin\Schedulers\CustomersScheduler::schedule_user_delete, Automattic\WooCommerce\Admin\Schedulers\ImportScheduler::schedule_action, WC_Action_Queue->schedule_single, as_schedule_single_action, ActionScheduler_ActionFactory->single, ActionScheduler_ActionFactory->store, ActionScheduler_DBStore->save_action

[04-Aug-2021 08:48:00 UTC] PHP Fatal error:  Uncaught RuntimeException: Error saving action: Table 'dbname_db.wp_3_actionscheduler_actions' doesn't exist in .../public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:85
Stack trace:
#0 .../public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(177): ActionScheduler_DBStore->save_action(Object(ActionScheduler_Action))
#1 .../public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_ActionFactory.php(84): ActionScheduler_ActionFactory->store(Object(ActionScheduler_Action))
#2 .../public_html/wp-content/plugins/woocommerce/packages/action-scheduler/functions.php(36): ActionScheduler_ActionFactory->single('wc-admin_delete...', Array, 1628066885, 'wc-admin-data')
#3 .../public_html/wp-content/plugins/woocommerce/includes/queue/class-wc-action-queue.php(44): as_schedule_single_act in .../public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 85

[04-Aug-2021 08:48:00 UTC] WordPress database error Table 'dbname_db.wp_3_actionscheduler_actions' doesn't exist for query SELECT COUNT(DISTINCT claim_id) FROM wp_3_actionscheduler_actions WHERE claim_id != 0 AND status IN ( 'pending', 'in-progress') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_DBStore->get_claim_count

[04-Aug-2021 08:48:00 UTC] WordPress database error Table 'dbname_db.wp_3_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_3_actionscheduler_actions a WHERE 1=1 AND a.status='pending' AND a.scheduled_date_gmt <= '2021-08-04 08:48:00' LIMIT 0, 5 made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_DBStore->query_actions
`

Looks like it's trying to access WooCommerce-specific DB tables in every sub-site set of tables for some reason.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://evolutionbox.net
Site address (URL): https://evolutionbox.net
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: ✔
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.21
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.30-MariaDB-cll-lve
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_
Total Database Size: 5.83MB
Database Data Size: 3.16MB
Database Index Size: 2.67MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_2_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_options: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_2_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_2_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_2_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_2_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_3_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_options: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_3_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_3_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_3_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_3_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_5_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_options: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_5_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_5_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_5_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_5_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.5.2

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-08-04 08:47:48 +0000
Newest: 2021-08-04 08:47:48 +0000


### Status report information ###

Generated at: 2021-08-04 08:58:42 +00:00
`
```
</details>

**Comment by tammullen** [comment]
Hi @bugnumber9 ,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce-admin/issues/7141. A fix will be in WooCommerce Admin 2.5.0, which will be included in the upcoming WooCommerce 5.6.0.
We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Comment by bugnumber9** [comment]
@tammullen Isn't this a different issue? In #7141 the pre-requisite is WooCommerce being network-activated.
In my case WooCommerce is only active on the main site. The stack trace of the error is also different in my case.

**Comment by tammullen** [comment]
Thanks @bugnumber9 for the reply.

I can reproduce your error using your reproduction steps with WooCommerce 5.5.2 but it works as expected with WooCommerce 5.6.0 RC 1 so I believe it is related to the linked issue as the fix for that fixes this issue.
