### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: int - string

### ISSUE THREAD

**Issue by RafaelFunchal** [woocommerce/woocommerce#31057]
Hi there :)

I'm creating this new issue as I couldn't find other issues related to `int - string`. Let me know if you want me to comment on another issue.

While working on p9F6qB-7CT-p2, I found this error:

```
[30-Oct-2021 07:22:05 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int - string in /wordpress/plugins/woocommerce/5.8.0/packages/woocommerce-admin/src/WCAdminHelper.php:56
Stack trace:
#0 /wordpress/plugins/woocommerce/5.8.0/packages/woocommerce-admin/src/WCAdminHelper.php(67): Automattic\WooCommerce\Admin\WCAdminHelper::get_wcadmin_active_for_in_seconds()
#1 /wordpress/plugins/woocommerce/5.8.0/packages/woocommerce-admin/src/Notes/NoteTraits.php(25): Automattic\WooCommerce\Admin\WCAdminHelper::is_wc_admin_active_for(5184000)
#2 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/notes/class-wc-payments-notes-qualitative-feedback.php(35): WC_Payments_Notes_Qualitative_Feedback::wc_admin_active_for(5184000)
#3 /wordpress/plugins/woocommerce/5.8.0/packages/woocommerce-admin/src/Notes/NoteTraits.php(83): WC_Payments_Notes_Qualitative_Feedback::get_note()
#4 /srv/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments.php(940): WC_Payments_Notes_Qualitative_Feedback::possibly_add_note()
#5 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(303): WC_Payments::add_woo_admin_notes('')
#6 /wordpress/core/5.8.1/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/5.8.1/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#8 /wordpress/core/5.8.1/wp-admin/admin-ajax.php(45): do_action('admin_init')
#9 {main}
  thrown in /wordpress/plugins/woocommerce/5.8.0/packages/woocommerce-admin/src/WCAdminHelper.php on line 56
```

PHP 8.0
WooCommerce 5.8.0

Switching PHP from 8.0 to 7.4 made the site usable again.

**Comment by tammullen** [comment]
Hi @RafaelFunchal!

Thank you for reporting the issue. WooCommerce Admin is being developed in another repository: https://github.com/woocommerce/woocommerce-admin

I am going to move your bug report there so that the right team could take a look further.
