### ISSUE TITLE
[Fatal] PHP Fatal error: Uncaught Exception: Produto inválido | class-wc-product-data-store-cpt.php:228

### ISSUE THREAD

**Issue by lanej0** [woocommerce/woocommerce#51209]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

We observed the following fatal error in relation to WooCommerce 9.2.3:

[Link to code](https://github.com/woocommerce/woocommerce/blob/b71e6e22a8c7fdbe10314fb7696c3cb646a336c3/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php#L228)

Stack trace:
```
PHP Fatal error:  Uncaught Exception: Produto inválido. in /../plugins/woocommerce/9.2.3/includes/data-stores/class-wc-product-data-store-cpt.php:228
#0 /../plugins/woocommerce/9.2.3/includes/class-wc-data-store.php(159): WC_Product_Data_Store_CPT->read(Object(WC_Product_Simple))
#1 /../plugins/woocommerce/9.2.3/includes/abstracts/abstract-wc-product.php(139): WC_Data_Store->read(Object(WC_Product_Simple))
#2 /../plugins/woocommerce/9.2.3/includes/class-wc-product-simple.php(24): WC_Product->__construct(8630)
#3 /../plugins/woocommerce/9.2.3/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php(469): WC_Product_Simple->__construct(8630)
#4 /../plugins/woocommerce/9.2.3/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(163): WC_REST_Products_Controller->prepare_object_for_database(Object(WP_REST_Request), false)
#5 /../plugins/woocommerce/9.2.3/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php(252): WC_REST_CRUD_Controller->save_object(Object(WP_REST_Request), false)
#6 /../core/6.6.1/wp-includes/rest-api/class-wp-rest-server.php(1230): WC_REST_CRUD_Controller->update_item(Object(WP_REST_Request))
#7 /../core/6.6.1/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wc/v3/products...', Array, NULL)
#8 /../core/6.6.1/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#9 /../core/6.6.1/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/wc/v3/products...')
#10 /../core/6.6.1/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#11 /../core/6.6.1/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#12 /../core/6.6.1/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#13 /../core/6.6.1/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#14 /../core/6.6.1/wp-includes/class-wp.php(813): WP->parse_request('')
#15 /../core/6.6.1/wp-includes/functions.php(1336): WP->main('')
#16 /../core/6.6.1/wp-blog-header.php(16): wp()
#17 /../core/6.6.1/index.php(17): require('/wordpress/core...')
#18 {main}
  thrown in /../plugins/woocommerce/9.2.3/includes/data-stores/class-wc-product-data-store-cpt.php on line 228
```

### Expected behavior

No fatal error on invalid product

### Actual behavior

Fatal error with invalid product

### Steps to reproduce

We don't have steps to reproduce, but observed 922 instances of this problem on Fri Aug 30, 1200 UTC to 2359 UTC on one site. Hopefully, someone can dig in and apply a defensive check if appropriate. - To be updated after investigation.

### WordPress Environment

N/A

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/products/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by barryhughes** [comment]
Within [WC_REST_CRUD_Controller::save_object()](https://github.com/woocommerce/woocommerce/blob/9.5.1/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php#L161) we already catch [WC_Data_Exceptions](https://github.com/woocommerce/woocommerce/blob/9.5.1/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php#L186) and [WC_REST_Exceptions](https://github.com/woocommerce/woocommerce/blob/9.5.1/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-crud-controller.php#L188), but nothing else. Perhaps we need a catch-all (in this error, for instance, it's a top-level exception which is being thrown).

**Comment by pmcpinto** [comment]
I've taken a look and marked this ready for the engineering team to pick up.
